### DISCUSSION TITLE
prometheus-operator on Minikube / Accessing services

### DISCUSSION THREAD

**Discussion by hackermann** [prometheus-operator/kube-prometheus#1068] [Q&A]
First of all, I am a complete Newbie in K8s / Prometheus, and it seems I am doing something terribly wrong. I did the setup of the prometheus-operator as described in 'Quickstart', now I can access the dashboards, but I cannot access my own services anymore. I applied this minimal example:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginxserver
  labels:
    app: nginxserver
spec:
  containers:
    - name: testpod0
      image: nginx
      ports:
      - containerPort: 80
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginxserverservice
spec:
  selector:
    app: nginxserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
```

Then:

minikube service nginxserverservice --url

The service is not available. Then I type:

kubectl delete -f manifests/

Now I can access the service again. I'm pretty sure this is not a bug (right?), because it is such a minimal example. But what am I doing wrong? (Again, I'm a complete newbie, just wanted to play around a bit with Prometheus, I already read the complete README.md, but nothing useful there ..)

**Comment by ArthurSens** [comment]
Hey, it looks like you only missed the nodePort field on your port 🙂 
https://kubernetes.io/docs/concepts/services-networking/service/#nodeport.

E.g.: 
```
apiVersion: v1
kind: Service
metadata:
  name: nginxserverservice
spec:
  selector:
    app: nginxserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
```

Or you could just change the service type:
```
apiVersion: v1
kind: Service
metadata:
  name: nginxserverservice
spec:
  selector:
    app: nginxserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
```


You can always find out why services didn't start with the command: `kubectl describe service <service-name>`
