### DISCUSSION TITLE
kube-prometheus and self-managed Gitlab

### DISCUSSION THREAD

**Discussion by w3irdrobot** [prometheus-operator/kube-prometheus#1075] [Q&A]
I manage a self-managed Gitlab install. We are trying to use `kube-prometheus`, which is wonderful btw, as the place Gitlab can point to to show metrics in the UI when installing in environments and such. There is good documentation on all this. I have `kube-prometheus` set up and data populating in Prometheus. However, some of the labels are named slightly differently than what Gitlab is expecting for its integrations. 

Specifically I'm talking about the [Kubernetes metrics](https://docs.gitlab.com/ee/user/project/integrations/prometheus_library/kubernetes.html) it can pull. It expects there to be labels called `container_name` and `pod_name`. However, the Prometheus Operator [relabels them](https://github.com/prometheus-operator/prometheus-operator/blob/14fe68699023d0db1b123b30d0ddc7b53e2a7358/pkg/prometheus/promcfg.go#L576-L577) as `container` and `pod` instead, which is causing the queries Gitlab is expecting to return empty results. I've been just testing these in the Prom UI for now. If I change the labels in their queries to the correct names of the labels in the Prom UI, the queries work great.

This lead me into attempting relabeling in one of my `ServiceMonitor`s as such:

```yaml
spec:
  endpoints:
  - targetPort: 2112
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_pod_container_name
      targetLabel: container_name
    - sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: pod_name
```

Looking at the Target screen, I can see that after this, both `container_name` and `container` exist. Same for pods. However, when I query, I can still see that only `container` is available for querying on.

This may just be my inexperience with Prometheus, but does anyone know what might be going on here?
