### DISCUSSION TITLE
Adding plus args to prometheus-k8s statefulset

### DISCUSSION THREAD

**Discussion by kHRISl33t** [prometheus-operator/kube-prometheus#1198] [Q&A] [answered]
I'm trying to add a new container arg to prometheus-k8s statefulset:

```yaml
    spec:
      containers:
      - args:
        - --web.console.templates=/etc/prometheus/consoles
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention.time=24h
        - --web.enable-lifecycle
        - --storage.tsdb.no-lockfile
        - --web.route-prefix=/
+      - --web.external-url=<MY_CUSTOM_EXTERNAL_HOST>
```

How can I achieve this? (also I'm not completely understanding how this statefulset was generated, because it does not exist inside my manifests folder)

I tried to modify the statefulset via `kubectl edit` to verify it will work or not, but my changes are not reflected.
