### DISCUSSION TITLE
Ingress

### DISCUSSION THREAD

**Discussion by valeriia-nesterova-thermo** [prometheus-operator/kube-prometheus#1223] [Q&A]
Hello. Is it a way to set up ingresses for Grafana and Prometheus without jsonnet? Documentation says only about jsonnet, but it's quite complicated and requires additional installations. It's hard to convert jsonnet to json or even yaml, but does anyone successed?

**Comment by zan-cbsi** [comment]
yes - totally agree.  have you figured this out @valeriia-nesterova-thermo ?

**Comment by AlissonRS** [comment]
You can deploy the resources below and fix the NetworkPolicies to add the namespace selector for nginx (or just disable them), also make sure you update the host and the base64 "data auth" inside the Secret.

For the auth field, install `htpasswd`, run it with `htpasswd -c auth <username>`, this will generate an "auth" file with some text, encode it with base64 for the data auth field.

```

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: prometheus-k8s
  namespace: monitoring
spec:
  rules:
  - host: prometheus.example.com
    http:
      paths:
      - backend:
          service:
            name: prometheus-k8s
            port:
              name: web
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: alertmanager-main
  namespace: monitoring
spec:
  rules:
  - host: alertmanager.example.com
    http:
      paths:
      - backend:
          service:
            name: alertmanager-main
            port:
              name: web
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: grafana
  namespace: monitoring
spec:
  rules:
  - host: grafana.example.com
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              name: http
        path: /
        pathType: Prefix
---
apiVersion: v1
data:
  auth: YWRtaW46ZG9udGVkaXRoZXJldXNlaHRwYXNzd2RpbnN0ZWFk
kind: Secret
metadata:
  name: basic-auth
  namespace: monitoring
type: Opaque
```
