### DISCUSSION TITLE
KubeScheduler has disappeared from Prometheus target discovery

### DISCUSSION THREAD

**Discussion by amateu** [prometheus-operator/kube-prometheus#1368] [General]
------------
- add https metrics  prometheus-serviceMonitorKubeScheduler.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      component: kube-scheduler
```
targets scheduler display error "server returned HTTP status 403 Forbidden"
![图片](https://user-images.githubusercontent.com/41470914/132440508-7a86a893-ddee-4ebd-af87-62b465e9e0bd.png)

- add http metrics prometheus-serviceMonitorKubeScheduler.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https-metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      component: kube-scheduler
```
targets scheduler display error "server returned HTTP status 400 Bad Request"
![YWX5Z`({QC~0FVGV`)(P5A2](https://user-images.githubusercontent.com/41470914/132441558-9d981b38-3da2-4ebf-8405-ef6e1ef1e1ec.png)

- add tlsconfig ca prometheus-serviceMonitorKubeScheduler.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https-metrics
    scheme: https
    tlsConfig:
#      insecureSkipVerify: true
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      component: kube-scheduler
```
targets scheduler display error " x509: certificate is valid for 127.0.0.1, not 192.168.110.X"
![ZJ$5`HZ 6NF P(I6{~3L)3E](https://user-images.githubusercontent.com/41470914/132444155-7b568fc0-67c1-4ea8-b460-b9648d76dda8.png)

openssl.config
```
.....
......
[alt_names]
DNS.1 = localhost
DNS.2 = node1
DNS.3 = node2
DNS.4 = node3
DNS.5 = lb-apiserver.kubernetes.local
DNS.6 = etcd.kube-system.svc.cluster.local
DNS.7 = etcd.kube-system.svc
DNS.8 = etcd.kube-system
DNS.9 = etcd
IP.1 = 192.168.110.19
IP.2 = 192.168.110.20
IP.3 = 192.168.110.21
IP.4 = 127.0.0.1
````
