### DISCUSSION TITLE
alertmanagerconfig matches about namespace not work

### DISCUSSION THREAD

**Discussion by pycgo** [prometheus-operator/kube-prometheus#1539] [Q&A] [answered]
my alertmanagerconfigs

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: configlinkflowalertmanager
  labels:
    alertmanagerConfig: linkflowAlertmanager
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'webhook'
    matchers:
      - name: alertname
        value: KubePodCrashLooping
      - name: namespace
        value: linkflow
  receivers:
  - name: 'webhook'
    webhookConfigs:
    - url: 'http://xxxxx:1194/'
```

the web shows:   namespace become monitoring  ? why?  and alerts only in monitoring can send out 
can I send other namespace  or  all namespace alerts? 
```
route:
  receiver: Default
  group_by:
  - namespace
  continue: false
  routes:
  - receiver: monitoring-configlinkflowalertmanager-webhook
    group_by:
    - namespace
    match:
      alertname: KubePodCrashLooping
      namespace: monitoring
    continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
```
