### DISCUSSION TITLE
Creating a servicemonitor adds it to prometheus twice

### DISCUSSION THREAD

**Discussion by abrondijk** [prometheus-operator/kube-prometheus#1639] [Q&A] [answered]
When I create the following servicemonitor, it adds a duplicate job to the `prometheus.env.yaml` file:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pihole-prometheus-servicemonitor
  namespace: cattle-monitoring-system
  labels:
    name: pihole-prometheus-servicemonitor
    release: kube-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: pihole-exporter
      app.kubernetes.io/name: pihole-exporter 
  namespaceSelector:
    matchNames:
      - cattle-monitoring-system
  endpoints:
    - port: metrics
    - path: /metrics
```
From inside the prometheus pod: 
```bash
/etc/prometheus/config_out $ cat prometheus.env.yaml | grep pihole
- job_name: serviceMonitor/cattle-monitoring-system/pihole-prometheus-servicemonitor/0
    regex: (pihole-exporter);true
    regex: (pihole-exporter);true
- job_name: serviceMonitor/cattle-monitoring-system/pihole-prometheus-servicemonitor/1
    regex: (pihole-exporter);true
    regex: (pihole-exporter);true
```

At first I thought this was because perhaps one was already there before I created the servicemonitor, but when I deleted the servicemonitor again, both jobs were removed from the yaml file.

I had trouble getting this to work, so I have been deleting/recreating the servicemonitor a few times, perhaps that has something to do with it? 

What's causing this?

In case required, the service itself:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: cattle-monitoring-system
  labels:
    app.kubernetes.io/name: pihole-exporter
    app.kubernetes.io/instance: pihole-exporter
spec:
  ports:
    - protocol: TCP
      name: metrics
      port: 9617
  selector:
    app.kubernetes.io/name: pihole-exporter
    app.kubernetes.io/instance: pihole-exporter
```

**Comment by abrondijk** [comment]
I've not solved it yet, but I did find that it is probably not related to me deleting/recreating the servicemonitor. I uninstalled the chart and removed the namespace it was in, after recreating the namespace and reinstalling the chart, the issue persists.

**Reply by abrondijk** [reply]
Another thing I've noticed, is that one of the two, doesn't have an "endpoint" label, as show in the image below:
![image](https://user-images.githubusercontent.com/73667900/153779301-5af9f2dc-0750-4cd3-a96b-6d8f96a82854.png)
Though I am not sure what this means, perhaps someone else does?

**Comment by abrondijk** [comment, marked as answer]
Ahh I got it. Yaml formatting of course...

In my servicemonitor, I had the following:
```yaml
  endpoints:
    - port: metrics
    - path: /metrics
```
where it should have been:
```yaml
  endpoints:
    - port: metrics
      path: /metrics
```
