### DISCUSSION TITLE
Grafana - Changes in grafana-config.yaml are not loaded in it's config

### DISCUSSION THREAD

**Discussion by dnaranjor** [prometheus-operator/kube-prometheus#1644] [Q&A] [answered]
I'm using release 0.7!

1.- We are not using jssonnet at all
2.- We are directly changing the grafana-config.yaml and after changes are done, we apply the file in the cluster
3.- The secret is correctly created
4.- After secret creation, we enter the Grafana GUI using local credentials and inspect Server Admin > Settings > auth.anonymous section, validating no changes has been loaded.  We perform the validation a) without restarting Grafana, and b) after restarting Grafana, with the same results.

Here are the changes performed in the grafana-config.yaml file:

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 7.4.3
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC
    [auth.anonymous]
    # enable anonymous access
    enabled = true
type: Opaque
```

Any advice?

**Comment by dnaranjor** [comment, marked as answer]
Okay, so, to solve the problem in release 0.7:

1.- Create a new ConfigMap YAML file with the required configuration, like this (you can simply pick up a default grafana.ini file and attach it to the YAML file):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    ##################### Grafana Configuration Example #####################
    #
    # Everything has defaults so you only need to uncomment things you want to
    # change

    # possible values : production, development
    app_mode = production

    # instance name, defaults to HOSTNAME environment variable value or hostname if HOSTNAME var is empty
    ; instance_name = ${HOSTNAME}

    #################################### Paths ####################################
    [paths]
    # Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
    #
    ;data = /var/lib/grafana
```

2.- Change the Grafana Deployment YAML file, and add the grafana-config file in volumeMounts and volume sections, like this:

```
        volumeMounts:
        - mountPath: /etc/grafana/grafana.ini
          name: grafana-config
          subPath: grafana.ini
          readOnly: false
...
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - name: grafana-datasources
        secret:
          secretName: grafana-datasources
      - configMap:
          name: grafana-config
        name: grafana-config
```

3.- Redeploy Grafana, and that's it
