### DISCUSSION TITLE
How to use kube-prometheus to monitoring an external kubernetes?

### DISCUSSION THREAD

**Discussion by DesireWithin** [prometheus-operator/kube-prometheus#1666] [Q&A] [answered]
Hello,

Scenario is that I have a kube-prometheus in `k8s-A`. And then I want to monitoring another `k8s-B`. Both `k8s-A` and `k8s-B` are not a big k8s cluster.
Here is my questions:
Accorinding to this [blog](https://jpweber.io/blog/monitor-external-services-with-the-prometheus-operator/), add extenal service by using `service`+`endpoints`+`serviceMonitor` only support IP, so I can't expose service of `k8s-B` by ingress. Which means I have to use a lot of `NodePort Service`. If i want to monitoring `coredns` of `k8s-B`, I have to separate `metrics` port from existing coredns service, because a simple coredns service is like this:
```
...
  clusterIP: 10.96.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
...
```
So what is the best way to use kube-prometheus to monitoring multiple k8s? 
Is Prometheus Federation  an optional choose?

- Prometheus-master
    - kube-prometheus-A in K8S-A
    - kube-prometheus-B in K8S-B
   
Let `Prometheus-master` pull metrics from `kube-prometheus-A` and `kube-prometheus-B` separately, is it a good solution?
