### DISCUSSION TITLE
How to configure multiple routes in AlertmanagerConfig?

### DISCUSSION THREAD

**Discussion by charris-ca** [prometheus-operator/kube-prometheus#1671] [Q&A]
I currently have:

```

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanagerconfig
  labels:
    alertmanagerConfig: enabled
spec:
  route:
    groupBy: ['alert-1']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'alert-receiver'
```

But I would like to be able to specify multiple routes going to the same receiver with a different route/groupBy.  Something like this:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanagerconfig
  labels:
    alertmanagerConfig: enabled
spec:
  routes:
  - groupBy: ['alert-1']
     groupWait: 30s
     groupInterval: 5m
     repeatInterval: 12h
     receiver: 'alert-receiver'
  - groupBy: ['alert-2']
     groupWait: 30s
     groupInterval: 5m
     repeatInterval: 12h
     receiver: 'alert-receiver'
```

**Comment by simonpasquier** [comment]
you can reuse the same receiver across different groups but your second definition isn't valid (`routes` doesn't exist at the top-level).
Here is an example:

```

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanagerconfig
  labels:
    alertmanagerConfig: enabled
spec:
  route:
    groupBy: [alertname]
    receiver: 'alert-receiver'
    routes:
    - groupBy: [instance]
      matchers:
      - job="web"
      receiver: alert-receiver
  receivers:
  - name: alert-receiver
```

**Reply by charris-ca** [reply]
Gotcha, so I set up my alertmanagerconfig similar to what you had sent,
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: kafka-alertmanagerconfig
  labels:
    alertmanagerConfig: enabled
spec:
  route:
    groupBy: ['kafka', 'zookeeper', 'entityOperator', 'connect', 'kafkaExporter']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'kafka-slack'
    routes:
    - matchers:
        - alertname="ZookeeperRunningOutOfSpace"
      receiver: 'kafka-slack'
  receivers:
  - name: 'kafka-slack'
    slackConfigs:
    - channel: "#kafka-alerts-uat"
      apiURL:
        key: slacktoken
        name: kafka-slack-config
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
      sendResolved: true
```
and keep receiving this error
```
level=warn ts=2022-03-11T00:14:48.465040474Z caller=operator.go:1018 component=alertmanageroperator msg="skipping alertmanagerconfig" error="route[0]: json: cannot unmarshal string into Go struct field Route.matchers of type v1alpha1.Matcher" alertmanagerconfig=kafka/kafka-alertmanagerconfig namespace=prometheus alertmanager=prometheus-kube-prometheus-alertmanager
level=warn ts=2022-03-11T00:14:48.465104956Z caller=amcfg.go:1326 component=alertmanageroperator alertmanager=prometheus-kube-prometheus-alertmanager namespace=prometheus receiver="null" msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="unsupported value type" match_re="unsupported value type"
```


I've tried a bunch of different formats for the matchers sections but I can't seem to find the right one.  Seems like this is doing some weird parsing of the yaml map to implement this?
