### DISCUSSION TITLE
Change alertmanager sd behavior

### DISCUSSION THREAD

**Discussion by rodrigoscferraz** [prometheus-operator/kube-prometheus#1685] [Q&A] [answered]
Hello folks,
I'm trying to change the `- role: endpoints` to `- role: services` as described in [documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config)
```yaml
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
  alertmanagers:
  - path_prefix: /
    scheme: http
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - monitoring
```

There is a way to do this?

Thx in advance
