### DISCUSSION TITLE
Problem with define new target

### DISCUSSION THREAD

**Discussion by hatamiarash7** [prometheus-operator/kube-prometheus#1742] [Q&A]
Hi

I have installed `kminion` for Kafka. Now I need to add this as a new target.

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-kminion
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kminion-metrics
    app.kubernetes.io/part-of: kafka
spec:
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      app: kminion
  endpoints:
    - port: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kminion
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kminion-metrics
    app.kubernetes.io/part-of: kafka

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kminion
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kminion-metrics
    app.kubernetes.io/part-of: kafka
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
      - configmaps
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
    verbs:
      - list
      - watch
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kminion
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kminion-metrics
    app.kubernetes.io/part-of: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kminion
subjects:
  - kind: ServiceAccount
    name: kminion
    namespace: kafka
```

But it does not work and I can't see this in targets list. The [documentation](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md) is very unclear for me. What should I do?

**Note :** I used default way to install

```bash
kubectl apply --server-side -f manifests/setup
until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
kubectl apply -f manifests/
```
