### DISCUSSION TITLE
How to set "Alertmanager data source" in Alerting section for a Prometheus data source via helm chart

### DISCUSSION THREAD

**Discussion by phongvq** [prometheus-operator/kube-prometheus#1826] [Q&A] [answered]
Hello team,
In a Prometheus Data source UI in Grafana, we have a place to select **Alertmanager data source** (The alert manager that manages alerts for this data source).
I wonder how we can set it via helm chart or datasource provision file.

I've tried to specify `alertmanagerUid` for the datasource, but it didn't work.
```yaml
    - name: gmp-dataplatform-296603-prod-01
      access: proxy
      editable: false
      jsonData:
        tlsSkipVerify: true
        manageAlerts: true
        alertmanagerUid: Alertmanager
      orgId: 1
      type: prometheus
      url: http://prometheus.monitoring.svc:9090
      version: 1
```

Thank you guys very much.
