### DISCUSSION TITLE
about network policy configuration

### DISCUSSION THREAD

**Discussion by cateto** [prometheus-operator/kube-prometheus#1907] [Q&A]
hello everyone. 

I'm new here. so please understand dumb question xD

why grafana needs networkpolicy?

https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/grafana-networkPolicy.yaml

especially, this configuration below - makes it hard to expose the service
(nodeport, loadbalancer doesn't work with this configuration. so i delete it. )
```
ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
```
what for?
