### DISCUSSION TITLE
Traefik Ingress serve_from_sub_path

### DISCUSSION THREAD

**Discussion by bensch98** [prometheus-operator/kube-prometheus#1912] [Q&A]
After succesfully deploying kube-prometheus in my cluster I want to enable Ingress for the grafana dashboard.
I configured my Traefik IngressRoute and get now an error in the browser that says:

```
If you're seeing this Grafana has failed to load its application files


1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

4. Sometimes restarting grafana-server can help

5. Check if you are using a non-supported browser. For more information, refer to the list of [supported browsers](https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers).
``` 

My Traefik IngressRoute is configured as following:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "false"
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - match: Host(`grafana.example.com`) && Path(`/login`)
    kind: Rule
    services:
    - name: grafana
      port: 3000
      namespace: monitoring
```

So my question is: I see that there's a grafana-config.yaml in the manifests directory, where I can configure grafana.ini, but I don't know what to put in there to make the Ingress work.
