### DISCUSSION TITLE
LoadBalancer not functional for Prometheus API

### DISCUSSION THREAD

**Discussion by fmunteanu** [prometheus-operator/kube-prometheus#2009] [General]
I installed the `kube-prometheus-stack` Helm chart and everything is functional, except I cannot get to access the prometheus API with:

```yaml
prometheus:
  service:
    type: LoadBalancer
```

Everything works if I use `NodePort` type, but I prefer to use `LoadBalancer` type. I have no issues exposing Grafana:

```yaml
grafana:
  service:
    type: LoadBalancer
```

Services:

```shell
# kubectl get svc -n monitoring-system -o wide
NAME                                      TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE   SELECTOR
alertmanager-operated                     ClusterIP      None            <none>         9093/TCP,9094/TCP,9094/UDP   46m   app.kubernetes.io/name=alertmanager
monitoring-grafana                        LoadBalancer   10.43.94.169    192.168.4.13   80:31514/TCP                 46m   app.kubernetes.io/instance=monitoring,app.kubernetes.io/name=grafana
monitoring-kube-prometheus-alertmanager   ClusterIP      10.43.239.143   <none>         9093/TCP                     46m   alertmanager=monitoring-kube-prometheus-alertmanager,app.kubernetes.io/name=alertmanager
monitoring-kube-prometheus-operator       ClusterIP      10.43.90.202    <none>         443/TCP                      46m   app=kube-prometheus-stack-operator,release=monitoring
monitoring-kube-prometheus-prometheus     LoadBalancer   10.43.180.70    192.168.4.12   9090:30448/TCP               46m   app.kubernetes.io/name=prometheus,prometheus=monitoring-kube-prometheus-prometheus
monitoring-kube-state-metrics             ClusterIP      10.43.50.194    <none>         8080/TCP                     46m   app.kubernetes.io/instance=monitoring,app.kubernetes.io/name=kube-state-metrics
monitoring-prometheus-node-exporter       ClusterIP      10.43.134.11    <none>         9100/TCP                     46m   app.kubernetes.io/instance=monitoring,app.kubernetes.io/name=prometheus-node-exporter
prometheus-operated                       ClusterIP      None            <none>         9090/TCP                     46m   app.kubernetes.io/name=prometheus
```

Can you please provide some guidance how can I address the issue? Not sure why I need to create a `NetworkPolicy`, like mentioned in a different [discussion](https://github.com/prometheus-operator/kube-prometheus/discussions/1741). Even if I use a policy, I still cannot access the API from `192.168.4.12`, like I do from any cluster node when `NodePort` is set:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-network-policy
  namespace: monitoring-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus-stack
  ingress:
    - ports:
        - protocol: TCP
          port: 9090
```

Thank you.
