### DISCUSSION TITLE
Ist There Any Way to Make Resource Naming More Flexible?

### DISCUSSION THREAD

**Discussion by awcodify** [prometheus-operator/kube-prometheus#2037] [Q&A]
For example: I need prefix for resource naming:
- Service Account: sa-{service_name} -> sa-prometheus
- Deployment: dpl-{service_name} -> dpl-grafana
- ConfigMap: cm-{service_name} -> cm-node-exporter

**Comment by awcodify** [comment]
My current workaround is manipulating manifest using prefixSufficTransformer

```
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: deploymentPrefixer
prefix: "dpl-"
fieldSpecs:
- kind: Deployment
  path: metadata/name
---
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: serviceAccountPrefixer
prefix: "sa-"
fieldSpecs:
- kind: ServiceAccount
  path: metadata/name
---
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: configMapPrefixer
prefix: "ca-"
fieldSpecs:
- kind: ConfigMap
  path: metadata/name
```

Is there any ways to do dynamic resource naming or prefix suffic from kube-prometheus itself?
