### DISCUSSION TITLE
Why isn't my NetworkPolicy blocking Prometheus?

### DISCUSSION THREAD

**Discussion by mlbiam** [prometheus-operator/kube-prometheus#2044] [Q&A]
I have a `ServiceMonitor` in place.  Works great.  I added the following to the namespace that has the `Pod`s being monitored:

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-ingress
  namespace: XXXXX
spec:
  podSelector: {}
  policyTypes:
    - Ingress
status: {}
```

When I try to access the metrics endpoint from any `Pod` in the cluster, the connection times out as expected, EXCEPT the prometheus `Pod`s are still able to scrape metrics and I can't figure out why.  There's no `NetworkPolicy` allowing prometheus to hit those pods.  What am I missing?  Kubernetes is AKS using the Calico CNI.
