### DISCUSSION TITLE
How to add dashboards as code?

### DISCUSSION THREAD

**Discussion by nicl-dev** [prometheus-operator/kube-prometheus#2363] [Q&A]
Hey everyone,

I am now in my third project where I am using the kube-prometheus-stack and it's the third time I am struggling with handling dashboards as code. Currently I am testing stuff with the following `ConfigMap`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-dashboard
  namespace: test-ns
  labels:
    grafana_dashboard: "1"
  annotations:
    k8s-sidecar-target-directory: "/tmp/dashboards/k8"
data:
  logging-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "links": [],
      "liveNow": false,
      "panels": [],
      "refresh": "",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Old dashboard",
      "version": 0,
      "weekStart": ""
    }
```

Grafana will pick this up, but only if I restart the pod. I have found a reload url in the pod defintion but I would like to avoid calling the API every time I add, delete or change a Dashboard. 

After some googling I found [this blogpost](https://andidog.de/blog/2022-04-21-grafana-dashboards-best-practices-dashboards-as-code#_dashboards_as_code_and_gitops_committed_dashboards) that defines its own `dashboardProvider` and apparently its possible to set an `updateIntervalSeconds` on them:

```yaml
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10 # how often Grafana will scan for changed dashboards
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/default
          foldersFromFilesStructure: false
```

However, I couldnt find any values to add or edit a `dashboardProvider` for the kube-prometheus-stack. 

My question is, is there a prefered/best-practice way to handle this? It feels like everyone is using their own workaround for it right now (depending on what Helm Chart or Grafana flavor they are using) but there is no real documentation for it. But maybe that's just me because I am too confused. I would appreciate you kicking me in the right direction if that's the case! :D
