### DISCUSSION TITLE
Use hostpath-mode as persistent storage

### DISCUSSION THREAD

**Discussion by peacewang017** [prometheus-operator/kube-prometheus#2521] [Q&A]
I've already had a shared storage mounted at a same place (MOUNT_PONIT= "/data_share") on every node in my cluster, so I want set hostpath-mode to use "$MOUNT_POINT/prometheus" as the persistent storage of prometheus data.

However, I'm not familiar with CRD stuffs, when I apply these changes to kube-operator:
```yaml
# Create prometheus-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tele_data_share/prometheus
    type: DirectoryOrCreate

# Create prometheus-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
  labels:
    name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

# Add the following to prometheus-prometheus.yaml
spec:
  ...
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: ""
        resources:
          requests:
            storage: 20Gi
        accessModes:
        - ReadWriteOnce
        selector:
          matchLabels:
            name: prometheus-pvc
```

It seems like no data has been storaged under $MOUNT_PATH/prometheus, how can I use the hostpath as a persistent storage in kube-operator?
