### DISCUSSION TITLE
How to enable exemplars with User Workload Monitoring

### DISCUSSION THREAD

**Discussion by ahus1** [prometheus-operator/kube-prometheus#2562] [Q&A]
I want to use exemplars with my user workload monitoring to connect metrics to traces. 

What I found: something was implemented here - https://github.com/openshift/cluster-monitoring-operator/pull/2161 - and I found the `sendExemplars` option in the API. It seems connected to remote write, but I want to use it with the regular built-in Prometheus / Thanos queries etc. that comes with OpenShift. 

I'm using a Grafana that is deployed on OpenShift and that points to `https://thanos-querier.openshift-monitoring.svc:9091`

What I tried already: 

```
  config.yaml: |
    prometheus:
      remoteWrite:
        - sendExemplars: true
          url: https://***
```

After that UWM Prometheus was deployed with the exemplar feature enabled, but complained while the remote URL wasn't present. 

I still can't see the exemplars in Grafana. What am I missing? Is it supported at all?
