### DISCUSSION TITLE
Specifying Prometheus additionalScrapeConfigs in jsonnet

### DISCUSSION THREAD

**Discussion by alexdyas** [prometheus-operator/kube-prometheus#2664] [Q&A]
Hi,

I'm struggling to specify `additionalScrapeConfigs` in my jsonnet configuration.

This is what I'm trying :
```
...
      prometheus+:: {
        namespaces: [],
        spec+: {
          additionalScrapeConfigs: {
            key: 'kube-prometheus-my-additional-config.yaml',
            name: 'my-additional-config',
...
```
The Kubernetes secret (`my-additional-config`) is present.

I'm not seeing the configuration in the Prometheus k8s resource.

However if I apply this Kubernetes patch, I see the configuration applied, and it works:
```
spec:
  additionalScrapeConfigs:
    key: kube-prometheus-nissa-additional-config.yaml
    name: nissa-additional-config
```

Any help appreciated, thanks.

Alexander
