### DISCUSSION TITLE
I want to modified grafana smtp config but I CAN NOT FIND grafana,ini

### DISCUSSION THREAD

**Discussion by seanlin1326** [prometheus-operator/kube-prometheus#562] [General]
I want to add more user in grafana by send email
But I found some error
<img width="762" alt="smtp" src="https://user-images.githubusercontent.com/58818014/83963626-1234ab80-a8da-11ea-8753-78d4dee7d326.PNG">

I want to find grafana.ini to modified this
<img width="518" alt="smtp2" src="https://user-images.githubusercontent.com/58818014/83963683-68095380-a8da-11ea-8047-1736020c0927.PNG">
but my eye is bad
so I can not find grafana.ini in kube-prometheus
how to find  grafana.ini

**Comment by olegmayko** [comment]
The project itself doesn't contain static grafana.ini, you need to customise it  as shown in [this readme](https://github.com/brancz/kubernetes-grafana#config-customization)

**Comment by songrijie** [comment]
Alternative to what @olegmayko said.

Since [grafana can be configured with env variables](https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables),  you may create a simple libsonnet like this.  Do not forget to include this libsonnet in entrypoint mixin.  

```
local k = import 'ksonnet/ksonnet.beta.4/k.libsonnet';
local env = k.apps.v1.deployment.mixin.spec.template.spec.containersType.envType;

{
    _config+:: {
        grafana+: {
            env+: [
                // SMTP
                env.new('GF_SMTP_ENABLED', 'true' ),
                env.new('GF_SMTP_FROM_ADDRESS', 'system@example.com'),
                env.new('GF_SMTP_HOST','smtp.example.com:465'),
                env.new('GF_SMTP_USER','system@example.com'),
                env.new('GF_SMTP_PASSWORD','example'),

            ],
        },
    },
}
```

This idea comes from [brancz/kubernetes-grafana](https://github.com/brancz/kubernetes-grafana/blob/release-0.1/grafana/grafana.libsonnet#L214)

**Reply by rsoika** [reply]
Sorry for asking a stupid question:
How should I create the libsonnet? Should I create a file and call some kubectl command? Or shoud I ssh into the grafana container and do something there?
I am totally lost . I simply whant to edit the smtp configuration from grafana - how do do this?

**Reply by olegmayko** [reply]
you'd need to follow the[ compiling process](https://github.com/prometheus-operator/kube-prometheus#compiling) and add the snippet from comment above into example.jsonnet.

**Comment by rsoika** [comment]
Ok, finally I found a more elegant way using kustomizaion. 

I created a kustomization.yaml file like this one:

```
namespace: monitoring

bases:
- https://github.com/prometheus-operator/kube-prometheus

resources:
- ingress.yaml

patchesStrategicMerge:
- grafana-env.yaml
```

My grafana-env.yaml file looks like this:

```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    spec:
      containers:
      - name: grafana
        env:
          - name: GF_SMTP_ENABLED
            value: "true"
          - name: GF_SMTP_HOST
            value: "my-mailgateway.kube-system:25"
          - name: GF_SMTP_FROM_ADDRESS
            value: "info@foo.com"
```

To install and customize my setup a run:

```
# Checkout the project form Github
$ cd ~/kube-prometheus
$ kubectl apply -f manifests/setup
$ until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
$ kubectl apply -f manifests/

# Customize
$ kubectl apply --kustomize ../i/monitoring/
```
