### DISCUSSION TITLE
servicemonitor  can not show on promethues target

### DISCUSSION THREAD

**Discussion by dingbin90** [prometheus-operator/kube-prometheus#604] [General]
I create namespace  kube-dev

this is deployment

```
kind: Service
apiVersion: v1
metadata:
  name: example-app
  namespace: kube-dev
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
  - name: web
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: registry-vpc.cn-beijing.aliyuncs.com/zhjw/nginx:20200630151319
        ports:
        - name: web
          containerPort: 80
this is servicemonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-example-app
  namespace: kube-dev
  labels:
    release: mypro 
spec:
  namespaceSelector:
    matchNames:
    - kube-dev
  selector: 
    matchLabels:
      app: example-app
  endpoints:
  - port: web
    path: /
```

i am apply this yaml ,but it cat not show on promethues target
if i change namespace to default or kube-system or monitoring ,it can show on  promethues target ,i do not why
