### DISCUSSION TITLE
Prometheus target is added but not discovered (0/0 up)

### DISCUSSION THREAD

**Discussion by efotopoulou** [prometheus-operator/kube-prometheus#723] [Q&A] [answered]
I successfully deploy deploy my app at kubernetes. The ServiceMonitor is also added but no targets are discovered (0/0 up) .
The application is an nginx server with the relevant nginx-prometheus-exporter sidecar. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example-v3
  labels:
    app: nginx-example-v3
spec:
  selector:
    matchLabels:
      app: nginx-example-v3
  template:
    metadata:
      labels:
        app: nginx-example-v3
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: "config"
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
      - name: exporter
        image: nginx/nginx-prometheus-exporter:0.8.0
        ports:
        - containerPort: 9113
      volumes:
        - name: "config"
          configMap:
            name: "nginx-example-v2-config"
            
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-example-v3
  name: nginx-example-v3
spec:
  type: LoadBalancer
  selector:
    app: nginx-example-v3
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: http-exporter
    port: 9113
    targetPort: 9113
```
After that i can see the nginx custom metrics exposed at the /metrics API:
![Screenshot_20201012_171900](https://user-images.githubusercontent.com/1914256/95756938-22f19580-0caf-11eb-8795-96e6d881830c.png)

Then i apply the monitoring service:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-example-v3
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: web
  selector:
    matchLabels:
      app: nginx-example-v3
```
i can see that the service is successfully added at prometheus "Service Discovery" section:
![Screenshot_20201012_171250](https://user-images.githubusercontent.com/1914256/95756347-57b11d00-0cae-11eb-917c-1ca2e5bc3255.png)

BUT no targets are discovered (0/0 up) on behalf of prometheus  
![Screenshot_20201012_171438](https://user-images.githubusercontent.com/1914256/95756717-d27a3800-0cae-11eb-9a6c-e10d17ca9e3b.png)

What i am missing???
Any help is really apreciated since i have been stuck on this many days!
Thank you very much in advance. :-)

**Comment by efotopoulou** [comment, marked as answer]
I slightly changed the service manifest and i am able to get the metrics now.
sorry for the new discussion. i hope my manifests help other persons to configure their services.
This is the updated manifest.
:-)

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-example-v3
  name: nginx-example-v3
spec:
  type: LoadBalancer
  selector:
    app: nginx-example-v3
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: web
    port: 9113
    targetPort: 9113
```
