### DISCUSSION TITLE
"Client Secret" configuration for Azure Monitor datasource

### DISCUSSION THREAD

**Discussion by rflume** [prometheus-operator/kube-prometheus#866] [Q&A]
Hi, 

I'm trying to configure an Azure Monitor datasource via grafana.additionalDataSources.
With the config, the datasource will be added successfully.
However, after every restart of grafana the `Client Secret` and the `Default Subscription` have to be set manually.

```yml
  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    version: 1
    id: 2
    orgId: 1
    typeLogoUrl: public/app/plugins/datasource/grafana-azure-monitor-datasource/img/logo.jpg
    url: /api/datasources/proxy/2
    access: proxy
    isDefault: false
    readOnly: false
    editable: true
    jsonData:
      timeInterval: 30s
      azureLogAnalyticsSameAs: true
      cloudName: azuremonitor
      clientId: $GF_AZURE_CLIENT_ID
      tenantId: $GF_AZURE_TENANT_ID
      subscriptionId: $GF_AZURE_SUBSCRIPTION_ID
```

Is there any way to set the secret for the initialization of Grafana already?
