### DISCUSSION TITLE
Critical alerts not firing

### DISCUSSION THREAD

**Discussion by acarsercan** [prometheus-operator/kube-prometheus#896] [Q&A]
Hi,

I'm failing to get prometheus rule  with severity Critical to alert to Slack, if I change the severity for alertmanager to warning, everything works

Stack
kube-prometheus-stack- 0.43.2
Kubernetes 1.17

Prometheus alert manager config (helm)
```
    alertmanager:
      enabled: true
      config:
        route:
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 10m
        repeat_interval: 3h
          receiver: 'null'
          routes:
          - match:
              alertname: Watchdog
            receiver: 'null'
          - match:
              severity: critical
            receiver: 'slack'
        receivers:
        - name: 'null'
        - name: 'slack'
          slack_configs:
          - api_url: 'https://XXXX'
            send_resolved: true

```

Prometheus rule to trigger

```
  spec:
    groups:
    - name: kubernetes-apps
      rules:
      - alert: KubePodCrashLooping
        annotations:
          description: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container
            }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
          runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
          summary: Pod is crash looping.
        expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",
          namespace=~".*"}[5m]) * 60 * 5 > 0
        for: 15m
        labels:
          severity: critical
```

I have a pod which is crash looping and in prometheus UI /alerts I can see the alert is "PENDING"

Thank you
