### DISCUSSION TITLE
kubelet.rules failed to evaluate

### DISCUSSION THREAD

**Discussion by safoorsafdar** [prometheus-operator/kube-prometheus#988] [Q&A] [answered]
Facing Evaluating rule failed for below rule: 

```
    - expr: |
        histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_duration_seconds_bucket[5m])) by (instance, le) * on(instance) group_left(node) kubelet_node_name{job="kubelet", metrics_path="/metrics"})
      labels:
        quantile: "0.99"
      record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile
```

When run directly to Prometheus server facing below error:
`Error executing query: found duplicate series for the match group {instance="172.31.248.10:10250"} on the right hand-side of the operation: [{__name__="kubelet_node_name", endpoint="https-metrics", instance="172.31.248.10:10250", job="kubelet", metrics_path="/metrics", namespace="kube-system", node="a0310pnxenwrk04", service="prometheus-operator-kubelet"}, {__name__="kubelet_node_name", endpoint="https-metrics", instance="172.31.248.10:10250", job="kubelet", metrics_path="/metrics", namespace="kube-system", node="a0310pnxenwrk04", service="kubelet"}];many-to-many matching not allowed: matching labels must be unique on one side`
