### ISSUE TITLE
Rename example-group in Watchdog alert

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/kube-prometheus#1027]
Seems like we have Watchdog alert group called example-group, might be better to call it something else like core-group maybe?
https://github.com/prometheus-operator/kube-prometheus/blob/44008b2682546fa738af5967ddfad86cd69b3e37/examples/existingrule.yaml#L1-L4

Lets agree on naming and would be great first issue I think.

cc @paulfantom @brancz

**Comment by ArthurSens** [comment]
Probably not that relevant, but what do you think of changing the alertname to "DeadManSwitch"? I feel like that's the standard for this kind of alert, but I don't have strong opinions on keeping/changing the alertname

**Comment by brancz** [comment]
It was originally that, but we switched it to Watchdog to be gender neutral. Watchdog has equivalent etymology: https://en.wikipedia.org/wiki/Watchdog_timer

I agree it shouldn't be `example-group`. I'm happy with anything other than that really, `core-group` or literally `watchdog` works for me as well as I don't imagine anything else ever being in that group and if, then we can still change it.

**Comment by paulfantom** [comment]
We shouldn't have this alert in this place at all. This file is only used to demonstrate an example from https://github.com/prometheus-operator/kube-prometheus/blob/44008b2682546fa738af5967ddfad86cd69b3e37/docs/developing-prometheus-rules-and-grafana-dashboards.md#pre-rendered-rules.

The Watchdog alert we are shipping is put in `general.rules` group as seen in https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kube-prometheus-prometheusRule.yaml#L14-L35


My proposal is to reinforce the fact that a file is only an example and change content to sth like:
```
groups:
- name: example-group
  rules:
  - alert: ExampleAlert
    expr: example_sli < 99.999
    labels:
      severity: "critical"
```

**Comment by lilic** [comment]
> My proposal is to reinforce the fact that a file is only an example and change content to sth like:

That sounds good to me as well! I would say we just use vector here so it does work out of the box:
```
groups:
- name: example-group
  rules:
  - alert: ExampleAlert
    expr: vector(1)
    labels:
      severity: "warning"
```
