### ISSUE TITLE
Unable to scrape metrics for my service using kube-prometheus-stack helm installation

### ISSUE THREAD

**Issue by dcs3spp** [prometheus-operator/kube-prometheus#1069]
I have installed kube-prometheus-stack as a dependency in my helm chart on a local docker for Mac Kubernetes cluster v1.19.7. 

```
dependencies:                  
- name: kube-prometheus-stack  
  version: "14.4.0"            
  repository: "https://prometheus-community.github.io/helm-charts"
```

I can view the default prometheus targets provided by the kube-prometheus-stack.

I have a python flask service that provides metrics which I can view successfully in the kubernetes cluster using ```kubectl port forward```.

However, I am unable to get these metrics displayed on the prometheus targets web interface. 

The [kube-prometheus-stack](https://hub.kubeapps.com/charts/prometheus-community/kube-prometheus-stack#!) documentation states that Prometheus.io/scrape does not support annotation-based discovery of services. Instead the the reader is referred to the concept of ```ServiceMonitors``` and ```PodMonitors```.

So, I have configured my service as follows:

```yaml
---
kind:                       Service
apiVersion:                 v1  
metadata:
  name:                     flask-api-service                    
  labels:
    app:                    flask-api-service
spec:
  ports:
    - protocol:             TCP 
      port:                 4444
      targetPort:           4444
      name:                 web 
  selector:
    app:                    flask-api-service                    
    tier:                   backend 
  type:                     ClusterIP
---
apiVersion:                 monitoring.coreos.com/v1
kind:                       ServiceMonitor
metadata:
  name:                     flask-api-service
spec:
  selector:
    matchLabels:
      app:                  flask-api-service
  endpoints:
  - port:                   web 
```

Subsequently, I have setup a port forward to view the metrics:

```bash
Kubectl port-forward prometheus-flaskapi-kube-prometheus-s-prometheus-0 9090
```

Then visited prometheus web page at ```http://localhost:9090```

When I select the Status->Targets menu option, my flask-api-service is not displayed.

I know that the service is up and running and I have checked that I can view the metrics for a pod for my flask-api-service using ```kubectl port-forward <pod name> 4444```.

Looking at a similar [issue](https://stackoverflow.com/a/65648944) it looks as though there is a  configuration value ```serviceMonitorSelectorNilUsesHelmValues``` that defaults to true. Setting this to false makes the operator look outside it’s release labels in helm?? 

I tried adding this to the ```values.yml``` of my helm chart in addition to the ```extraScrapeConfigs``` configuration value. However, the *flask-api-service* still does not appear as an additional target on the prometheus web page when clicking the Status->Targets menu option.

```yaml
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  extraScrapeConfigs: |
    - job_name: 'flaskapi'
    static_configs:
      - targets: ['flask-api-service:4444']
```

How do I get my *flask-api-service* recognised on the prometheus targets page at ```http://localhost:9090```?

**Comment by dcs3spp** [comment]
Solved, I needed to match to release label in the service monitor:

```yaml
---
kind:                       Service
apiVersion:                 v1 
metadata:
  name:                     flask-api-service                
  labels:
    app:                    flask-api-service
spec:
  ports:
    - protocol:             TCP
      port:                 4444
      targetPort:           4444
      name:                 web
  selector:
    app:                    flask-api-service                
    tier:                   backend 
  type:                     ClusterIP
---
apiVersion:                 monitoring.coreos.com/v1
kind:                       ServiceMonitor
metadata:
  name:                     flask-api-service
  labels:
    release:                flaskapi
spec:
  selector:
    matchLabels:
      app:                  flask-api-service
  endpoints:
  - port:                   web
```
