### ISSUE TITLE
Shows apiserver client certificate expiring, kube controller-manager and scheduler down on fresh 1.20 cluster

### ISSUE THREAD

**Issue by xpepermint** [prometheus-operator/kube-prometheus#1089]
**What happened?**

Originally posted at https://github.com/kubernetes/kops/issues/11211

The Prometheus dashboard shows `5` alerts firing:

```yaml
name: Watchdog
expr: vector(1)
labels:
  severity: none
annotations:
  message: This is an alert meant to ensure that the entire alerting pipeline is functional.
  This alert is always firing, therefore it should always be firing in Alertmanager
  and always fire against a receiver. There are integrations with various notification
  mechanisms that send a notification when this alert is not firing. For example the
  "DeadMansSnitch" integration in PagerDuty.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/watchdog
```

```yaml
name: KubeClientCertificateExpiration
expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and on(job) histogram_quantile(0.01, sum by(job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 604800
labels:
  severity: warning
annotations:
  description: A client certificate used to authenticate to the apiserver is expiring in less than 7.0 days.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/kubeclientcertificateexpiration
  summary: Client certificate is about to expire.
```

```yaml
name: KubeClientCertificateExpiration
expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and on(job) histogram_quantile(0.01, sum by(job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 86400
labels:
  severity: critical
annotations:
  description: A client certificate used to authenticate to the apiserver is expiring in less than 24.0 hours.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/kubeclientcertificateexpiration
  summary: Client certificate is about to expire.
```

```yaml
name: KubeControllerManagerDown
expr: absent(up{job="kube-controller-manager"} == 1)
for: 15m
labels:
  severity: critical
annotations:
  description: KubeControllerManager has disappeared from Prometheus target discovery.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/kubecontrollermanagerdown
  summary: Target disappeared from Prometheus target discovery.
```

```yaml
name: KubeSchedulerDown
expr: absent(up{job="kube-scheduler"} == 1)
for: 15m
labels:
  severity: critical
annotations:
  description: KubeScheduler has disappeared from Prometheus target discovery.
  runbook_url: https://github.com/prometheus-operator/kube-prometheus/wiki/kubeschedulerdown
  summary: Target disappeared from Prometheus target discovery.
```

**Did you expect to see some different?**

The Prometheus dashboard should not have `pending` or `firing` alerts only `inactive`. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a fresh AWS cluster using `kops`.

```sh
# Create cluster.
$ kops create cluster \
    --node-count 2 \
    --master-count 1 \
    --zones eu-central-1a \
    --master-zones eu-central-1a \
    --networking calico \
    ${NAME}
$ kops update cluster --name XXX --yes --admin
# Install kube-prometheus.
$ git clone https://github.com/prometheus-operator/kube-prometheus.git
$ cd kube-prometheus
$ kubectl create -f manifests/setup
$ kubectl create -f manifests/
$ kubectl --namespace monitoring port-forward svc/prometheus-k8s 9090
=> navigate to `http://localhost:9090/alerts`
```

**Environment**

kops: 1.20
k8s: 1.20
provider: AWS

* Prometheus Operator version:

`quay.io/prometheus-operator/prometheus-operator:v0.46.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

See above instructions.

* Manifests:

Using master branch manifests. See above instructions.

* Prometheus Operator Logs:

-

* Prometheus Logs:

-

**Anything else we need to know?**:

-
