### ISSUE TITLE
Internal registry mixin not working

### ISSUE THREAD

**Issue by nlarzon** [prometheus-operator/kube-prometheus#1106]
**What happened?**

**Did you expect to see some different?**
Using the example https://github.com/prometheus-operator/kube-prometheus/blob/main/examples/internal-registry.jsonnet

yields no change in image repository in the generated files.

**How to reproduce it (as minimally and precisely as possible)**:
Run the internal-registry example
https://github.com/prometheus-operator/kube-prometheus/blob/main/examples/internal-registry.jsonnet

**Environment**
 "https://github.com/prometheus-operator/kube-prometheus.git"
SHA: 9d69c4c318cebecf982db3a77c172c251f5c2172

* Manifests:
```yaml
spec:
  image: quay.io/prometheus/alertmanager:v0.21.0
  nodeSelector:
    kubernetes.io/os: linux
```

should yield:

```yaml
spec:
  image: internal-registry.com/organization:v0.21.0
  nodeSelector:
    kubernetes.io/os: linux
```

**Anything else we need to know?**:
