### ISSUE TITLE
List available bytes for PVCs?

### ISSUE THREAD

**Issue by dev-samples** [prometheus-operator/kube-prometheus#1134]
Using: 

k8s 1.15 in azure/aks
kube-prometheus-stack-9.4.10

I am trying to get Prometheus to list _available capacity_ for a list of PVCs I have created for my k8s cluster in aks/azure.

I can curl a running prometheus and list my PVCs in a cluster with:

```
    $ curl http://127.0.0.1:9090/api/v1/label/persistentvolumeclaim/values | jq
        {
          "status": "success",
          "data": [
            ...,
            "my-pvc",
            ...
          ]
        }
```

Which has the below PersistentVolumeClaim:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  finalizers:
  - kubernetes.io/pvc-protection
  name: my-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  storageClassName: managed-premium
  volumeMode: Filesystem
  volumeName: pvc-g8hhd2e1-f11f-4bfc-a54c-e1b3f0d64c70
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 512Gi
  phase: Bound
...
```

In the graphql web editor (http://127.0.0.1:9090/graph) I can query its _capacity_ with (using the above volumeName for **my-pvc**):

    kube_persistentvolume_capacity_bytes{persistentvolume="pvc-g8hhd2e1-f11f-4bfc-a54c-e1b3f0d64c70"}

which gives: `549755813888`

But more interestingly how do I list the _available capacity_ for that volume?

I found a similar post on the cadvisor project:

https://github.com/google/cadvisor/issues/1702#issuecomment-343941712

mentioning this metric: **kubelet_volume_stats_available_bytes** but that is not available.

Any suggestions?
