### ISSUE TITLE
matches for kind "MasterConfiguration" in version "kubeadm.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by DiazRock** [prometheus-operator/kube-prometheus#1194]
**What happened?**
I wanted to configure my kubeadm-like cluster to get monitored by prometheus-operator. I started using the following file:

```yaml
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 192.168.1.173 (I changed the IP from here)
  bindPort: 6443
authorizationModes:
- Node
- RBAC
certificatesDir: /etc/kubernetes/pki
cloudProvider:
etcd:
  dataDir: /var/lib/etcd
  endpoints: null
imageRepository: gcr.io/google_containers
kubernetesVersion: v1.8.3
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
nodeName: your-dev
tokenTTL: 24h0m0s
controllerManagerExtraArgs:
  address: 0.0.0.0
schedulerExtraArgs:
  address: 0.0.0.0
```

And I got no 
`matches for kind "MasterConfiguration" in version "kubeadm.k8s.io/v1alpha1"`

**Did you expect to see some different?**
I expected a success conf applying this manifest using kubectl.

**How to reproduce it (as minimally and precisely as possible)**:
Just run `sudo kubectl -f manifestMasterConf.yml`

**Environment**

`uname -a ` : 
```bash
Linux ip-172-30-0-94 5.4.0-1048-aws #50~18.04.1-Ubuntu SMP Tue May 4 17:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

`kubectl version --short`: 
```bash
v1.21.1
```
