### ISSUE TITLE
我重新加载了prometheus-prometheus.yaml 文件后，发现prometheus启动了但是无法发现服务 （prometheus: 0.5.0   k8s: 1.18.2）

### ISSUE THREAD

**Issue by zhangshangbj** [prometheus-operator/kube-prometheus#1199]
这是我的配置
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-storage
        resources:
          requests:
            storage: 150Gi
  retention: 180d
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  image: 10.111.9.72/prometheus/prometheus:v2.15.2.1
  nodeSelector:
    #kubernetes.io/os: linux
    decided: system
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 1
  resources:
    requests:
      memory: 1024Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  version: v2.15.2
  tolerations:
  - key: "decided"
    operator: "Equal"
    value: "system"
    effect: "PreferNoSchedule"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-local-pv-0
  labels:
    app: prometheus
spec:
  capacity:
    storage: 150Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/prometheus/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - f-ppp72.flycua.com
```
应用启动后，prometheus页面，service-discovery 为空；Alerts页面，5个Firing服务，剩下的全都是Inactive服务。

我应该如何排查问题，感觉像是prometheus发现不了服务，又感觉是kube-state-metrics获取不了数据。。。。。。。

好头痛啊。。。。

这个prometheus容器内的配置
```
 cat  /etc/prometheus/config_out/prometheus.env.yaml 
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  external_labels:
    prometheus: monitoring/k8s
    prometheus_replica: prometheus-k8s-0
rule_files:
- /etc/prometheus/rules/prometheus-k8s-rulefiles-0/*.yaml
scrape_configs: []
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
  alertmanagers:
  - path_prefix: /
    scheme: http
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - monitoring
    relabel_configs:
    - action: keep
      source_labels:
      - __meta_kubernetes_service_name
      regex: alertmanager-main
    - action: keep
      source_labels:
      - __meta_kubernetes_endpoint_port_name
      regex: web
```

我非常想知道问题出在哪儿了
