### ISSUE TITLE
Incomplete/no data during Cluster Scaling

### ISSUE THREAD

**Issue by Renader** [prometheus-operator/kube-prometheus#120]
Hi, 

I'm using your example (more or less) successfully on GKE. Yet I have the following problem:

My workload is highly elastic. Therefore the cluster is continuously increasing/decreasing the node pool. I have a (multi zone) region cluster - so its not a single master zone cluster. Anytime the cluster scales there is no data collected from my Cluster. Application based metrics on the other hand work fine.

I think the only customization that I did was to disable all the `prometheus-adapter-*.yaml` since it is running on GKE and I found an Issue that here that suggested that.

**For reproduction:** 
1. I created a cluster on GKE, enabled autoscaling and deployed something - this is where the data in the screenshots "starts". 
1. Then after a short while I scaled the deployment manually to more instances
1. Autoscaling kicks in, leads to the gap in collected data.
1. After a short while I scale back to 1 
1. Autoscaling kicks in again, leads to the second gap in data

![image](https://user-images.githubusercontent.com/16294855/59347844-ef4ad800-8d15-11e9-959c-29413b05e603.png)

**A metric that I collect from my application is fine and without gaps:**
![image](https://user-images.githubusercontent.com/16294855/59347876-038ed500-8d16-11e9-8b7f-41fd2867e8e2.png)

So what could this be, is it that I need to increase the replicas for some kube-system pod? I am not totally sure where the data originates from, but I already added a PDB and replica of 2 for `kube-state-metrics-deployment.yaml`

**Comment by Renader** [comment]
I tend to say yes, at the same time I am not aware of the definite origin of metric `kube-pod-info`. But the metrics in general are not affected, just multiple kube-system related metrics like the kube-pod-info.

How can this happen during a scale up, my first shot was, that the pod gets assigned to another node but the gap is a little bit too long for that and this should have been mitigated by PDB and replica 2 for  `kube-state-metrics-deployment.yaml` - if my assumption that this pod is the source of `kube-pod-info` is correct.

I think during the scaling of the node pool kubectl looses connection sometimes too, but I am not totally sure about this not beeing connected to me having a single master cluster before. If that would help narrowing it down, I could do another test.

**Comment by brancz** [comment]
`kube_pod_info` is definitely coming from kube-state-metrics. kube-state-metrics has some indirections, so to make sure we're aggregating away these indirection, do you see the expected result when querying this?

```
max(kube_pod_info) without(instance)
```

Prometheus thinks, that these are new time-series since it's a new process, however, as this data doesn't originate in kube-state-metrics, this dimension can be safely ignored.

**Comment by Renader** [comment]
I was not aware of that, interesting. But it did not resolve the issue,  

![image](https://user-images.githubusercontent.com/16294855/59420319-fbde3780-8dcc-11e9-844b-4a4eb4be775c.png)

![image](https://user-images.githubusercontent.com/16294855/59420355-0e587100-8dcd-11e9-8e8b-41169222c1db.png)


Yet it appears to me that during the node scaling the kube-state-metrics pods were killed.  They were deployed at the same time as e.g. Grafana, Prometheus, yet their age is only 5 min - matching the age of the new nodes exporter. How did that happen?
```
kubectl get pods -n  monitoring  -w
NAME                                   READY   STATUS    RESTARTS   AGE
grafana-9d97dfdc7-p52s7                1/1     Running   0          11m
kube-state-metrics-6fd7c48447-4h64h    4/4     Running   0          5m14s
kube-state-metrics-6fd7c48447-rrp66    4/4     Running   0          5m11s
node-exporter-4lksr                    2/2     Running   0          5m16s
node-exporter-95t2d                    2/2     Running   0          10m
node-exporter-cgd7w                    2/2     Running   0          11m
node-exporter-kfdsp                    2/2     Running   0          11m
node-exporter-lzdmb                    2/2     Running   0          11m
node-exporter-spmq9                    2/2     Running   0          10m
prometheus-k8s-0                       3/3     Running   1          10m
prometheus-operator-65c44fb7b7-75zbp   1/1     Running   0          11m
```


Kube-state-metrics-deployment (only replicas was adjusted)
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - args:
        - --logtostderr
....
```

PDB:
```

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics-pdb
  namespace: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kube-state-metrics

```

**Comment by Renader** [comment]
The cluster just scaled down again and kube-state-metrics pods were both re-created.

```
kubectl get pods -n  monitoring 
NAME                                   READY   STATUS    RESTARTS   AGE
grafana-9d97dfdc7-p52s7                1/1     Running   0          34m
kube-state-metrics-85557c49d9-gq529    4/4     Running   0          73s
kube-state-metrics-85557c49d9-s5dtv    4/4     Running   0          70s
node-exporter-95t2d                    2/2     Running   0          33m
node-exporter-cgd7w                    2/2     Running   0          34m
node-exporter-kfdsp                    2/2     Running   0          34m
node-exporter-lzdmb                    2/2     Running   0          34m
node-exporter-spmq9                    2/2     Running   0          33m
prometheus-k8s-0                       3/3     Running   1          33m
prometheus-operator-65c44fb7b7-75zbp   1/1     Running   0          34m
```

![image](https://user-images.githubusercontent.com/16294855/59422522-d18e7900-8dd0-11e9-9ce5-4eb9edb2fd79.png)

**Comment by brancz** [comment]
If you want this kind of high availability, you’re gonna have to also ensure the kube state metrics pods have anti affinity configured. Do you have that already?

**Comment by Renader** [comment]
I did not have it, thought the affinity would be enough. Just added it and the pods were located on different nodes (Listing 1) yet as soon as the node pool was increased, the kube-state-metrics pods were restarted again (Listing 2). The age matches again the age of the new node. Might the pods be crashing if a node is added? 


```
kubectl get pods -o wide -n monitoring 
NAME                                   READY   STATUS    RESTARTS   AGE    IP              NODE                                                NOMINATED NODE
grafana-9d97dfdc7-p52s7                1/1     Running   0          164m   10.56.2.5       gke-accointing-cluster-default-pool-24500f38-7w7z   <none>
kube-state-metrics-85d867cf6-864gk     4/4     Running   0          18s    10.56.3.8       gke-accointing-cluster-default-pool-f3f37fd0-ztpm   <none>
kube-state-metrics-85d867cf6-kgc9b     4/4     Running   0          12s    10.56.0.13      gke-accointing-cluster-default-pool-f3f37fd0-01vt   <none>
node-exporter-95t2d                    2/2     Running   0          163m   10.132.15.220   gke-accointing-cluster-default-pool-6dae3a6f-844d   <none>
node-exporter-cgd7w                    2/2     Running   0          164m   10.132.15.216   gke-accointing-cluster-default-pool-6dae3a6f-czj4   <none>
node-exporter-kfdsp                    2/2     Running   0          164m   10.132.15.217   gke-accointing-cluster-default-pool-24500f38-7w7z   <none>
node-exporter-lzdmb                    2/2     Running   0          164m   10.132.15.218   gke-accointing-cluster-default-pool-f3f37fd0-01vt   <none>
node-exporter-spmq9                    2/2     Running   0          163m   10.132.15.219   gke-accointing-cluster-default-pool-f3f37fd0-ztpm   <none>
prometheus-k8s-0                       3/3     Running   1          163m   10.56.3.4       gke-accointing-cluster-default-pool-f3f37fd0-ztpm   <none>
prometheus-operator-65c44fb7b7-75zbp   1/1     Running   0          164m   10.56.1.5       gke-accointing-cluster-default-pool-6dae3a6f-czj4   <none>

```




```
kubectl get pods -o wide -n monitoring 
NAME                                   READY   STATUS              RESTARTS   AGE    IP              NODE                                                NOMINATED NODE
grafana-9d97dfdc7-p52s7                1/1     Running             0          171m   10.56.2.5       gke-accointing-cluster-default-pool-24500f38-7w7z   <none>
kube-state-metrics-58dc8f5dd6-f6mnj    4/4     Running             0          21s    10.56.4.15      gke-accointing-cluster-default-pool-6dae3a6f-844d   <none>
kube-state-metrics-58dc8f5dd6-gtmb2    4/4     Running             0          18s    10.56.2.14      gke-accointing-cluster-default-pool-24500f38-7w7z   <none>
node-exporter-95t2d                    2/2     Running             0          171m   10.132.15.220   gke-accointing-cluster-default-pool-6dae3a6f-844d   <none>
node-exporter-cgd7w                    2/2     Running             0          171m   10.132.15.216   gke-accointing-cluster-default-pool-6dae3a6f-czj4   <none>
node-exporter-kfdsp                    2/2     Running             0          171m   10.132.15.217   gke-accointing-cluster-default-pool-24500f38-7w7z   <none>
node-exporter-lzdmb                    2/2     Running             0          171m   10.132.15.218   gke-accointing-cluster-default-pool-f3f37fd0-01vt   <none>
node-exporter-njhlk                    0/2     ContainerCreating   0          23s    10.132.15.222   gke-accointing-cluster-default-pool-24500f38-2fv8   <none>
node-exporter-spmq9                    2/2     Running             0          171m   10.132.15.219   gke-accointing-cluster-default-pool-f3f37fd0-ztpm   <none>
prometheus-k8s-0                       3/3     Running             1          171m   10.56.3.4       gke-accointing-cluster-default-pool-f3f37fd0-ztpm   <none>
prometheus-operator-65c44fb7b7-75zbp   1/1     Running             0          171m   10.56.1.5       gke-accointing-cluster-default-pool-6dae3a6f-czj4   <none>

```


Full Deployment:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - args:
        - --logtostderr
        - --secure-listen-address=:8443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - --upstream=http://127.0.0.1:8081/
        image: quay.io/coreos/kube-rbac-proxy:v0.4.1
        name: kube-rbac-proxy-main
        ports:
        - containerPort: 8443
          name: https-main
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --logtostderr
        - --secure-listen-address=:9443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - --upstream=http://127.0.0.1:8082/
        image: quay.io/coreos/kube-rbac-proxy:v0.4.1
        name: kube-rbac-proxy-self
        ports:
        - containerPort: 9443
          name: https-self
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --host=127.0.0.1
        - --port=8081
        - --telemetry-host=127.0.0.1
        - --telemetry-port=8082
        image: quay.io/coreos/kube-state-metrics:v1.5.0
        name: kube-state-metrics
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi
      - command:
        - /pod_nanny
        - --container=kube-state-metrics
        - --cpu=100m
        - --extra-cpu=2m
        - --memory=150Mi
        - --extra-memory=30Mi
        - --threshold=5
        - --deployment=kube-state-metrics
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: k8s.gcr.io/addon-resizer:1.8.4
        name: addon-resizer
        resources:
          limits:
            cpu: 50m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: kube-state-metrics
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kube-state-metrics
              topologyKey: "kubernetes.io/hostname"
```
