### ISSUE TITLE
Adding environment variables to grafana container is broken on 0.8 release

### ISSUE THREAD

**Issue by TamasNeumer** [prometheus-operator/kube-prometheus#1287]
**What happened?**

Adding environment variables to the Grafana container broke in the new v0.8 release.

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

### Install kube prometheus

```sh
jb init
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.7
```

### build.sh

```sh
#!/usr/bin/env bash

# This script uses arg $1 (name of *.jsonnet file to use) to generate the manifests/*.yaml files.

set -e
set -x
# only exit with zero if all commands of the pipeline exit successfully
set -o pipefail

# Make sure to use project tooling
PATH="$(pwd)/tmp/bin:${PATH}"

# Make sure to start with a clean 'manifests' dir
rm -rf manifests
mkdir -p manifests/setup

# Calling gojsontoyaml is optional, but we would like to generate yaml, not json
jsonnet -J vendor -m manifests "${1-example.jsonnet}" | xargs -I{} sh -c 'cat {} | gojsontoyaml > {}.yaml' -- {}

# Make sure to remove json files
find manifests -type f ! -name '*.yaml' -delete
rm -f kustomization

# Namespace is created by Terraform => We have no CRDs for Grafana => No need for the setup folder.
rm -rf manifests/setup

# Copy manifest-kustomization into the kustomization folder
cp manifests-kustomization.yaml manifests/kustomization.yaml
```

### jsonnet file

```jsonnet
local grafana = import 'grafonnet/grafana.libsonnet';

local kp =
  (import 'kube-prometheus/kube-prometheus.libsonnet') +
  {
    _config+:: {
      namespace: 'grafana',

      versions+:: {
        grafana: '7.5.3',
      },

      grafana+::{
        env+::
          // Rendering server
          [{"name": "GF_RENDERING_SERVER_URL", "value": "http://grafana-renderer:8081/render"},
          {"name": "GF_RENDERING_CALLBACK_URL", "value": "http://grafana:3000/"},
          // Plugins
          {"name": "GF_INSTALL_PLUGINS", "value": "grafana-piechart-panel"},
          ]
        ,
      },
    },
  };

// No need to generate namespace
// { ['setup/0namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.filter((function(name) name != 'serviceMonitor'), std.objectFields(kp.grafana)) }
```

I generate the manifests using `./build grafana.jsonnet`. The resulting deployment.yaml has the desired environment variables set correctly:

```yaml
...
      containers:
      - env:
        - name: GF_RENDERING_SERVER_URL
          value: http://grafana-renderer:8081/render
        - name: GF_RENDERING_CALLBACK_URL
          value: http://grafana:3000/
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
```

### Install kube prometheus

```sh
jb init
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.8
```

### Build script
Same as previously

### grafan.jsonnet

```jsonnet
local grafana = import 'grafonnet/grafana.libsonnet';

local kp =
  (import 'kube-prometheus/main.libsonnet') +
  {   
    values+:: {
      common+:: {
        namespace: "grafana",
        versions+: {
          grafana: "8.0.6",
        }
      },
      grafana+:: {
        plugins+:: ["grafana-piechart-panel"],
        env+:: [
            // Rendering server
            {"name": "GF_RENDERING_SERVER_URL", "value": "http://grafana-renderer:8081/render"},
            {"name": "GF_RENDERING_CALLBACK_URL", "value": "http://grafana:3000/"},
            {"name": "GF_AUTH_DISABLE_LOGIN_FORM", "value": "true"}
          ],
      }
    },
  };

// No need to generate namespace
// { ['setup/0namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.filter((function(name) name != 'serviceMonitor'), std.objectFields(kp.grafana)) }
```

I generate the manifests using `./build grafana.jsonnet`. The resulting deployment.yaml has the env var for the plugin but not the rest of the env vars:

```yaml
...
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
        image: grafana/grafana:8.0.6
```

Looking forward to your insights.
