### ISSUE TITLE
alertmanager-service http port name causes 404 with istio

### ISSUE THREAD

**Issue by MiddleMan5** [prometheus-operator/kube-prometheus#1290]
The port name in the `alertmanager-operated` service is `web` but is actually an http port. This causes issues when using kube-prometheus-stack in an istio service mesh. This port should be prefixed with or named **http** to properly route traffic.

When the port is named web, prometheus reports the following:
`level=error ts=2021-07-29T19:31:43.324Z caller=notifier.go:527 component=notifier alertmanager=http://10.0.116.76:9093/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"`

When the Service port is renamed from web to http, prometheus is immediately able to send alerts to alertmanager again. 

**How to reproduce it (as minimally and precisely as 

- [ ] 

- [ ] possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.13", GitCommit:"4c00c3c459261e8ff3381c1070ddf798f0131956", GitTreeState:"clean", BuildDate:"2020-12-09T11:09:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    Single cluster with istio 1.18

* Manifests:

manifests/alertmanager-service.yaml
```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```

apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: alertmanager-main
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9093
    targetPort: web
  selector:
    alertmanager: main
    app: alertmanager
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
  sessionAffinity: ClientIP
```

should be:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: alertmanager-main
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9093
    targetPort: web
  selector:
    alertmanager: main
    app: alertmanager
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
  sessionAffinity: ClientIP
```
