### ISSUE TITLE
grafana: secret missing, dashboardDatasources incorrectly generated

### ISSUE THREAD

**Issue by nickb937** [prometheus-operator/kube-prometheus#1356]
**What happened?**

Using release-0.9:

Compiled example.jsonnet, the grafana-dashboardDatasources.yaml fails to apply:

```
error validating "manifests/grafana-dashboardDatasources.yaml": error validating data: ValidationError(Secret.stringData.datasources.yaml): invalid type for io.k8s.api.core.v1.Secret.stringData: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false
```

The generated form is:

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 8.1.1
  name: grafana-datasources
  namespace: monitoring
stringData:
  datasources.yaml:
  - 123
  - 10
  - 32
  - 32
  - 32
  - 32
  - 34
  - 97
  - 112
  - 105
  - 86
```

The generated `grafana-deployment.yaml` expects a grafana-config, but one isn't generated:

```
        - mountPath: /etc/grafana
          name: grafana-config
          readOnly: false
```

```
MountVolume.SetUp failed for volume "grafana-config" : secret "grafana-config" not found
```

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

```
$ jb update
GET https://github.com/prometheus-operator/kube-prometheus/archive/9ead6ebc539e463a45d9e04a9168ff91ba4dc7c4.tar.gz 200
GET https://github.com/kubernetes/kube-state-metrics/archive/d60e6f7ba1719045edc0f60857faadeb87280421.tar.gz 200
GET https://github.com/prometheus/node_exporter/archive/832909dd257eb368cf83363ffcae3ab84cb4bcb1.tar.gz 200
GET https://github.com/prometheus/prometheus/archive/751ca03faddc9c64089c41d0da370a3a0b477742.tar.gz 200
GET https://github.com/etcd-io/etcd/archive/2fe94b19d38237e9eff025e5eeaddde371973b01.tar.gz 200
GET https://github.com/prometheus-operator/prometheus-operator/archive/83fe36566f4e0894eb5ffcd2638a0f039a17bdeb.tar.gz 200
GET https://github.com/prometheus-operator/prometheus-operator/archive/83fe36566f4e0894eb5ffcd2638a0f039a17bdeb.tar.gz 200
GET https://github.com/kubernetes-monitoring/kubernetes-mixin/archive/1163ea85e45e1f7edf6d4f83758d44c6fef1f2fa.tar.gz 200
GET https://github.com/brancz/kubernetes-grafana/archive/405638a537f707f8ccb20b253e06115d2c5b5985.tar.gz 200
GET https://github.com/kubernetes/kube-state-metrics/archive/d60e6f7ba1719045edc0f60857faadeb87280421.tar.gz 200
GET https://github.com/prometheus/alertmanager/archive/b408b522bc653d014e53035e59fa394cc1edd762.tar.gz 200
GET https://github.com/thanos-io/thanos/archive/ff363498fc95cfe17de894d7237bcf38bdd0bc36.tar.gz 200
GET https://github.com/grafana/grafonnet-lib/archive/3082bfca110166cd69533fa3c0875fdb1b68c329.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/ff22d1d6698573e7cb76228198edfa2b2f632dcc.tar.gz 200
GET https://github.com/kubernetes-monitoring/kubernetes-mixin/archive/2b27a09a667091cef74776b690ccceaf55995e29.tar.gz 200

$ ./build.sh example.jsonnet
```

**Environment**

Linux

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.49.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"archive", BuildDate:"2021-07-16T17:16:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"bd9d9ae2719e67a582f48c5dc2f81e87fe1deb8a", GitTreeState:"clean", BuildDate:"2021-08-16T22:02:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
`

* Kubernetes cluster kind:

    Azure AKS

* Manifests:

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 8.1.1
  name: grafana-datasources
  namespace: monitoring
stringData:
  datasources.yaml:
  - 123
  - 10
  - 32
  - 32
  - 32
  - 32
  - 34
  - 97
  - 112
  - 105
  - 86
  - 101
  - 114
  - 115
  - 105
  - 111
  - 110
  - 34
  - 58
  - 32
  - 49
  - 44
  - 10
  - 32
  - 32
  - 32
  - 32
  - 34
  - 100
  - 97
  - 116
  - 97
  - 115
  - 111
  - 117
  - 114
  - 99
  - 101
  - 115
  - 34
  - 58
  - 32
  - 91
  - 10
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 123
  - 10
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 34
  - 97
  - 99
  - 99
  - 101
  - 115
  - 115
  - 34
  - 58
  - 32
  - 34
  - 112
  - 114
  - 111
  - 120
  - 121
  - 34
  - 44
  - 10
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 34
  - 101
  - 100
  - 105
  - 116
  - 97
  - 98
  - 108
  - 101
  - 34
  - 58
  - 32
  - 102
  - 97
  - 108
  - 115
  - 101
  - 44
  - 10
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 34
  - 110
  - 97
  - 109
  - 101
  - 34
  - 58
  - 32
  - 34
  - 112
  - 114
  - 111
  - 109
  - 101
  - 116
  - 104
  - 101
  - 117
  - 115
  - 34
  - 44
  - 10
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 34
  - 111
  - 114
  - 103
  - 73
  - 100
  - 34
  - 58
  - 32
  - 49
  - 44
  - 10
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 34
  - 116
  - 121
  - 112
  - 101
  - 34
  - 58
  - 32
  - 34
  - 112
  - 114
  - 111
  - 109
  - 101
  - 116
  - 104
  - 101
  - 117
  - 115
  - 34
  - 44
  - 10
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 34
  - 117
  - 114
  - 108
  - 34
  - 58
  - 32
  - 34
  - 104
  - 116
  - 116
  - 112
  - 58
  - 47
  - 47
  - 112
  - 114
  - 111
  - 109
  - 101
  - 116
  - 104
  - 101
  - 117
  - 115
  - 45
  - 107
  - 56
  - 115
  - 46
  - 109
  - 111
  - 110
  - 105
  - 116
  - 111
  - 114
  - 105
  - 110
  - 103
  - 46
  - 115
  - 118
  - 99
  - 58
  - 57
  - 48
  - 57
  - 48
  - 34
  - 44
  - 10
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 34
  - 118
  - 101
  - 114
  - 115
  - 105
  - 111
  - 110
  - 34
  - 58
  - 32
  - 49
  - 10
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 32
  - 125
  - 10
  - 32
  - 32
  - 32
  - 32
  - 93
  - 10
  - 125
type: Opaque
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 8.1.1
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      annotations:
        checksum/grafana-config: d510039417af7e50e35b2016d12acfe8
        checksum/grafana-dashboardproviders: d503da475c79a8ec463d4b0414620591
        checksum/grafana-datasources: e562b7000952c537fa95a85bedb8dee0
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 8.1.1
    spec:
      containers:
      - env: []
        image: grafana/grafana:8.1.1
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
          readOnly: false
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
          readOnly: false
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/alertmanager-overview
          name: grafana-dashboard-alertmanager-overview
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/apiserver
          name: grafana-dashboard-apiserver
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/cluster-total
          name: grafana-dashboard-cluster-total
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/controller-manager
          name: grafana-dashboard-controller-manager
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-cluster
          name: grafana-dashboard-k8s-resources-cluster
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-namespace
          name: grafana-dashboard-k8s-resources-namespace
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-node
          name: grafana-dashboard-k8s-resources-node
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-pod
          name: grafana-dashboard-k8s-resources-pod
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-workload
          name: grafana-dashboard-k8s-resources-workload
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-workloads-namespace
          name: grafana-dashboard-k8s-resources-workloads-namespace
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/kubelet
          name: grafana-dashboard-kubelet
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/namespace-by-pod
          name: grafana-dashboard-namespace-by-pod
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/namespace-by-workload
          name: grafana-dashboard-namespace-by-workload
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/node-cluster-rsrc-use
          name: grafana-dashboard-node-cluster-rsrc-use
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/node-rsrc-use
          name: grafana-dashboard-node-rsrc-use
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/nodes
          name: grafana-dashboard-nodes
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/persistentvolumesusage
          name: grafana-dashboard-persistentvolumesusage
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/pod-total
          name: grafana-dashboard-pod-total
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/prometheus-remote-write
          name: grafana-dashboard-prometheus-remote-write
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/prometheus
          name: grafana-dashboard-prometheus
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/proxy
          name: grafana-dashboard-proxy
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/scheduler
          name: grafana-dashboard-scheduler
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/workload-total
          name: grafana-dashboard-workload-total
          readOnly: false
        - mountPath: /etc/grafana
          name: grafana-config
          readOnly: false
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: grafana
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - name: grafana-datasources
        secret:
          secretName: grafana-datasources
      - configMap:
          name: grafana-dashboards
        name: grafana-dashboards
      - configMap:
          name: grafana-dashboard-alertmanager-overview
        name: grafana-dashboard-alertmanager-overview
      - configMap:
          name: grafana-dashboard-apiserver
        name: grafana-dashboard-apiserver
      - configMap:
          name: grafana-dashboard-cluster-total
        name: grafana-dashboard-cluster-total
      - configMap:
          name: grafana-dashboard-controller-manager
        name: grafana-dashboard-controller-manager
      - configMap:
          name: grafana-dashboard-k8s-resources-cluster
        name: grafana-dashboard-k8s-resources-cluster
      - configMap:
          name: grafana-dashboard-k8s-resources-namespace
        name: grafana-dashboard-k8s-resources-namespace
      - configMap:
          name: grafana-dashboard-k8s-resources-node
        name: grafana-dashboard-k8s-resources-node
      - configMap:
          name: grafana-dashboard-k8s-resources-pod
        name: grafana-dashboard-k8s-resources-pod
      - configMap:
          name: grafana-dashboard-k8s-resources-workload
        name: grafana-dashboard-k8s-resources-workload
      - configMap:
          name: grafana-dashboard-k8s-resources-workloads-namespace
        name: grafana-dashboard-k8s-resources-workloads-namespace
      - configMap:
          name: grafana-dashboard-kubelet
        name: grafana-dashboard-kubelet
      - configMap:
          name: grafana-dashboard-namespace-by-pod
        name: grafana-dashboard-namespace-by-pod
      - configMap:
          name: grafana-dashboard-namespace-by-workload
        name: grafana-dashboard-namespace-by-workload
      - configMap:
          name: grafana-dashboard-node-cluster-rsrc-use
        name: grafana-dashboard-node-cluster-rsrc-use
      - configMap:
          name: grafana-dashboard-node-rsrc-use
        name: grafana-dashboard-node-rsrc-use
      - configMap:
          name: grafana-dashboard-nodes
        name: grafana-dashboard-nodes
      - configMap:
          name: grafana-dashboard-persistentvolumesusage
        name: grafana-dashboard-persistentvolumesusage
      - configMap:
          name: grafana-dashboard-pod-total
        name: grafana-dashboard-pod-total
      - configMap:
          name: grafana-dashboard-prometheus-remote-write
        name: grafana-dashboard-prometheus-remote-write
      - configMap:
          name: grafana-dashboard-prometheus
        name: grafana-dashboard-prometheus
      - configMap:
          name: grafana-dashboard-proxy
        name: grafana-dashboard-proxy
      - configMap:
          name: grafana-dashboard-scheduler
        name: grafana-dashboard-scheduler
      - configMap:
          name: grafana-dashboard-workload-total
        name: grafana-dashboard-workload-total
      - name: grafana-config
        secret:
          secretName: grafana-config

```
