### ISSUE TITLE
alertmanager-config secret is not updated

### ISSUE THREAD

**Issue by manfred-ackermann** [prometheus-operator/kube-prometheus#1377]
**What happened?**

Deploying kube-prometheus-stack from https://prometheus-community.github.io/helm-charts with Helm updates a secret alertmanager-prometheus-{clustername}-kube-prom-alertmanager-generated but the alertmanager pod mounts secret alertmanager-prometheus-{clustername}-kube-prom-alertmanager as config-volume.

**How to reproduce it (as minimally and precisely as possible):**

Update alertmanager configuration and deploy chart kube-prometheus-stack

**Environment:**

From Chart/chart-information.yaml
```
repositoryName: prometheus-community
repositoryAddress: https://prometheus-community.github.io/helm-charts
chartName: kube-prometheus-stack
gitHub: https://github.com/prometheus-operator/kube-prometheus
artifactHub: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
chartVersion: 16.15.0
deploymentName: prometheus
crdVersion: v0.47.0
```
Kubernetes version information: v1.19.11
Kubernetes cluster kind: AKS

**Anything else we need to know?:**

Deploytask:
```
    - task: HelmDeploy@0
      displayName: Deploy Prometheus-stack into ${{ parameters.namespace }}
      inputs:
        connectionType: $(connectionType)
        kubernetesServiceEndpoint: AKS-Connector-${{ parameters.clustername }}-${{ parameters.clusterstage }}-clusteradmin
        install: true
        chartType: Name
        chartName: $(REPOSITORYNAME)/$(CHARTNAME)
        releaseName: $(DEPLOYMENTNAME)-${{ parameters.clustername }}
        command: upgrade
        arguments: --history-max 1 -f ./Chart/values.yaml -f ./Chart/values-${{ parameters.clusterstage }}.yaml -n ${{ parameters.namespace }} --version $(CHARTVERSION)

```

Happend when OpsGenie integration was added to the existing Slack integration.
