### ISSUE TITLE
servicemonitor not being discovered

### ISSUE THREAD

**Issue by mohammadasim** [prometheus-operator/kube-prometheus#1392]
**What happened?**
I am using the bitnami/ingress-controller helm chart and have enabled metrics and servicemonitor in the chart configuration. The deployment creates a servicemonitor in the monitoring namespace. This servicemonitor monitors a metrics service. When I install the prometheus-operator helm chart, I don't see the servicemonitor in the target list in prometheus.  In the prometheus config I have the following values for servicemonitor selection.
`serviceMonitorSelector: {}`
    `## Example which selects ServiceMonitors with label "prometheus" set to "somelabel"`
    `# serviceMonitorSelector:`
   ` #   matchLabels:`
    `#     prometheus: somelabel`

   ` ## Namespaces to be selected for ServiceMonitor discovery.`
    `##`
    `serviceMonitorNamespaceSelector: {}`

**Did you expect to see some different?**
I expected the servicemonitor for the ingress controller to be discovered and being available in the targets in prometheus wbe ui.
**How to reproduce it (as minimally and precisely as possible)**:
install prometheus operator using helm chart `kube-prometheus-stack-18.0.12`
install ingress controller using helm chart `bitnami/nginx-ingress-controller-7.6.4` enabling metrics and service monitor.
**Environment**

* Prometheus Operator version:
`cart_version: kube-prometheus-stack-18.0.12	 app_version: 0.50.0`
    `Insert image and tag: quay.io/prometheus-operator/prometheus-operator:v0.50.0`
    

* Kubernetes version information:

    `Client Version: v1.22.1
      Server Version: v1.21.4`
    

* Kubernetes cluster kind:

    `kops`

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-ingress-controller
    meta.helm.sh/release-namespace: config
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: nginx-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-7.6.5
  name: nginx-ingress-controller
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - config
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: nginx-ingress-controller
      app.kubernetes.io/name: nginx-ingress-controller
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-ingress-controller
    meta.helm.sh/release-namespace: config
    prometheus.io/port: "9913"
    prometheus.io/scrape: "true"
  creationTimestamp: "2021-09-23T13:42:20Z"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: nginx-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-7.6.4
  name: nginx-ingress-controller-metrics
  namespace: config
spec:
  clusterIP: <removed>
  clusterIPs:
  - <removed>
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9913
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-ingress-controller
    app.kubernetes.io/name: nginx-ingress-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

* Prometheus Operator Logs:

```
level=info ts=2021-09-23T15:14:50.863173745Z caller=main.go:261 msg="Starting Prometheus Operator" version="(version=0.50.0, branch=master, revision=83fe36566)"
level=info ts=2021-09-23T15:14:50.863264876Z caller=main.go:262 build_context="(go=go1.16, user=paulfantom, date=20210817-15:18:20)"
level=info ts=2021-09-23T15:14:50.887721878Z caller=main.go:114 msg="Starting insecure server on [::]:8080"
level=info ts=2021-09-23T15:14:50.897451856Z caller=operator.go:449 component=alertmanageroperator msg="connection established" cluster-version=v1.21.4
level=info ts=2021-09-23T15:14:50.897503886Z caller=operator.go:458 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2021-09-23T15:14:50.897674479Z caller=operator.go:309 component=thanosoperator msg="connection established" cluster-version=v1.21.4
level=info ts=2021-09-23T15:14:50.897697339Z caller=operator.go:318 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2021-09-23T15:14:50.89780613Z caller=operator.go:421 component=prometheusoperator msg="connection established" cluster-version=v1.21.4
level=info ts=2021-09-23T15:14:50.897827911Z caller=operator.go:430 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2021-09-23T15:14:51.413885907Z caller=operator.go:261 component=thanosoperator msg="successfully synced all caches"
level=info ts=2021-09-23T15:14:51.804373722Z caller=operator.go:281 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2021-09-23T15:14:51.804785098Z caller=operator.go:742 component=alertmanageroperator key=monitoring/kube-alertmanager msg="sync alertmanager"
level=info ts=2021-09-23T15:14:51.815025923Z caller=operator.go:351 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2021-09-23T15:14:51.815443238Z caller=operator.go:1221 component=prometheusoperator key=monitoring/kube-prometheus msg="sync prometheus"
level=info ts=2021-09-23T15:14:51.849744239Z caller=operator.go:742 component=alertmanageroperator key=monitoring/kube-alertmanager msg="sync alertmanager"
level=info ts=2021-09-23T15:14:52.478737231Z caller=operator.go:1221 component=prometheusoperator key=monitoring/kube-prometheus msg="sync prometheus"
level=info ts=2021-09-23T15:40:33.37613878Z caller=operator.go:1221 component=prometheusoperator key=monitoring/kube-prometheus msg="sync prometheus"
```

* Prometheus Logs:

```
level=info ts=2021-09-23T14:55:02.934Z caller=main.go:443 msg="Starting Prometheus" version="(version=2.28.1, branch=HEAD, revision=b0944590a1c9a6b35dc5a696869f75f422b107a1)"
level=info ts=2021-09-23T14:55:02.936Z caller=main.go:448 build_context="(go=go1.16.5, user=root@2915dd495090, date=20210701-15:20:10)"
level=info ts=2021-09-23T14:55:02.936Z caller=main.go:449 host_details="(Linux 5.8.0-1041-aws #43~20.04.1-Ubuntu SMP Thu Jul 15 11:07:29 UTC 2021 x86_64 prometheus-monitoring-kube-prometheus-0 (none))"
level=info ts=2021-09-23T14:55:02.936Z caller=main.go:450 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-09-23T14:55:02.936Z caller=main.go:451 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-09-23T14:55:02.944Z caller=web.go:541 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2021-09-23T14:55:02.946Z caller=main.go:824 msg="Starting TSDB ..."
level=info ts=2021-09-23T14:55:02.948Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632376800028 maxt=1632384000000 ulid=01FG8Y441JBESCJ7729PVBTT63
level=info ts=2021-09-23T14:55:02.949Z caller=tls_config.go:227 component=web msg="TLS is disabled." http2=false
level=info ts=2021-09-23T14:55:02.949Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632384000021 maxt=1632391200000 ulid=01FG94ZV9JBMX57K4ZW9N9K6Q4
level=info ts=2021-09-23T14:55:02.950Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632318048484 maxt=1632376800000 ulid=01FG950KM6AGCTSXN282WJV2BX
level=info ts=2021-09-23T14:55:02.950Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1632391200023 maxt=1632398400000 ulid=01FG9BVJJ576T0C24FPVVKJZQN
level=info ts=2021-09-23T14:55:03.060Z caller=head.go:780 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2021-09-23T14:55:03.699Z caller=head.go:794 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=638.437133ms
level=info ts=2021-09-23T14:55:03.699Z caller=head.go:800 component=tsdb msg="Replaying WAL, this may take a while"
level=info ts=2021-09-23T14:55:05.292Z caller=head.go:826 component=tsdb msg="WAL checkpoint loaded"
level=info ts=2021-09-23T14:55:09.433Z caller=head.go:854 component=tsdb msg="WAL segment loaded" segment=23 maxSegment=31
level=info ts=2021-09-23T14:55:11.651Z caller=head.go:854 component=tsdb msg="WAL segment loaded" segment=24 maxSegment=31
level=info ts=2021-09-23T14:55:15.553Z caller=head.go:854 component=tsdb msg="WAL segment loaded" segment=25 maxSegment=31
level=info ts=2021-09-23T14:55:15.843Z caller=head.go:854 component=tsdb msg="WAL segment loaded" segment=26 maxSegment=31
level=info ts=2021-09-23T14:55:17.381Z caller=head.go:854 component=tsdb msg="WAL segment loaded" segment=27 maxSegment=31
level=info ts=2021-09-23T14:55:18.717Z caller=head.go:854 component=tsdb msg="WAL segment loaded" segment=28 maxSegment=31
level=info ts=2021-09-23T14:55:19.344Z caller=head.go:854 component=tsdb msg="WAL segment loaded" segment=29 maxSegment=31
level=info ts=2021-09-23T14:55:20.448Z caller=head.go:854 component=tsdb msg="WAL segment loaded" segment=30 maxSegment=31
level=info ts=2021-09-23T14:55:20.448Z caller=head.go:854 component=tsdb msg="WAL segment loaded" segment=31 maxSegment=31
level=info ts=2021-09-23T14:55:20.448Z caller=head.go:860 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=1.593030734s wal_replay_duration=15.15593726s total_replay_duration=17.387517809s
level=info ts=2021-09-23T14:55:20.815Z caller=main.go:851 fs_type=EXT4_SUPER_MAGIC
level=info ts=2021-09-23T14:55:20.815Z caller=main.go:854 msg="TSDB started"
level=debug ts=2021-09-23T14:55:20.815Z caller=main.go:855 msg="TSDB options" MinBlockDuration=2h MaxBlockDuration=1d MaxBytes=0B NoLockfile=false RetentionDuration=10d WALSegmentSize=0B AllowOverlappingBlocks=false WALCompression=true
level=info ts=2021-09-23T14:55:20.816Z caller=main.go:981 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2021-09-23T14:55:20.821Z caller=kubernetes.go:282 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-09-23T14:55:20.822Z caller=kubernetes.go:282 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-09-23T14:55:20.823Z caller=kubernetes.go:282 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=debug ts=2021-09-23T14:55:20.824Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=kubernetes/0 subs=[serviceMonitor/monitoring/monitoring-kube-apiserver/0]
level=debug ts=2021-09-23T14:55:20.824Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=kubernetes/1 subs="[serviceMonitor/monitoring/monitoring-kube-kube-controller-manager/0 serviceMonitor/monitoring/monitoring-kube-kubelet/0 serviceMonitor/monitoring/monitoring-kube-kubelet/1 serviceMonitor/monitoring/monitoring-kube-kube-proxy/0 serviceMonitor/monitoring/monitoring-kube-kube-scheduler/0]"
ts=2021-09-23T14:55:20.824Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Endpoints (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.824Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Endpoints from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.824Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Service (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.824Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Service from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.825Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Pod (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.825Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Pod from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.826Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Endpoints (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.826Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Endpoints from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.826Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Service (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.826Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Service from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.827Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Pod (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.827Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Pod from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
level=debug ts=2021-09-23T14:55:20.824Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=kubernetes/2 subs="[serviceMonitor/monitoring/monitoring-kube-prometheus/0 serviceMonitor/monitoring/monitoring-kube-node-exporter/0 serviceMonitor/monitoring/monitoring-kube-operator/0 serviceMonitor/monitoring/monitoring-kube-alertmanager/0 serviceMonitor/monitoring/monitoring-kube-grafana/0 serviceMonitor/monitoring/monitoring-kube-kube-state-metrics/0]"
ts=2021-09-23T14:55:20.828Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Endpoints (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.828Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Endpoints from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.828Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Pod (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.828Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Pod from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
level=info ts=2021-09-23T14:55:20.828Z caller=kubernetes.go:282 component="discovery manager notify" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=debug ts=2021-09-23T14:55:20.830Z caller=manager.go:195 component="discovery manager notify" msg="Starting provider" provider=kubernetes/0 subs=[config-0]
ts=2021-09-23T14:55:20.828Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Service (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.837Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Service from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.838Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Endpoints (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.838Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Endpoints from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.838Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Service (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.838Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Service from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.838Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Starting reflector *v1.Pod (10m0s) from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.838Z caller=level.go:63 component=k8s_client_runtime level=debug func=Verbose.Infof msg="Listing and watching *v1.Pod from pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167"
ts=2021-09-23T14:55:20.840Z caller=level.go:63 component=k8s_client_runtime level=debug func=Infof msg="GET https://100.64.0.1:443/api/v1/namespaces/monitoring/endpoints?limit=500&resourceVersion=0 200 OK in 2 milliseconds"
```

**Anything else we need to know?**:

**Comment by Tilusch** [comment]
I  faced the same problem
I solved it adding the following to my ServiceMonitor:
   ` release: prometheus-community`
So for you: 
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-ingress-controller
    meta.helm.sh/release-namespace: config
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: nginx-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress-controller
    helm.sh/chart: nginx-ingress-controller-7.6.5
    release: prometheus-community
  name: nginx-ingress-controller
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - config
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: nginx-ingress-controller
      app.kubernetes.io/name: nginx-ingress-controller
```

You can easily check the values set for the serviceMonitorSelector in your Prometheus Deployment:

`kubectl get prometheuses.monitoring.coreos.com --all-namespaces -o jsonpath="{.items[*].spec.serviceMonitorSelector}"`

**Comment by mohammadasim** [comment]
> Please check the following steps:
> 
> 1. Check prometheus-operator logs to verify if there is something abnormal happening
> 2. Go to prometheus UI `/service-discovery` and check if your service is present there. If it is then ServiceMonitor was picked up, the issue is with incorrectly selected port in endpoints field
> 3. If your serviceMonitor is not registered in /service-discovery then check what is the value of `serviceMonitorSelector` field in your Prometheus object and adjusting ServiceMonitor labels accordingly. Value of `{}` selects all serviceMonitors.
> 4. If you still don't have serviceMonitor registered, check a field `serviceMonitorNamespaceSelector` to verify if prometheus should look for serviceMonitor in that namespace. Value of `{}` selects all namespaces.
> 5. If after waiting 15 minutes you still don't have your serviceMonitor registered, check RBAC. Usually you shouldn't get this far as in most cases issue is in points 2-4 :)

I made all those checks and nothing worked. At the end I ended up disabling the ServiceMonitor creation by ingress-controller and creating a serviceMonitor by adding variables to the prometheus-operator helm chart values.yml file. Once prometheus created the serviceMonitor it was registered as target and the serviceMonitor was also able to retrieve metrics from the ingress-controller.

**Comment by KaiGrassnick** [comment]
Just for reference, i faced the same issue.

Running: `kubectl get prometheuses.monitoring.coreos.com --all-namespaces -o jsonpath="{.items[*].spec.serviceMonitorSelector}"`
i found out, that the selector required (in my case) the label:  `release: monitoring`

instead of adding the label: `release: monitoring` to every custom serviceMonitor, prometheusRule etc. ( which also works )

you can update your prometheus configuration to not add the helm label selector at all by adding / changing the following in your helm chart values.yaml

```
prometheus:`
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
```

default value for these 4 entries is: `true` which adds the release: <your-release-name> as a selector as default.
