### ISSUE TITLE
kube-prometheus grafana config

### ISSUE THREAD

**Issue by Auggie321** [prometheus-operator/kube-prometheus#1485]
This repository now has the new GitHub Discussions enabled: 
https://github.com/coreos/kube-prometheus/discussions

Please create a new discussion to ask for any kind of support, which is not a Bug or Feature Request.

Thank you for being part of this community!

---

We are still happy to chat with you in the #prometheus-operator channel on Kubernetes Slack!

---------------------------------------------------------------

kube-promethes version :  release-0.9 / 2021-08-19

edit grafana-dashboardDefinitions.yaml wanna disable some grafana template disgram, some like 'Alertmanager / Overview' , 'Node Exporter /USE Method /Node' , 'Node Exporter /USE Method/ Cluster'.

e.g :  if wanna disable  alertmanager-overview display in grafana, then delete the following info, 

```
- apiVersion: v1
  data:
    alertmanager-overview.json: |-
***
kind: ConfigMap
  metadata:
    labels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 8.2.2
    name: grafana-dashboard-alertmanager-overview
    namespace: monitoring
```
after deleting, then execute as following:
kubectl apply -f grafana-dashboardDefinitions.yaml
kubectl apply -f grafana-deployment.yaml

login web grafana: the template disgram  'Alertmanager / Overview' still there.

try the other way, recovery the defaut grafana configuration same as that first git clone from kube-prometheus.
edit  grafana-deployment.yaml , 

```comment some alertmanger-overview configguration;
#- mountPath: /grafana-dashboard-definitions/0/alertmanager-overview
#          name: grafana-dashboard-alertmanager-overview
#         readOnly: false

***
#- configMap:
#         name: grafana-dashboard-alertmanager-overview
#      name: grafana-dashboard-alertmanager-overview

***

``` 
kubectl apply -f grafana-deployment.yaml
there will some error, notice grafana configmap not exist.

If want to turn off the template disgram page of unused grafana dashboard, how to configure it more elegantly to turn off.

Also from grafana web nterface deletes grafana's display page some like 'disgram  'Alertmanager / Overview' ', it will prompt: 'provisioned dashboard cannot be deleted'. causing it to be impossible to delete.

2. download postgres-exporter-grafana.json copy those , paste those in grafana-dashboardDefinitions.yaml with same other's - apiVersion: v1, noticed format issuses.
Is there have some tools, transfer download-template-grafana-disgram.json to yaml, then just copy them in grafana-dashboardDefinitions.yaml, then update once will be successful.
