### ISSUE TITLE
kube-Prometheus installation failed on K8 initiated with kubeadm, maybe due to problem in prometheus-adapter-apiService.yaml ??

### ISSUE THREAD

**Issue by hshtel** [prometheus-operator/kube-prometheus#1503]
**What did you do?**
try to deploy kube-Prometheus on K8 cluster iniated with kubeadm with "kubectl create -f manifests/ || true" with no luck. 

I am not fully aware of how APIservice object work, but is there any relation  between prometheus-adapter-apiService.yaml and metrics-apiservice.yaml which is deployed before with metric-server. or it is another problem.

**What did you expect to see?**
kube-Prometheus installed successfully.

**What did you see instead? Under which circumstances?**
the kube-state-metrics and prometheus-operator pods keep crashing as below, 
```
NAMESPACE     NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE      NOMINATED NODE   READINESS GATES
monitoring    pod/grafana-6689854d5-7npcp                 1/1     Running   0          86s     10.46.0.3    worker2   <none>           <none>
monitoring    pod/kube-state-metrics-86bc74fd4c-j7c7h     4/4     Error     2          86s     10.40.0.2    master    <none>           <none>
monitoring    pod/node-exporter-6b6d9                     2/2     Running   0          86s     172.1.1.11   worker2   <none>           <none>
monitoring    pod/node-exporter-lfsw8                     2/2     Running   0          86s     172.1.1.9    master    <none>           <none>
monitoring    pod/node-exporter-zzcth                     2/2     Running   0          86s     172.1.1.10   worker1   <none>           <none>
monitoring    pod/prometheus-adapter-5d7cff4b-2gqg9       1/1     Running   0          85s     10.32.0.6    worker1   <none>           <none>
monitoring    pod/prometheus-operator-5cfb7f4c54-kfl4r    1/1     Error     2          90s     10.40.0.1    master    <none>           <none>
```

**Environment**

* Prometheus Operator version:
```
Prometheus Operator version '0.26.0'."
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubeadm.

* Manifests:

```
### prometheus-adapter-apiService.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: prometheus-adapter
    namespace: monitoring
  version: v1beta1
  versionPriority: 100
```

```
###metrics-apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100

```
* Prometheus Operator Logs:

```
root@master:~# kubectl logs pod/prometheus-operator-5cfb7f4c54-kfl4r -n monitoring
ts=2018-12-11T13:27:48.738481288Z caller=main.go:165 msg="Starting Prometheus Operator version '0.26.0'."
ts=2018-12-11T13:28:18.826524292Z caller=main.go:253 msg="Unhandled error received. Exiting..." err="communicating with server failed: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout"

```
