### ISSUE TITLE
Cannot find root_path in grafana services

### ISSUE THREAD

**Issue by JimFran** [prometheus-operator/kube-prometheus#1510]
Hello,

I am trying to add an ingress rule to access grafana using my ingress IP: https://<INGRESS_IP>/grafana

I have 2 more ingress rules under the same IP:

APP1 --> https://<INGRESS_IP>/app1
APP2 --> https://<INGRESS_IP>/app2

The issue is that when I try to get access to the URL https://<INGRESS_IP>/grafana I get an 404 error (page not found).

I am pretty sure that I need to modify the rooth path into the grafana server:

```
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

```
The thing is that I cannot see any grafana server clear on the services under monitoring namespace... I try to find "root_url"/"root_path" checking each services that I can see deployed but I did not find anything.

This is the Ingress rule I created for Grafana:

```
# https://argoproj.github.io/argo-cd/getting_started/#port-forwarding
# https://argoproj.github.io/argo-cd/operator-manual/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "3000"
spec:
  rules:
  - http:
      paths:
        - path: /grafana(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: grafana
              port:
                number: 3000

```
and these are the services under monitoring namespace for grafana and prometheus:

```
kubectl get configmap -n monitoring
NAME                                                  DATA   AGE
adapter-config                                        1      19h
blackbox-exporter-configuration                       1      19h
grafana-dashboard-alertmanager-overview               1      19h
grafana-dashboard-apiserver                           1      19h
grafana-dashboard-cluster-total                       1      19h
grafana-dashboard-controller-manager                  1      19h
grafana-dashboard-k8s-resources-cluster               1      19h
grafana-dashboard-k8s-resources-namespace             1      19h
grafana-dashboard-k8s-resources-node                  1      19h
grafana-dashboard-k8s-resources-pod                   1      19h
grafana-dashboard-k8s-resources-workload              1      19h
grafana-dashboard-k8s-resources-workloads-namespace   1      19h
grafana-dashboard-kubelet                             1      19h
grafana-dashboard-namespace-by-pod                    1      19h
grafana-dashboard-namespace-by-workload               1      19h
grafana-dashboard-node-cluster-rsrc-use               1      19h
grafana-dashboard-node-rsrc-use                       1      19h
grafana-dashboard-nodes                               1      19h
grafana-dashboard-persistentvolumesusage              1      19h
grafana-dashboard-pod-total                           1      19h
grafana-dashboard-prometheus                          1      19h
grafana-dashboard-prometheus-remote-write             1      19h
grafana-dashboard-proxy                               1      19h
grafana-dashboard-scheduler                           1      19h
grafana-dashboard-workload-total                      1      19h
grafana-dashboards                                    1      19h
kube-root-ca.crt                                      1      19h
prometheus-k8s-rulefiles-0                            7      19h

```

Any help on this?

Regards,
