### ISSUE TITLE
how to get kube-controller-manager and kube-scheduler metrics when runs it as service in host server

### ISSUE THREAD

**Issue by lw8008** [prometheus-operator/kube-prometheus#1517]
**What did you do?**
I hope to add kube-controller-manager and kube-scheduler in Prometheus-operator
I read  https://coreos.com/operators/prometheus/docs/latest/user-guides/cluster-monitoring.html
but it seems only works when we run kube-controller-manager and kube-scheduler in container/pod rather than as linux service in the master node.

**What did you expect to see?**
Could you pls guide me if there is a way to fulfill it?

* Prometheus Operator version:

v2.2.1

* Kubernetes version information:

1.11.2

**Comment by slyt** [comment]
Here's the [kubernetes PR](https://github.com/kubernetes/kubernetes/pull/85043/files) that changed the kube-controller-manager from port `10252` to `10257` and the kube-scheduler from port `10251` to `10259 `.

I'm using the [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) helm chart and had to add the following to [values.yaml](https://github.com/prometheus-community/helm-charts/blob/2c3113586607a53252fdb3d2583bb3e44e107121/charts/kube-prometheus-stack/values.yaml#L1184-L1270):
```
kubeControllerManager:
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: 'true'
    insecureSkipVerify: 'true'
```

For some reason my `kube-scheduler` is working on port `10251`. Maybe later I will have to also add the following to `values.yaml` as well:
```
kubeScheduler:
  service:
    port: 10259
    targetPort: 10259
  serviceMonitor:
    https: 'true'
    insecureSkipVerify: 'true'
```
