### ISSUE TITLE
MalformedYAMLError when kustomization is built using v4.5.3

### ISSUE THREAD

**Issue by masih** [prometheus-operator/kube-prometheus#1708]
**What happened?**

Building the repo with kustomize v4.5.3 fails with `MalformedYAMLError`. Also tried with the latest releases `kustomize`; same issue.

**Did you expect to see something different?**
Yes. YAML generated by `kustomize`

**How to reproduce it (as minimally and precisely as possible)**:

Create `kustomization.yaml` with the following content:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/prometheus-operator/kube-prometheus.git?ref=v0.9.0
```

Build:

```sh
$ kustomize build .
Error: accumulating resources: accumulating resources from 'https://github.com/prometheus-operator/kube-prometheus.git?ref=v0.9.0': MalformedYAMLError: yaml: line 25: mapping values are not allowed in this context in File: https://github.com/prometheus-operator/kube-prometheus.git?ref=v0.9.0

```

**Environment**
N/A

* Prometheus Operator version:
N/A

* Kubernetes version information:
N/A

* Kubernetes cluster kind:
N/A

* Manifests:
N/A

* Prometheus Operator Logs:
N/A

* Prometheus Logs:
N/A
