### ISSUE TITLE
how config grafana.ini

### ISSUE THREAD

**Issue by X-Mars** [prometheus-operator/kube-prometheus#1731]
```
kubernetes version: 1.20.15
kube-prometheus version: 0.8.0
```

Dear all
I what change grafana database config, How can I do it?

Thank You!

**Comment by X-Mars** [comment]
```

    spec:
      containers:
      - env:
          - name: GF_SERVER_ROOT_URL
            value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
          - name: GF_SERVER_SERVE_FROM_SUB_PATH
            value: "true"
          - name: GF_DATABASE_TYPE
            value: "mysql"
          - name: GF_DATABASE_HOST
            value: "192.168.2.12"
          - name: GF_DATABASE_NAME
            value: "grafana"
          - name: GF_DATABASE_USER
            value: "root"
          - name: GF_DATABASE_PASSWORD
            value: "EEEEEEE"

        image: grafana/grafana:8.4.6
```
