### ISSUE TITLE
Using List kubernetes objects (e.g. ConfigMapList)

### ISSUE THREAD

**Issue by blaghed** [prometheus-operator/kube-prometheus#1735]
**What happened?**

Some provided resources are using *List kubernetes object kinds.
E.g.:
https://github.com/prometheus-operator/kube-prometheus/blob/release-0.10/manifests/grafana-dashboardDefinitions.yaml

**Did you expect to see some different?**

According to the documentation provided by Kubernetes (https://kubernetes.io/docs/reference/using-api/api-concepts/#collections), these should not be used at all, as they are meant to be response objects only, not request objects.

E.g.:
The following aggregate:
```yaml
apiVersion: v1
kind: ConfigMapList
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: foo
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: bar
```
Should actually be represented by its atomic ingredients:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bar
```

**How to reproduce it (as minimally and precisely as possible)**:

Try to deploy such a resource without the help of "kubectl" (kubectl is internally converting the list items into the atomic elements, likely hiding this issue from most of your tests).

E.g.: Deploy via the GUI
