### ISSUE TITLE
I have a need to monitor applications outside the cluster, how can I configure TLS  through ServiceMonitor

### ISSUE THREAD

**Issue by COCONUTYA1** [prometheus-operator/kube-prometheus#1739]
Hello everyone，I have a need to monitor applications outside the cluster, how can I configure TLS and basic auth through ServiceMonitor？

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter1
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  jobLabel: node-exporter
  endpoints:
  - port: port
    interval: 30s
  selector:
    matchLabels:
      app: node-exporter
  namespaceSelector:
    matchNames:
    - monitoring
```
