### ISSUE TITLE
Grafana ldap authentification is missing in generated manifests (v0.8.0)

### ISSUE THREAD

**Issue by leovct** [prometheus-operator/kube-prometheus#1745]
**What happened?**
I'm migrating a monitoring stack from kube-prometheus v0.6.0 to v0.8.0 (yeah it's quite old i know).

I re-used the grafana configuration we used in v0.6.0 and it looks like the ldap parameters are not added to the `grafana-config.yml` secret. The generated secret only contains the `grafana.ini` data. Here's what it looks like:
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-config
  namespace: kube-monitoring
  labels: ...
data:
  grafana.ini: randomBase64string
```

Here's an extract from my grafana configuration:
```jsonnet
{
  values+:: {
    grafana+:: {
      ldap: importstr './ldamp.toml',
      ...
    },
  },
}
```

To fix the issue, I had to override the grafana object:
```jsonnet
{
  values+:: {
    grafana+:: {
      ldap: importstr './ldamp.toml',
      ...
    },
  },
  
  // fix ldap auth
  grafana+:: {
    config+: {
      data+: {
        local ldap = importstr './ldap.toml',
        'ldap.toml': std.base64(ldap),
      },
    },
  },
}
```

**Did you expect to see some different?**
The ldap configuration should be encrypted to base64 and added to the `grafana-config.yml` secret.
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-config
  namespace: kube-monitoring
  labels: ...
data:
  grafana.ini: randomBase64string
  ldap.toml: anotherRandomBase64string
```

**Environment**

- Kube-prometheus version: release-v0.8.0 (the branch not the tag)
