### ISSUE TITLE
New grafana dashboard config map is missing in generated manifests (v0.8.0)

### ISSUE THREAD

**Issue by leovct** [prometheus-operator/kube-prometheus#1746]
**What happened?**
I'm migrating a monitoring stack from kube-prometheus v0.6.0 to v0.8.0 (yeah it's quite old i know).

Sometimes we're creating dashboards in the grafana ui and exporting the json. To make sure we don't lose the templates, we add these exported jsons in our monitoring stack project. Here's how we do:
```jsonnet
{
  values+:: {
    grafana+:: {
      folderDashboards+:: {
        RandomFolder+: {
          'xyz.json': (import './dashboards/xyz.json'),
        }
      },
      ...
    },
  },
}
```

With kube-prometheus v0.6.0, it would generate a `grafana-dashboardDefinitons.yaml` file which defines a list of config maps.
```yaml
apiVersion: v1
kind: ConfigMapList
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-xyz
      namespace: kube-monitoring
    data:
      xyz.json: |-
        { the content of dashboards/xyz.json }
```

After the kube-prometheus v0.8.0 migration, `grafana-dashboardDefinitons.yaml` only contains `null`. So I had to fix the grafana object:
```jsonnet
{
  values+:: {
    grafana+:: {
      folderDashboards+:: {
        RandomFolder+: {
          'xyz.json': (import './dashboards/xyz.json'),
        }
      },
      ...
    },
  },

  // fix new dashboard config map
  grafana+:: {
    dashboardDefinitions+: {
      apiVersion: 'v1',
      kind: 'ConfigMapList',
      items: [
        {
          apiVersion: 'v1',
          kind: 'ConfigMap',
          metadata: {
            name: 'grafana-dashboard-xyz',
            namespace: 'kube-monitoring',
          },
          data: {
            'xyz.json': importstr './dashboards/xyz.json',
          },
        },
      ],
    },
  },
}
```

**Did you expect to see some different?**
 `grafana-dashboardDefinitons.yaml` should contain the list of config maps specified in the `folderDashboards` field. It should not contain `null`.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

- Kube-prometheus version: release-v0.8.0 (the branch not the tag)
