### ISSUE TITLE
How to modify global config after kube-prometheus is deployed?

### ISSUE THREAD

**Issue by wajika** [prometheus-operator/kube-prometheus#1747]
I searched the entire manifests directory and the yaml file in it, but I couldn't find a place where I can configure or modify the global config. I only see that the rule file can be modified. Can anyone guide me on how to modify the config?

I want to increase 
```
scrape_configs:
- job_name: 'dapr'
  scrape_interval: 5s
  static_configs:
    - targets: ['dapr-sidecar-injector.dapr.svc.cluster.local:9090']
```
