### ISSUE TITLE
Expose Grafana with Ingress

### ISSUE THREAD

**Issue by raihan519** [prometheus-operator/kube-prometheus#1748]
Hi Everyone,

I've been trying to provisioned prometheus and grafana in my kubernetes cluster and i already did it using this repositry.

But also want to expose the dashboard, but only for grafana. So i installed ingress in my cluster and create ingress resource yaml file with below content.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dashboard.domain.com
    secretName: domain-com
  rules:
  - host: dashboard.domain.com
    http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
```

But i think it's didn't function as it should be, it always give me "504 Gateway Time-out" response.

Can someone give me a clue what is the problem? Or a guide how to configure ingress to expose my Grafana?

Thank you,
Raihan

**Comment by Tilusch** [comment]
You can create the ingress with the chart.
Try those values:

```
grafana:
    enabled: true    
    ingress:
        enabled: true
        annotations:                                                                                                                           
          kubernetes.io/ingress.class: nginx    
        hosts:
        - dasboard.domain.com
        tls:
         - secretName: domain.com
           hosts:
           - dashboard.domain.com
 ```

**Comment by raihan519** [comment]
Hi Tilusch,

Thank you for the information.

I'll try those values.

Thank You,
Raihan

**Comment by createchange** [comment]
I was facing this same issue. There's really no good reason for me to expose Grafana publicly, but I am just toying around, trying to gain more Kubernetes understanding.

I wasn't able to follow the suggestion above (not sure where those values would be set...), but I did find that I could modify the following file, removing pod selector whitelist for ingress: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/grafana-networkPolicy.yaml#L15-L18

After that, the file looks like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 9.0.1
  name: grafana
  namespace: monitoring
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 3000
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: kube-prometheus
  policyTypes:
  - Egress
  - Ingress
```

And my ingress began functioning.

**Comment by aleshaczech** [comment]
Alternatively network policies can be defined in the Jsonnet configuration file as suggested in https://github.com/prometheus-operator/kube-prometheus/issues/1719#issuecomment-1201654214.

**Comment by gabrielsantosblanchet** [comment]
> You can create the ingress with the chart. Try those values:
> 
> ```
> grafana:
>     enabled: true    
>     ingress:
>         enabled: true
>         annotations:                                                                                                                           
>           kubernetes.io/ingress.class: nginx    
>         hosts:
>         - dasboard.domain.com
>         tls:
>          - secretName: domain.com
>            hosts:
>            - dashboard.domain.com
> ```


where do I put these values ?

**Comment by Damowerko** [comment]
@gabrielsantosblanchet When deploying the helm chart you pass a yaml file using the `--values` argument. This allows you change default values in the chart to new ones.
### shell arg
```
helm install prometheus-community/kube-prometheus-stack \
   --create-namespace --namespace prometheus \
   --generate-name \
   --values ./values.yaml
```
### values.yaml
```
grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - dasboard.domain.com
    tls:
      - secretName: domain.com
        hosts:
          - dashboard.domain.com
```
