### ISSUE TITLE
Can't Access Prometheus,Grafana UI in NodePort way

### ISSUE THREAD

**Issue by oneslideicywater** [prometheus-operator/kube-prometheus#1763]
## version
download zip lastest of this repo: https://github.com/prometheus-operator/kube-prometheus.git

- docker: v1.21.0
- kubernetes: v1.23.0

## description

can't access pods such as `promtheus-k8s-0` in `monitoring` namespace by creating a custom pod in the same namespace, I can't either  expose those service `prometheus-k8s` in NodePort.

```bash
[root@localhost ingress]# kubectl exec -it prometheus-k8s-0 -n monitoring -- /bin/sh
/prometheus $ wget grafana:3000
Connecting to grafana:3000 (10.97.45.181:3000)
saving to 'index.html'
```
but using a custom pod `nginx` can't access grafana pods

```bash
[root@localhost ingress]# kubectl exec -it nginx -n monitoring -- /bin/bash
root@nginx:/# curl http://10.97.45.181:3000
curl: (28) Failed to connect to 10.97.45.181 port 3000: Connection timed out
```

edit the promtheus svc by expose the nodeport, but my brower can't access UI
```yaml
# ref by step 3
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.35.0
  name: prometheus-k8s-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus

```

## how to reproduce 

1. download main branch zip of this repo: https://github.com/prometheus-operator/kube-prometheus.git
2. follow the quick start but not port forward the service
3. add a promtheus svc yaml above
4. access the prometheus UI in the browser

**Comment by pschulten** [comment]
I have the same problem. I normally access prometheus with `kubectl proxy` and localhost:8001/api/v1/namespaces/monitoring/services/prometheus-k8s:9090/proxy/graph

this also doesn't work right now

**Comment by slashpai** [comment]
You probably would want to use [node-ports addon](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/addons/node-ports.libsonnet) for that. See example using minikube [here](https://github.com/prometheus-operator/kube-prometheus/blob/main/examples/minikube.jsonnet)

**Comment by bogd** [comment]
After spending way too long trying to troubleshoot a fresh installation that I was unable to access (and, of course, never thinking of network policies, because I knew that I never created any on the cluster....), I have two comments:
1) Thank you, @pschulten , for pointing me in the right direction!
2) Shouldn't such a change be CLEARLY documented somewhere??? It is not in the quickstart, and not in the "Access UIs" part of the docs.

**Comment by cateto** [comment]
@bogd 
I agree.  
I think "Access UIs"  only for checking (not production).
In my case, Really confused because Document below,
https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/node-ports.md

I made it, but I couldn't connect with `node ip:node port`, so I thought it was a problem with another network.

**Comment by pschulten** [comment]
Just for the record. I think restricting the access with NetworkPolicies is
a good idea, that I will definitely pick up when I'm growing up

**Comment by tobiasmuehl** [comment]
I faced the same issue when deploying the [grafana helm chart](https://artifacthub.io/packages/helm/grafana/grafana) even though the default networkpolicy for prometheus-k8s allows Ingress traffic that has the `app.kubernetes.io/app=grafana` label, which is present on the grafana deployment. Deleting the networkpolicy fixed this.

**Comment by kskalski** [comment]
Shouldn't default network policies at least allow health checks? I had to delete the network policies just to get the grafana and prometheus pods healthy.

**Comment by natehudson** [comment]
Just wanted to post this in case someone else was stuck on the same problem. 

If you are trying to use a NodePort service with `kube-prometheus` and have deleted all the network policies in `monitoring` (if required) and still can't get the health checks to pass, take a look at the `selector` on your custom grafana `type: NodePort` service. We were upgrading from `release-0.7` which used
```
  selector:
    app: grafana
```
and it seems `release-0.12` has changed to:
```
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
```
