### ISSUE TITLE
How to add an out-of-cluster blackbox exporter through servicemonitor?

### ISSUE THREAD

**Issue by Nctllnty** [prometheus-operator/kube-prometheus#1798]
I set up a blackbox exporter outside the cluster, and now I want to set up a Targets using servicemonitor in the cluster, what should I do?
**ServiceMonitor**
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
    blackbox.yeahmobi.com/provider: hw
    blackbox.yeahmobi.com/region: guangzhou
  name: hw-guangzhou-blackbox-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: blackbox-exporter

```
**Probe**
```
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: example.com
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: xxx.xxx.xxx.xxx:9115
  targets:
    staticConfig:
      static:
      - http://example.com
```
