### ISSUE TITLE
PodMonitor does not work

### ISSUE THREAD

**Issue by zhaofengcumt** [prometheus-operator/kube-prometheus#181]
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: prometheus-jvm
  name: prometheus-jvm
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - interval: 30s
    port: jvm
  selector:
    matchLabels:
      app-type: java
```
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jvm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: jvm
        app-type: java
    spec:
      hostname: jvm
      containers:
      - name: jvm
        imagePullPolicy: Never
        image: prod.registry.cmiot.chinamobile.com/market/jvm:v6
        command:
        - java
        - -javaagent:./jmx_prometheus_javaagent-0.12.0.jar=8089:config.yaml
        - -jar
        - data-collector-0.0.1-SNAPSHOT.jar
        ports:
        - containerPort: 8089
          name: jvm
```

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s-jvm
  name: k8s-jvm
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: tcloud.hub/prometheus/prometheus
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: jvm
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  version: v2.11.0

```

**Comment by brancz** [comment]
Please follow the issue template. Could you please share the logs of prometheus and the prometheus-operator?

**Comment by zhaofengcumt** [comment]
@brancz i did not see any error in prometheus and prometheus-operator

**Comment by brancz** [comment]
Can you share the generated Prometheus config? The one you see on `/config` in the Prometheus UI.

**Comment by zhaofengcumt** [comment]
@brancz 
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
```

**Comment by brancz** [comment]
What version of the prometheus operator are you using?

**Comment by zhaofengcumt** [comment]
@brancz v0.31.1

**Comment by brancz** [comment]
can you bump the log verbosity to `debug` and share the prometheus operator logs with us?

**Comment by zhaofengcumt** [comment]
does the --v=10 argument work in prometheus-operaror? or any thing else

**Comment by brancz** [comment]
It's `--log-level=debug`: https://github.com/coreos/prometheus-operator/blob/c13bcedd9f9b5dff9840785c3b02d9066dd6b2a8/cmd/operator/main.go#L148

**Comment by zhaofengcumt** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-adapter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: prometheus-adapter
    spec:
      containers:
      - args:
        - --cert-dir=/var/run/serving-cert
        - --config=/etc/adapter/config.yaml
        - --log-level=debug
        - --logtostderr=true
        - --metrics-relist-interval=1m
        - --prometheus-url=http://prometheus-k8s.monitoring.svc:9090/
        - --secure-port=6443
        image: tcloud.hub/prometheus/k8s-prometheus-adapter-amd64:v0.4.1
        name: prometheus-adapter
        ports:
        - containerPort: 6443
        volumeMounts:
        - mountPath: /tmp
          name: tmpfs
          readOnly: false
        - mountPath: /var/run/serving-cert
          name: volume-serving-cert
          readOnly: false
        - mountPath: /etc/adapter
          name: config
          readOnly: false
      serviceAccountName: prometheus-adapter
      volumes:
      - emptyDir: {}
        name: tmpfs
      - emptyDir: {}
        name: volume-serving-cert
      - configMap:
          name: adapter-config
        name: config
```
```
[root@wlwk8s11 manifests]# kubectl logs -f prometheus-adapter-85dff89545-967r5 -n monitoring
unknown flag: --log-level
Usage of /adapter:
unknown flag: --log-level
      --alsologtostderr                                         log to standard error as well as files
      --authentication-kubeconfig string                        kubeconfig file pointing at the 'core' kubernetes server with enough rights to create tokenaccessreviews.authentication.k8s.io.
      --authentication-skip-lookup                              If false, the authentication-kubeconfig will be used to lookup missing authentication configuration from the cluster.
      --authentication-token-webhook-cache-ttl duration         The duration to cache responses from the webhook token authenticator. (default 10s)
      --authorization-kubeconfig string                         kubeconfig file pointing at the 'core' kubernetes server with enough rights to create  subjectaccessreviews.authorization.k8s.io.
      --authorization-webhook-cache-authorized-ttl duration     The duration to cache 'authorized' responses from the webhook authorizer. (default 10s)
      --authorization-webhook-cache-unauthorized-ttl duration   The duration to cache 'unauthorized' responses from the webhook authorizer. (default 10s)
      --bind-address ip                                         The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If blank, all interfaces will be used (0.0.0.0 for all IPv4 interfaces and :: for all IPv6 interfaces). (default 0.0.0.0)
      --cert-dir string                                         The directory where the TLS certs are located. If --tls-cert-file and --tls-private-key-file are provided, this flag will be ignored. (default "apiserver.local.config/certificates")
      --client-ca-file string                                   If set, any request presenting a client certificate signed by one of the authorities in the client-ca-file is authenticated with an identity corresponding to the CommonName of the client certificate.
      --config string                                           Configuration file containing details of how to transform between Prometheus metrics and custom metrics API resources
      --contention-profiling                                    Enable lock contention profiling, if profiling is enabled
      --discovery-interval duration                             interval at which to refresh API discovery information
      --enable-swagger-ui                                       Enables swagger ui on the apiserver at /swagger-ui
      --http2-max-streams-per-connection int                    The limit that the server gives to clients for the maximum number of streams in an HTTP/2 connection. Zero means to use golang's default.
      --lister-kubeconfig string                                kubeconfig file pointing at the 'core' kubernetes server with enough rights to list any described objects
      --log-flush-frequency duration                            Maximum number of seconds between log flushes (default 5s)
      --log_backtrace_at traceLocation                          when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                                          If non-empty, write log files in this directory
      --logtostderr                                             log to standard error instead of files (default true)
      --metrics-max-age duration                                period for which to query the set of available metrics from Prometheus (default 20m0s)
      --metrics-relist-interval duration                        interval at which to re-list the set of all available metrics from Prometheus (default 10m0s)
      --profiling                                               Enable profiling via web interface host:port/debug/pprof/ (default true)
      --prometheus-auth-config string                           kubeconfig file used to configure auth when connecting to Prometheus.
      --prometheus-auth-incluster                               use auth details from the in-cluster kubeconfig when connecting to prometheus.
      --prometheus-ca-file string                               Optional CA file to use when connecting with Prometheus
      --prometheus-token-file string                            Optional file containing the bearer token to use when connecting with Prometheus
      --prometheus-url string                                   URL for connecting to Prometheus. (default "https://localhost")
      --requestheader-allowed-names strings                     List of client certificate common names to allow to provide usernames in headers specified by --requestheader-username-headers. If empty, any client certificate validated by the authorities in --requestheader-client-ca-file is allowed.
      --requestheader-client-ca-file string                     Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers. WARNING: generally do not depend on authorization being already done for incoming requests.
      --requestheader-extra-headers-prefix strings              List of request header prefixes to inspect. X-Remote-Extra- is suggested. (default [x-remote-extra-])
      --requestheader-group-headers strings                     List of request headers to inspect for groups. X-Remote-Group is suggested. (default [x-remote-group])
      --requestheader-username-headers strings                  List of request headers to inspect for usernames. X-Remote-User is common. (default [x-remote-user])
      --secure-port int                                         The port on which to serve HTTPS with authentication and authorization. If 0, don't serve HTTPS at all. (default 443)
      --stderrthreshold severity                                logs at or above this threshold go to stderr (default 2)
      --tls-cert-file string                                    File containing the default x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert). If HTTPS serving is enabled, and --tls-cert-file and --tls-private-key-file are not provided, a self-signed certificate and key are generated for the public address and saved to the directory specified by --cert-dir.
      --tls-cipher-suites strings                               Comma-separated list of cipher suites for the server. If omitted, the default Go cipher suites will be use.  Possible values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_3DES_EDE_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_RC4_128_SHA
      --tls-min-version string                                  Minimum TLS version supported. Possible values: VersionTLS10, VersionTLS11, VersionTLS12
      --tls-private-key-file string                             File containing the default x509 private key matching --tls-cert-file.
      --tls-sni-cert-key namedCertKey                           A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com". (default [])
  -v, --v Level                                                 log level for V logs
      --vmodule moduleSpec                                      comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by zhaofengcumt** [comment]
```
level=debug ts=2019-08-10T09:56:50.153216868Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:56:50.167048849Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:56:50.180393511Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=debug ts=2019-08-10T09:56:57.250305121Z caller=operator.go:412 component=alertmanageroperator msg="update handler" old=40947714 cur=40947754
level=debug ts=2019-08-10T09:56:57.250554664Z caller=operator.go:1014 component=prometheusoperator msg="update handler" old=40947714 cur=40947754
level=debug ts=2019-08-10T09:56:57.250581037Z caller=operator.go:1024 component=prometheusoperator msg="StatefulSet updated"
level=info ts=2019-08-10T09:56:57.250616921Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s-jvm
level=debug ts=2019-08-10T09:56:57.250629045Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:56:57.250653751Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:56:57.254969977Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:56:57.267442205Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=debug ts=2019-08-10T09:57:14.974999308Z caller=operator.go:504 component=prometheusoperator msg="Prometheus updated" key=monitoring/k8s-jvm
level=info ts=2019-08-10T09:57:14.975069332Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s-jvm
level=debug ts=2019-08-10T09:57:14.975087205Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:14.975114055Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:14.987427431Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:15.002847417Z caller=operator.go:1120 component=prometheusoperator msg="updating current Prometheus statefulset"
level=debug ts=2019-08-10T09:57:15.011858111Z caller=operator.go:412 component=alertmanageroperator msg="update handler" old=40947754 cur=40947800
level=debug ts=2019-08-10T09:57:15.012283696Z caller=operator.go:1014 component=prometheusoperator msg="update handler" old=40947754 cur=40947800
level=debug ts=2019-08-10T09:57:15.012313052Z caller=operator.go:1024 component=prometheusoperator msg="StatefulSet updated"
level=info ts=2019-08-10T09:57:15.012341313Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s-jvm
level=debug ts=2019-08-10T09:57:15.012351646Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:15.012428595Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:15.016831071Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:15.037597475Z caller=operator.go:1014 component=prometheusoperator msg="update handler" old=40947800 cur=40947806
level=debug ts=2019-08-10T09:57:15.0376247Z caller=operator.go:1024 component=prometheusoperator msg="StatefulSet updated"
level=debug ts=2019-08-10T09:57:15.037727518Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=info ts=2019-08-10T09:57:15.037763524Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s-jvm
level=debug ts=2019-08-10T09:57:15.037773786Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:15.037813672Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:15.037875945Z caller=operator.go:412 component=alertmanageroperator msg="update handler" old=40947800 cur=40947806
level=debug ts=2019-08-10T09:57:15.042340191Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:15.054057426Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=debug ts=2019-08-10T09:57:16.521772749Z caller=operator.go:1014 component=prometheusoperator msg="update handler" old=40947806 cur=40947816
level=debug ts=2019-08-10T09:57:16.521831326Z caller=operator.go:1024 component=prometheusoperator msg="StatefulSet updated"
level=info ts=2019-08-10T09:57:16.521859371Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s-jvm
level=debug ts=2019-08-10T09:57:16.521870718Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:16.521866445Z caller=operator.go:412 component=alertmanageroperator msg="update handler" old=40947806 cur=40947816
level=debug ts=2019-08-10T09:57:16.521897717Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:16.528093684Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:16.539495005Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=debug ts=2019-08-10T09:57:25.764094039Z caller=operator.go:1014 component=prometheusoperator msg="update handler" old=40947816 cur=40947842
level=debug ts=2019-08-10T09:57:25.764148759Z caller=operator.go:1024 component=prometheusoperator msg="StatefulSet updated"
level=info ts=2019-08-10T09:57:25.764189122Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s-jvm
level=debug ts=2019-08-10T09:57:25.764203322Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:25.76430424Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:25.766175951Z caller=operator.go:412 component=alertmanageroperator msg="update handler" old=40947816 cur=40947842
level=debug ts=2019-08-10T09:57:25.776819109Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:25.789371691Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=debug ts=2019-08-10T09:57:30.360456273Z caller=operator.go:412 component=alertmanageroperator msg="update handler" old=40947842 cur=40947881
level=debug ts=2019-08-10T09:57:30.360513306Z caller=operator.go:1014 component=prometheusoperator msg="update handler" old=40947842 cur=40947881
level=debug ts=2019-08-10T09:57:30.360542575Z caller=operator.go:1024 component=prometheusoperator msg="StatefulSet updated"
level=info ts=2019-08-10T09:57:30.360571895Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s-jvm
level=debug ts=2019-08-10T09:57:30.360583413Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:30.360619537Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:30.365463141Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s-jvm
level=debug ts=2019-08-10T09:57:30.376287114Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=debug ts=2019-08-10T09:58:51.376525097Z caller=operator.go:714 component=prometheusoperator msg="PodMonitor delete"
level=info ts=2019-08-10T09:58:51.37659978Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=debug ts=2019-08-10T09:58:51.376614026Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:51.388065839Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules=monitoring-prometheus-k8s-rules.yaml namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:51.401138259Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:51.401191411Z caller=operator.go:1491 component=prometheusoperator msg="filtering namespaces to select ServiceMonitors from" namespaces=kube-system,monitoring,test-market-1,kube-public,test,udm,default,market,test-market-2 namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:51.40122511Z caller=operator.go:1506 component=prometheusoperator msg="selected ServiceMonitors" servicemonitors=monitoring/prometheus,monitoring/node-exporter,monitoring/kube-controller-manager,monitoring/grafana,monitoring/coredns,monitoring/kubelet,monitoring/kube-apiserver,monitoring/kube-scheduler,monitoring/kube-state-metrics,monitoring/prometheus-operator,monitoring/alertmanager namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:51.401236928Z caller=operator.go:1536 component=prometheusoperator msg="filtering namespaces to select PodMonitors from" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:51.401245524Z caller=operator.go:1549 component=prometheusoperator msg="selected PodMonitors" podmonitors= namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:51.473532313Z caller=operator.go:1453 component=prometheusoperator msg="updating Prometheus configuration secret skipped, no configuration change"
level=debug ts=2019-08-10T09:58:51.487464252Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=info ts=2019-08-10T09:58:51.487511295Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=default/k8s-jvm
level=debug ts=2019-08-10T09:58:51.487524107Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=default namespace=default prometheus=k8s-jvm
level=debug ts=2019-08-10T09:58:51.487559684Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=default prometheus=k8s-jvm
level=debug ts=2019-08-10T09:58:51.490469174Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=default prometheus=k8s-jvm
level=debug ts=2019-08-10T09:58:51.5036815Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=debug ts=2019-08-10T09:58:53.532010225Z caller=operator.go:689 component=prometheusoperator msg="PodMonitor added"
level=info ts=2019-08-10T09:58:53.53208956Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=debug ts=2019-08-10T09:58:53.532104971Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:53.540432826Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules=monitoring-prometheus-k8s-rules.yaml namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:53.547894488Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:53.547933478Z caller=operator.go:1491 component=prometheusoperator msg="filtering namespaces to select ServiceMonitors from" namespaces=default,market,test-market-2,kube-public,test,udm,kube-system,monitoring,test-market-1 namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:53.547966549Z caller=operator.go:1506 component=prometheusoperator msg="selected ServiceMonitors" servicemonitors=monitoring/coredns,monitoring/kube-state-metrics,monitoring/kube-controller-manager,monitoring/kube-scheduler,monitoring/grafana,monitoring/kube-apiserver,monitoring/prometheus,monitoring/alertmanager,monitoring/node-exporter,monitoring/prometheus-operator,monitoring/kubelet namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:53.547978035Z caller=operator.go:1536 component=prometheusoperator msg="filtering namespaces to select PodMonitors from" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:53.547986761Z caller=operator.go:1549 component=prometheusoperator msg="selected PodMonitors" podmonitors= namespace=monitoring prometheus=k8s
level=debug ts=2019-08-10T09:58:53.572475118Z caller=operator.go:1453 component=prometheusoperator msg="updating Prometheus configuration secret skipped, no configuration change"
level=debug ts=2019-08-10T09:58:53.582981218Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=info ts=2019-08-10T09:58:53.583022121Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=default/k8s-jvm
level=debug ts=2019-08-10T09:58:53.583033393Z caller=rules.go:154 component=prometheusoperator msg="selected RuleNamespaces" namespaces=default namespace=default prometheus=k8s-jvm
level=debug ts=2019-08-10T09:58:53.583061608Z caller=rules.go:196 component=prometheusoperator msg="selected Rules" rules= namespace=default prometheus=k8s-jvm
level=debug ts=2019-08-10T09:58:53.585537734Z caller=rules.go:71 component=prometheusoperator msg="no PrometheusRule changes" namespace=default prometheus=k8s-jvm
level=debug ts=2019-08-10T09:58:53.596433405Z caller=operator.go:1116 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
```

**Comment by brancz** [comment]
It seems the namespace is selected appropriately, but the PodMonitor ends up not being selected for some reason. This will need a deeper look.

**Comment by yeya24** [comment]
Any update on this issue?

**Comment by yxyx520** [comment]
Same problem, add podMonitor but not work, no changes in prometheus and not related logs on prometheus-operator.

**Comment by faximan** [comment]
I think I'm also hit by this. I am using the prometheus-operator helm chart (version 0.32.0).

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fluentd-metrics
  labels:
    prometheus: kube-prometheus
spec:
  podMetricsEndpoints:
  - targetPort: 24231
    path: /metrics
    interval: 10s
  namespaceSelector:
    matchLabels:
      namespace: kube-system
  selector:
    matchLabels:
      k8s-app: fluentd-gcp
```
```
<snip>
prometheus:
  prometheusSpec:
    # Pick up all service monitors across all namespaces.
    serviceMonitorNamespaceSelector:
      any: true
    serviceMonitorSelector:
      any: true
    # Pick up all pod monitors across all namespaces.
    podMonitorNamespaceSelector:
      any: true
    podMonitorSelector:
      any: true
<snip>
```

```
level=debug ts=2020-07-07T15:20:57.627124847Z caller=operator.go:1497 component=prometheusoperator msg="filtering namespaces to select ServiceMonitors from " namespaces=kube-node-lease,kube-public,kube-system,default namespace=default prometheus=kube-prometheus
level=debug ts=2020-07-07T15:20:57.627157281Z caller=operator.go:1512 component=prometheusoperator msg="selected ServiceMonitors" servicemonitors=default/kube-apiserver,default/kube-grafana,default/kube-kube-state-metrics,default/kube-node-exporter,default/kube-operator,default/kube-prometheus,default/kubelet,default/prometheus-relay-server namespace=default prometheus=kube-prometheus
level=debug ts=2020-07-07T15:20:57.627178351Z caller=operator.go:1542 component=prometheusoperator msg="filtering namespaces to select PodMonitors from" namespaces=default namespace=default prometheus=kube-prometheus
level=debug ts=2020-07-07T15:20:57.627194761Z caller=operator.go:1555 component=prometheusoperator msg="selected PodMonitors" podmonitors= namespace=default prometheus=kube-prometheus
```

I find it interesting that the namespace output for PodMonitor is different than ServiceMonitor, even though the namespace selectors are configured exactly the same and the selection [code](https://git.daedalus-project.io/kubernetes/prometheus-operator/-/blob/release-0.32/pkg/prometheus/operator.go) for the two are basically identical.

**Comment by brancz** [comment]
`any: true` does not work in there selectors, if you want to select any with a label selector, you need to use the all selector, which in kubernetes is the empty one: `{}`. The `any: true` one is only possible within the ServiceMonitor and PodMonitor, as those directly transfer to the Prometheus paradigm which can only list individual namspaces or watch any, not a real kubernetes labelselector to select namespaces.

**Comment by faximan** [comment]
Thanks Frederic. Turns out my problem was caused by running prometheus-operator Helm chart 6.11.0 when PodMonitor support was added in 6.12.0. And Helm ignores all unknown values (`podMonitorNamespaceSelector` and `podMonitorSelector`) *facepalm*

**Comment by jhwbarlow** [comment]
Also cannot get this to work :(

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-process-exporter
    meta.helm.sh/release-namespace: telemetry
  creationTimestamp: "2020-12-14T12:59:24Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: prometheus-process-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-process-exporter
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: prometheus-process-exporter-0.1.0
  name: prometheus-process-exporter
  namespace: telemetry
  resourceVersion: "1469976"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/telemetry/podmonitors/prometheus-process-exporter
  uid: eb1a22fa-8229-433f-8880-67e7316c3262
spec:
  namespaceSelector:
    matchNames:
    - telemetry
  podMetricsEndpoints:
  - path: /metrics
    port: "9256"
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-process-exporter
      app.kubernetes.io/name: prometheus-process-exporter
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-12-14T23:18:00Z"
  generateName: prometheus-process-exporter-
  labels:
    app.kubernetes.io/instance: prometheus-process-exporter
    app.kubernetes.io/name: prometheus-process-exporter
<snip>
```

```
level=debug ts=2020-12-14T23:56:47.107595585Z caller=operator.go:1853 component=prometheusoperator msg="selected PodMonitors" podmonitors= namespace=telemetry prometheus=prometheus-operator-prometheus
```

```yaml
  ## Prometheus-operator image
  ##
  image:
    repository: quay.io/coreos/prometheus-operator
    tag: v0.38.1

  ## Prometheus-config-reloader image to use for config and rule reloading
  ##
  prometheusConfigReloaderImage:
    repository: quay.io/coreos/prometheus-config-reloader
    tag: v0.38.1
```

**Comment by paulfantom** [comment]
@jhwbarlow what are the values of `podMonitorNamespaceSelector` and `podMonitorSelector` in your Prometheus CR?

**Comment by jhwbarlow** [comment]
@paulfantom here are the values:

```yaml
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: prometheus-operator
```

So I guess the second of these is the problem? It is only going to consider pod monitors with that label and value? I don't know where this value is coming from, as in the `vales.yaml` of the chart, it is also set to `{}`. I'll have to do some more digging. I'll edit the live resource and see if it picks up the PM.

Thanks!
