### ISSUE TITLE
how to configure ServiceMonitor scrape metrics other than "/metrics"

### ISSUE THREAD

**Issue by oneslideicywater** [prometheus-operator/kube-prometheus#1883]
I have a service serve metrics under path “/promtheus”, which not the usually used path "/metrics"

how can I configure `ServiceMonitor` Object, like this ?

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-proxy
  labels:
    team: jenkins-proxy
spec:
  selector:
    matchLabels:
      app: jenkins-proxy
  endpoints:
  - port: web
   # path: /prometheus 

```
