### ISSUE TITLE
Problem setting active targets of kubelet, prometheus server, alertmanager, kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by marcusnh** [prometheus-operator/kube-prometheus#1895]
**What happened?**
Installed the kube-prometheus stack on my system, but seemed to have problem accessing the different endpoints in the system. Not quite sure what the reason is. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/44726949/194312010-6015a40b-ff1d-4085-80c0-6b4fb475936b.png)
As you can see from the image of the prometheus service discovery it can see the differnt targets, but some are not active. 
Below is my services
![image](https://user-images.githubusercontent.com/44726949/194311895-7e538add-6600-4c5a-bc09-7b1420475e56.png)
And here are my pods running in the monitoring namespace:
![image](https://user-images.githubusercontent.com/44726949/194314027-19c282bf-cef2-4463-a889-27aa002e2adb.png)
I seem to be able to access the services from the prometheus pods, but can't scrape metrics. For instance when trying to connect to the prometheus-operated service or the prometheus-k8s service from the promtheus-k8s-0 pod i get a timeout error:
![image](https://user-images.githubusercontent.com/44726949/194318204-3368d586-1047-4142-852d-7f0d5693185c.png)
Notice that the prometheus-k8s service is of the type loadbalancer, and i had to add a new policy to make it work:
```yaml

# Allow for external access to the service
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: prometheus-allow-external
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
  ingress:
  - ports:
    - port: 9090
```

Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:
