### ISSUE TITLE
kube-state-metrics cant get node label

### ISSUE THREAD

**Issue by Ryu-Z** [prometheus-operator/kube-prometheus#1910]
#### kube-state-metrics cant get node label
when i use kube-prometheus, i cant get node label from metrics: kube_node_labels{kube_node_labels{job="kube-state-metrics"}
#### imgae
```bash
image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.6.0
```
#### args
```bash
args:
  - --host=127.0.0.1
  - --port=8081
  - --telemetry-host=127.0.0.1
  - --telemetry-port=8082
```
#### clusterRole
```yaml
...
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - nodes
  - pods
  - services
  - serviceaccounts
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs:
  - list
  - watch
...
```
#### prometheus sql
sql
```bash
kube_node_labels{job="kube-state-metrics"}
```
#### i got
```bash
...
kube_node_labels{node="ip-10-162-123-166.ap-northeast-1.compute.internal"} 1
...
```
