### ISSUE TITLE
tls certificate error

### ISSUE THREAD

**Issue by elias-p** [prometheus-operator/kube-prometheus#1990]
I have installed the certificate on node_exporer how ever I keep getting errors.

the debug logs ....

ts=2023-01-19T00:11:15.071Z caller=tls_config.go:268 level=info msg="TLS is enabled." http2=true address=[::]:9100
2023/01/19 00:15:06 http: TLS handshake error from 1.3.1.7:33798: remote error: tls: unknown certificate
 tls: unknown certificate2023/01/19 00:20:06 http: TLS handshake error from 1.3.1.7:38776: remote error: tls: unknown certificate

IP=  1.3.1.7  my local IP or node_exporter IP

my config for web.yml is
```
tls_server_config:
        cert_file: node_exporter.crt
        key_file:  node_exporter.key
       client_auth_type: RequestClientCert
basic_auth_users:
  admin: xxxxxxxxxxxx
```

* This is CA certificate not sure what is the problem. any suggestion
