### ISSUE TITLE
How to edit remote_write to use Victoriametrics?

### ISSUE THREAD

**Issue by giz33** [prometheus-operator/kube-prometheus#2012]
Hi everyone, I just installed the kube prometheus on my environment and now I have Victoria Metrics installed and want to connect my operator on it.
I tried to search for a configmap where I can edit the prometheus.yaml and put the remote_write section but I didn't find it.

I already have an installed kube-prometheus, I need to change this parameter without losing all my earlier configs.
Where I can put this parameter and how I can apply it?
I edited the manifest prometheus-prometheus.yaml putting the following lines on it:

version: v2.22.1
  remoteWrite:
  - url:  Your Metrics instance remote_write endpoint

And them I applied with kubectl apply -f prometheus-prometheus.yaml -n monitoring.

After this I check my operator(prometheus) with :
kubectl edit prometheus k8s -n monitoring

And the lines I edited was there, but when I go look inside my PODS of prometheus, there isn't any modifications on prometheus.yml at all.

So, how can I change this parameter and apply it formally without losing any of my earlier configurations like rules configured, I mean, without need to reconfigure all my prometheus?

For reference I'm trying to execute the following procedure to connect my prometheus to my VictoriaMetrics:
https://grafana.com/docs/grafana-cloud/kubernetes-monitoring/other-methods/prometheus/remote_write_operator/#step-2--modify-the-prometheus-manifest-configuration

I'm trying to use whats on the topic "Modify the Prometheus manifest configuration"
Just ignore the parts where say to use user and password because for VictoriaMetrics its not necessary.

Thank you very much.

**Comment by giz33** [comment]
I solve it editing directly the prometheus using:
kubectl edit prometheus k8s -n monitoring
I put the config remoteWrite on the workload config and save it.

But this wasn't working because my operator is not running on the environment.
After I install manually the operator using the following manifest, it works:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.49.0
  name: prometheus-operator
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: prometheus-operator
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.49.0
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.49.0
        image: quay.io/prometheus-operator/prometheus-operator:v0.49.0
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --logtostderr
        - --secure-listen-address=:8443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --upstream=http://127.0.0.1:8080/
        image: quay.io/brancz/kube-rbac-proxy:v0.11.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: prometheus-operator
      serviceAccountName: prometheus-operator
      terminationGracePeriodSeconds: 30
```

For those who pass for this problem on future.
Tks to @JoaoBraveCoding on another topic that helped me understanding the problem.
