### ISSUE TITLE
Grafana datasource wont load configmap when behind TLS and ingress

### ISSUE THREAD

**Issue by ceelias** [prometheus-operator/kube-prometheus#2033]
**What happened?**

I'm attempting to deploy Grafana with TLS enabled (`grafana.ini` updated with `protocol: https`) and ingress along with loading a Prometheus datasource. This deploys fine and works as expected. The issue is when I navigate to the data sources in the Grafana UI, I see 1 of 3 things:
1. No data source appears at all
2. The default data source appears without the configuration I need
3. The datasource I actually need is configured properly as I would expect

I am creating a separate configmap that I then attach the label `grafana_datasource=1` to. I know this works fine when I am not attempting to update the grafana.ini with ingress or TLS enabled so I'm unsure why it is failing to work now. As I mentioned, it will occasionally/randomly work when I deploy which makes the issue a bit more odd for me.

In another attempt to solve my use case, I have updated the default datasource to use the appropriate url I need using `https://`, but I would also like the ability to toggle `tlsSkipVerify` which does not appear to be a supported configuration for the default data source.

I see no errors in the logs related to these changes or anything that would indicate an issue to me. I am able to manually add the datasource through the UI and it has not issue.

I am able to confirm that my datasource configmap gets created with the correct label but I do see another configmap that appears to be created by default `v4m-grafana-datasource` that is completely empty with the correct label as well. I wonder if somehow this configmap is getting picked up first and is the one causing the issue.

**Did you expect to see some different?**

I expect Grafana to get deployed with TLS and Ingress enabled with my Prometheus datasource configured.

**How to reproduce it (as minimally and precisely as possible)**:
Updated grafana values:
```
grafana:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    tls:
    - hosts:
      - ingress-nginx.webb-m1.opsmonitor.sashq-d.openstack.sas.com
      secretName: grafana-ingress-tls-secret
    hosts:
    - ingress-nginx.webb-m1.opsmonitor.sashq-d.openstack.sas.com
    path: /grafana
  testFramework:
    enabled: false
  readinessProbe:
    httpGet:
      scheme: HTTPS
      port: 3000
  livenessProbe:
    httpGet:
      scheme: HTTPS
      port: 3000
  extraSecretMounts:
  - name: grafana-tls
    mountPath: /cert
    secretName: grafana-tls-secret
    readOnly: true
    subPath: ""
  service:
    port: 3000
    targetPort: 3000
    type: ClusterIP
    nodePort: null
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
  "grafana.ini":
    server:
      protocol: https
      cert_file: /cert/tls.crt
      cert_key: /cert/tls.key
      domain: ingress-nginx.webb-m1.opsmonitor.sashq-d.openstack.sas.com
      root_url: https://ingress-nginx.webb-m1.opsmonitor.sashq-d.openstack.sas.com/grafana
      serve_from_sub_path: true
```

Datasource configmap(`grafana-datasource-prom-https.yaml`):
```
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      isDefault: true
      jsonData:
        tlsSkipVerify: true
      editable: true
      url: https://v4m-prometheus:9090/prometheus
```

Configmap created:
```
  kubectl create cm -n monitoring grafana-datasource-prom-https --from-file monitoring/tls/grafana-datasource-prom-https.yaml
  kubectl label cm -n monitoring grafana-datasource-prom-https grafana_datasource=1
```
