### ISSUE TITLE
A CRD is missing when deploying the kube-prometheus-stack with Argo CD

### ISSUE THREAD

**Issue by lucj** [prometheus-operator/kube-prometheus#2075]
When deploying the kube-prometheus-stack with the following definition:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.9.1
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus
      parameters:
      - name: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues
        value: "false"
      - name: prometheus.prometheusSpec.serviceMonitorSelector
        value: "{}"
      - name: prometheus.prometheusSpec.serviceMonitorNamespaceSelector
        value: "{}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

I can see the following CRDs are created:
```
$ k get crds | grep coreos
prometheusrules.monitoring.coreos.com       2023-04-13T12:11:36Z
servicemonitors.monitoring.coreos.com       2023-04-13T12:11:36Z
alertmanagerconfigs.monitoring.coreos.com   2023-04-13T12:11:36Z
probes.monitoring.coreos.com                2023-04-13T12:11:36Z
podmonitors.monitoring.coreos.com           2023-04-13T12:11:36Z
alertmanagers.monitoring.coreos.com         2023-04-13T12:11:36Z
thanosrulers.monitoring.coreos.com          2023-04-13T12:11:36Z
```

but I cannot see metrics in the dashboard.
From the logs, the *prometheuses.monitoring.coreos.com* CRD is missing:
```
level=error ts=2023-04-13T12:15:16.836941424Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: Failed to watch *v1.Prometheus: failed to list *v1.Prometheus: the server could not find the requested resource (get prometheuses.monitoring.coreos.com)"
```

Any idea what could be wrong ?
