### ISSUE TITLE
Default rule to trigger on "host down"

### ISSUE THREAD

**Issue by jcpunk** [prometheus-operator/kube-prometheus#2097]
**What is missing?**
Something that builds an element like:
```yaml
      rules:
      - alert: NodeDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Node {{ $labels.instance }} is down
          description: Node {{ $labels.instance }} has been down for
          5 minutes.
```

**Why do we need it?**
This rule would help folks quickly become aware of dead instances or bare metal hosts.

**Environment**
production

* kube-prometheus version:

    `0.63.0`

**Anything else we need to know?**:
I know it goes into jsonnet somewhere...
