### ISSUE TITLE
default rule for high CPU usage

### ISSUE THREAD

**Issue by jcpunk** [prometheus-operator/kube-prometheus#2098]
**What is missing?**
Something like
```yaml
      rules:
      - alert: HighCPUUtilization
        expr: avg(node_cpu{mode="system"}) > 95
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High CPU utilization on host {{ $labels.instance 
          }}
          description: The CPU utilization on host {{
          $labels.instance }} has exceeded 95% for 5 minutes.
```

**Why do we need it?**
Alerts like this can help folks understand their sizing limits and isolate badly behaving container.

**Environment**
Production

* kube-prometheus version:

    `0.63.0`

**Anything else we need to know?**:
I'm unsure how to make such a thin in jsonnet...
