### ISSUE TITLE
Setting prometheus pod memory in values yaml

### ISSUE THREAD

**Issue by electricstrm-redgate** [prometheus-operator/kube-prometheus#2177]
I've installed kube-prometheus with a helm chart and a minor changes to the config. 

From Grafana I see that prometheus-prometheus-kube-prometheus-prometheus-0 takes 1.5 Gig although it's set to 50 mg.  I did a test to find the value to change in the values.yaml.  I found the following to be set to 50mg by default and thought it might be the values to change since i found nothing else :  

```

 # resource config for prometheusConfigReloader
 prometheusOperator:
   prometheusConfigReloader:
     resources:
       requests:
         memory: 100Mi
       limits:
         memory: 100Mi
```

When i logged on to see the data in grafana, I now had 3 of the prometheus pods with that value as a limit.  This is a problem because pod 1 is over 1G and would like to change the memory limit.
1. prometheus-prometheus-kube-prometheus-prometheus-0
2. prometheus-kube-prometheus-operator-9d6b8c497-jjxjn
3. The prometheus config reloader 

Why would all three have the same values. The other 2 seem fine and hover at 50-60 mg, while the other is much bigger.
