### ISSUE TITLE
Set secrets in alertmanager via jsonnet

### ISSUE THREAD

**Issue by roelandvanbatenburg** [prometheus-operator/kube-prometheus#2203]
**What is missing?**

I cannot set the secrets in the alertmanager config via jsonnet.
In <https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/alertmanager.libsonnet> anything but a few variables are ignored, while the alertmanager CRD does support this secrets:

```yaml
              secrets:
                description: Secrets is a list of Secrets in the same namespace as the Alertmanager object, which shall be mounted into the Alertmanager Pods. Each Secret is added to the StatefulSet definition as a volume named `secret-<secret-name>`. The Secrets are mounted into `/etc/alertmanager/secrets/<secret-name>` in the 'alertmanager' container.
                items:
                  type: string
                type: array
```

**Why do we need it?**

I am mounting the slack-api-url via the External Secrets Operator. This works fine if I manually add

```yaml
spec:
  secrets:
  - alertmanager-secrets
```

and then reference it in the alertmanager config

```yaml
            slack_configs:
              - api_url_file: /etc/alertmanager/secrets/alertmanager-secrets/slack-api
```

But this requires patching (apply does not work as there is no patchStrategy for the alertmanager CRD) the alertmanager resource, which should not be necessary.

**Environment**

GKE

* kube-prometheus version:

    `6901a5e88d29f322d8cde30ca94e273167b711b2` (0.12)
