### ISSUE TITLE
Need help how to edit config after deploy 

### ISSUE THREAD

**Issue by yahavvidaa** [prometheus-operator/kube-prometheus#2204]
Hi , 
i recently deployed the kube-prometheus v0.10 on my k8s cluster and i am wondering how can i start edit my configuration of alertmanager and promethues.
i saw a way to do it using the tool jsonnet but i dont have any expirience with this tool so i wonder what is my second option to start editing my configuration ? 
in addition i found also that command :
```
kubectl get prometheusrules -A

NAMESPACE    NAME                              AGE
monitoring   alertmanager-main-rules           5d21h
monitoring   kube-prometheus-rules             5d21h
monitoring   kube-state-metrics-rules          5d21h
monitoring   kubernetes-monitoring-rules       5d21h
monitoring   node-exporter-rules               5d21h
monitoring   prometheus-k8s-prometheus-rules   5d21h
monitoring   prometheus-operator-rules         5d21h
```
but when run - 

` kubectl edit prometheusrules alertmanager-main-rules -n monitoring
`
and try to paste this:
```
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
  #routes:
  #- match:
  #    alertname: Nodedown
  #  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://prom2teams:8089/v2/Connector1'
inhibit_rules:
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
```

i dont really saw the change on alertmanager config web page from browser 

i used this method to install - 
```
# Create the namespace and CRDs, and then wait for them to be available before creating the remaining resources
kubectl apply --server-side -f manifests/setup
until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
kubectl apply -f manifests/
```

What i am missing here please?
