### ISSUE TITLE
Issue deploying prometheus-operator .33 to k8 1.15.3

### ISSUE THREAD

**Issue by cvernooy23** [prometheus-operator/kube-prometheus#242]
**What did you do?**
ran the commands to generate the manifests and deploy kube-prometheus
```
kubectl create -f manifests/
until kubectl get customresourcedefinitions servicemonitors.monitoring.coreos.com ; do date; sleep 1; echo ""; done
until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
kubectl apply -f manifests/
```

only prometheus-adapter came up in the monitoring namespace. No other containers showed up, running or otherwise

**Did you expect to see some different?**

I expected other pods for prometheus, grafana, etc.

**Environment**

* Prometheus Operator version:

    quay.io/coreos/prometheus-operator:v0.33.0

* Kubernetes version information:

    1.15.3

* Kubernetes cluster kind:

   kubedm w/ custom ansible

* Manifests:

```
promtheus-adapter
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: prometheus-adapter
    namespace: monitoring
  version: v1beta1
  versionPriority: 100
```

* Prometheus Operator Logs:

N/A

* Prometheus Logs:
```
k logs prometheus-adapter-668748ddbd-89drr -n=monitoring
I0925 13:25:26.684280       1 adapter.go:91] successfully using in-cluster auth
I0925 13:25:27.178137       1 serving.go:273] Generated self-signed cert (/var/run/serving-cert/apiserver.crt, /var/run/serving-cert/apiserver.key)
I0925 13:25:27.731316       1 serve.go:96] Serving securely on [::]:6443
```

**Anything else we need to know?**:

I have the following in kubelet-flags.env:
```
--authentication-token-webhook=true --authorization-mode=Webhook
```
read-only-port is 0
tls ciphers allowed are limited to "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
profilling is active (API Server)
