### ISSUE TITLE
How to override startup args for prometheus server

### ISSUE THREAD

**Issue by ForcemCS** [prometheus-operator/kube-prometheus#2453]
I am deploying prometheus using kube-prometheus-satck, how do I override the value of --storage.tsdb.retention.time=10d to --storage.tsdb.retention.time=15d, I I tried the following VALUES. yaml modification, but when helm upgrade is executed, there are two configurations in the startup parameters, one for 10d and one for 15 days
```yaml
prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - prom.threshold.com
    tls:
    - hosts:
      - prom.threshold.com
      secretName: prom-threshold-com
  prometheusSpec:
    additionalArgs:
    - name: 'storage.tsdb.retention.time=15d'
    - name: 'storage.tsdb.max-block-duration=2h'
    - name: 'storage.tsdb.min-block-duration=2h'
    - name: 'web.enable-admin-api'
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: preferred
                  operator: In
                  values:
                    - prometheus
```
