### ISSUE TITLE
customizations all namespaces is broken

### ISSUE THREAD

**Issue by k8s-1** [prometheus-operator/kube-prometheus#2491]
**What happened?**

Applied customizations all namespaces in kind cluster -> https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-all-namespaces.md, got error: resource mapping not found for name: "k8s" namespace: "monitoring" from "manifests/prometheus-prometheus.yaml": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"

Next, checked prometheus UI in http://localhost:9090/targets?search=
-> No scrape pools configured

**Did you expect to see some different?**
Expected to see no error, scrape pools showing up in UI

**How to reproduce it (as minimally and precisely as possible)**:
Apply the jsonnet https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-all-namespaces.md to a clean cluster

**Environment**
kind/kubeadm

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
app.kubernetes.io/version=0.76.0

* Kubernetes version information:

    `kubectl version`
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.
```
kind delete cluster && kind create cluster --config - <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker
EOF

```

* Manifests:

```
not relevant
```

* Prometheus Operator Logs:

```
not relevant
```

* Prometheus Logs:

```
not relevant
```

**Anything else we need to know?**:
