### ISSUE TITLE
How to write prometheus configurations to set an alertmanager out of k8s?

### ISSUE THREAD

**Issue by yxyx520** [prometheus-operator/kube-prometheus#250]
**What did you do?**

**Did you expect to see some different?**
I want to add configurations below into prometheus config in k8s,because I have 4 k8s clusters and I want to send all alerts to one alertmanager, for me it's more convenient.
```yaml
alerting:
  alertmanagers:
  - static_configs:
      - targets: ["192.168.1.23:9093"]
```
But as I know I can only set alertmanager service and port inside this cluster to post alerts in "prometheus-prometheus.yaml",config as below:
```yaml
   alerting:
     alertmanagers:
     - name: alertcenter
       namespace: monitoring
       port: 9093
```
I want to know how to set a static alertmanager address in prometheus. Are there any advices?
@rphillips 
**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:
