### ISSUE TITLE
How to embed Grafana in iframe

### ISSUE THREAD

**Issue by Ashley-Tung** [prometheus-operator/kube-prometheus#2610]
Hi, I would like to embed my grafana page in an html iframe like this:
```
<iframe src="http://<public-ip>:3000"></iframe>
```

I have already set up anonymous authentication - which does work. I have tried out these values to get the iframe to embed but they do now work. I apply it via `helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -f grafana-update.yaml`
```
grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Editor
      cookie_secure: true
      cookie_samesite: none
      allow_embedding: true
    auth:
      disable_login_form: true
    panels:
      disable_sanitize_html: true
    plugins:
      enable_alpha: true
```

I start the pods with
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/kube-prometheus-stack
```

How can I allow for grafana embedding in an iframe?

**Comment by Ashley-Tung** [comment]
```
grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Editor
    auth:
      disable_login_form: true
    security:
      allow_embedding: true
      cookie_samesite: none
```
