### ISSUE TITLE
kubeadm documentation out of date

### ISSUE THREAD

**Issue by yogeek** [prometheus-operator/kube-prometheus#331]
**What happened?**

The documentation located at https://github.com/coreos/kube-prometheus/blob/master/docs/kube-prometheus-on-kubeadm.md seems out of date.

For example, the link to kubeadm config file in "Kubeadm Pre-requisites" section have to been updated and it seems that the given example refers to an old format :
```
controllerManagerExtraArgs:
  address: 0.0.0.0
schedulerExtraArgs:
  address: 0.0.0.0
```
has become :
```
controllerManager:
  extraArgs:
    address: 0.0.0.0
scheduler:
  extraArgs:
    address: 0.0.0.0
```

Moreover, it is not clear if the modification indicated for kubelet configuration (`sed -e "s/--authorization-mode=Webhook/--authentication-token-webhook=true --authorization-mode=Webhook/" -i "$KUBEADM_SYSTEMD_CONF"`) is still needed or not.

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

 kubeadm
