### ISSUE TITLE
Prometheus node anti-affinity for ARM hosts

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/kube-prometheus#528]
**What is missing?**
Node anti-affinity for prometheus pods for ARM hosts. Essentially this:
```
nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/arch
        operator: NotIn
        values:
        - arm
```

**Why do we need it?**
Prometheus performance is much worse on 32-bit systems such as ARM (not ARM64). To prevent monitoring performance degradation in multi-arch environment, but still allow scheduling when there is no other choice `preferredDuringSchedulingIgnoredDuringExecution` can be used.

**Environment**

* kube-prometheus version: all

**Anything else we need to know?**:
