### ISSUE TITLE
Add pod security policies in manifests

### ISSUE THREAD

**Issue by Exagone313** [prometheus-operator/kube-prometheus#572]
Hi,

**What is missing?**

Manifests do not contain PodSecurityPolicy objects.

**Why do we need it?**

This prevents the installation of *kube-prometheus* in clusters having the PodSecurityPolicy admission controller enabled.

**Environment**

* kube-prometheus version:

    v0.5.0

**Anything else we need to know?**:

```
$ kubectl get events -n monitoring | grep security
5m24s       Warning   FailedCreate        replicaset/grafana-5c55845445               Error creating: pods "grafana-5c55845445-" is forbidden: unable to validate against any pod security policy: []
5m24s       Warning   FailedCreate        replicaset/kube-state-metrics-957fd6c75     Error creating: pods "kube-state-metrics-957fd6c75-" is forbidden: unable to validate against any pod security policy: []
5m24s       Warning   FailedCreate        daemonset/node-exporter                     Error creating: pods "node-exporter-" is forbidden: unable to validate against any pod security policy: []
5m23s       Warning   FailedCreate        replicaset/prometheus-adapter-5949969998    Error creating: pods "prometheus-adapter-5949969998-" is forbidden: unable to validate against any pod security policy: []
32s         Warning   FailedCreate        replicaset/prometheus-operator-574fd8ccd9   Error creating: pods "prometheus-operator-574fd8ccd9-" is forbidden: unable to validate against any pod security policy: []
```

I found #167 but it seems incomplete.

**Comment by brancz** [comment]
If anyone wants to push forward on this, I think this is a great improvement!

**Comment by Exagone313** [comment]
I made a PSP and succeeded to deploy kube-prometheus, but since some deployments run as root, I made a PSP that allows that.

Thus this is subject to improvement.

Run this before deploying quick start:
```
$ kubectl apply -f psp.yml
```
```
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kube-prometheus
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
  - 'emptyDir'
  - 'secret'
  - 'downwardAPI'
  - 'configMap'
  - 'projected'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  allowedHostPaths: []
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitoring
  name: kube-prometheus-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - kube-prometheus
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: monitoring
  name: kube-prometheus-psp:sa-rb
roleRef:
  kind: Role
  name: kube-prometheus-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
```

**Comment by bygui86** [comment]
@Exagone313 I tried your PSP and it does not work for me

k8s version:   v1.17.14-gke
node-exporter version:   1.0.1

after several attempts this is a restricted PSP working:
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: node-exporter-restricted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  runtime/default
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName:  runtime/default
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - emptyDir
    - configMap
    - secret
    - hostPath
    - downwardAPI
    - projected
  hostPID: false
  hostIPC: false
  hostNetwork: false
  allowedHostPaths:
    - pathPrefix: /proc
    - pathPrefix: /sys
    - pathPrefix: /root
    - pathPrefix: /
      readOnly: true
  hostPorts:
    - min: 9100
      max: 9100
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  readOnlyRootFilesystem: true
```
