### ISSUE TITLE
HTTP status 403 Forbidden

### ISSUE THREAD

**Issue by a8j8i8t8** [prometheus-operator/kube-prometheus#629]
**What happened?**
I installed kube-prometheus from `master` as well as from release `0.6.0` on Kubernetes cluster `1.18.6` but for both I'm getting below.
![image](https://user-images.githubusercontent.com/9692020/89413101-84820a80-d728-11ea-875c-d477e41f69ae.png)

**How to reproduce it (as minimally and precisely as possible)**:
I'm using below jsonnet to install kube-prometheus.
https://gist.github.com/a8j8i8t8/b54d4e3199e76e9c14875da1a2118734
**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.40.0`
    

* Kubernetes version information:

    `1.18.6`
    

* Kubernetes cluster kind:

    Created the cluster using kops.

* Manifests:

```
https://gist.github.com/a8j8i8t8/b54d4e3199e76e9c14875da1a2118734
```
Any help would be appreciated.
Thanks.
~ Ajit

**Comment by brancz** [comment]
This suggests a permission problem. Could you check the logs of the scheduler and controller manager?

**Comment by a8j8i8t8** [comment]
@brancz Thanks for quick reply.

I was looking into prometheus logs only.
BTW I'm getting logs like below in both Scheduler and Controller manager.
```
E0805 13:36:29.356239       1 writers.go:105] apiserver was unable to write a JSON response: no kind is registered for the type v1.Status in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"
E0805 13:36:29.356275       1 status.go:71] apiserver received an error that is not an metav1.Status: &runtime.notRegisteredErr{schemeName:"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30", gvk:schema.GroupVersionKind{Group:"", Version:"", Kind:""}, target:runtime.GroupVersioner(nil), t:(*reflect.rtype)(0x1a64e80)}
```

**Comment by brancz** [comment]
Did you enable webhook authorization on the scheduler and controller manager?

**Comment by a8j8i8t8** [comment]
@brancz Do you mean below? I'm stating below in terms of Kops provisioning.
```
kubelet:
    authenticationTokenWebhook: true
    authorizationMode: Webhook
```

**Comment by brancz** [comment]
that's just the kubelet, you need the equivalent for controller-manager and scheduler

**Comment by a8j8i8t8** [comment]
@brancz Thanks for the insights. I'll try and update here.

**Comment by a8j8i8t8** [comment]
@brancz At least with kops I can't give something like below in Cluster config.
```
kubeControllerManager:
    authenticationTokenWebhook: true
    authorizationMode: Webhook
kubeScheduler:
    authenticationTokenWebhook: true
    authorizationMode: Webhook
```
Those flags are not present https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
Any inputs?

**Comment by a8j8i8t8** [comment]
Further from my message above,
I restarted my K8S cluster with following settings, but I'm still facing the same issue.
```
kubelet:
    authenticationTokenWebhook: true
    authorizationMode: Webhook
```
I also tested by assigning `cluster-admin` permissions to prometheus `serviceAccount` but same issue.

**Comment by a8j8i8t8** [comment]
I needed to start kube-controller-manager and kube-scheduler with below options
```
--authentication-kubeconfig
--authorization-kubeconfig
```

**Comment by brancz** [comment]
Ah awesome that you figured it out!

**Comment by searsaw** [comment]
> I needed to start kube-controller-manager and kube-scheduler with below options
> 
> ```
> --authentication-kubeconfig
> --authorization-kubeconfig
> ```

@a8j8i8t8 did you do this through the kops cluster spec or manually by updating the pod definition?

**Comment by a8j8i8t8** [comment]
@searsaw I did that by manually updating the pod definition.
BTW I had also opened issue https://github.com/kubernetes/kops/issues/9695 for that and it's fixed.
So from kops 1.19 onwards you can do that using kops itself.

**Comment by jfassad** [comment]
Hello @a8j8i8t8 , could you please share the value you used for each option ? 

```
kubeControllerManager:
  authenticationKubeconfig: ???
  authorizationKubeconfig: ???
kubeScheduler:
  authenticationKubeconfig: ???
  authorizationKubeconfig: ???
```
Thank you

**Comment by a8j8i8t8** [comment]
@jfassad 

```
kubeControllerManager:
  authenticationKubeconfig: /var/lib/kube-controller-manager/kubeconfig
  authorizationKubeconfig: /var/lib/kube-controller-manager/kubeconfig
kubeScheduler:
  authenticationKubeconfig: /var/lib/kube-scheduler/kubeconfig
  authorizationKubeconfig: /var/lib/kube-scheduler/kubeconfig
```

**Comment by dmcnaught** [comment]
I can't seem to set the options in kops 1.19.1
```yaml
kubeControllerManager:
  authenticationKubeconfig: /var/lib/kube-controller-manager/kubeconfig
  authorizationKubeconfig: /var/lib/kube-controller-manager/kubeconfig
kubeScheduler:
  authenticationKubeconfig: /var/lib/kube-scheduler/kubeconfig
  authorizationKubeconfig: /var/lib/kube-scheduler/kubeconfig
  ```
  
  error parsing config: yaml: line 113: mapping values are not allowed in this context
