### ISSUE TITLE
Blackbox probe example

### ISSUE THREAD

**Issue by enkov** [prometheus-operator/kube-prometheus#644]
Hello!
I installed prometheus-operator with kube-prometheus and trying to create Probe.
Here is my config for Probe
```
{
  prometheus+:: {
    probeBlackboxExporter: {
      apiVersion: 'monitoring.coreos.com/v1',
      kind: 'Probe',
      metadata: {
        name: 'blackbox-exporter',
        namespace: 'monitoring',
        labels: {
          app: 'blackbox-exporter',
        },
      },
      spec: {
        jobName: 'blackbox',
        prober: {
          url: env.name + '-prometheus-blackbox-exporter',
          scheme: 'http',
          path: '/probe',
        },
        module: 'http_2xx',
        // interval: '15s',
        // scrapeTimeout: '3s',
        targets: {
          staticConfig: {
            static: [
              'https://ya.ru',
              'https://google.com',
            ],
          },
        },
      },
    },
  },
}
```
I can see that I have a Probe CRD and CR
k get probes -n monitoring
```
NAME                AGE
blackbox-exporter   179m
```

k describe probes blackbox-exporter -n monitoring
```
Name:         blackbox-exporter
Namespace:    monitoring
Labels:       app=blackbox-exporter
              qbec.io/application=kube-prometheus
              qbec.io/environment=kubesolo
Annotations:  qbec.io/component: kube_prometheus
              qbec.io/last-applied:
                H4sIAAAAAAAA/3SRy07rMBCG9+cx/nWa6LD0lj1ixQahauwOiantGWynKqry7shR6UWI5Uzmv+TzCaT+hXPxkmAQJfkq2aexd5JZSu8kDof/6LD3aQeD5yyW0SFypR1VgjmBUpJK1U...
API Version:  monitoring.coreos.com/v1
Kind:         Probe
Metadata:
  Creation Timestamp:  2020-08-13T06:00:07Z
  Generation:          2
  Managed Fields:
    API Version:  monitoring.coreos.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:qbec.io/component:
          f:qbec.io/last-applied:
        f:labels:
          .:
          f:app:
          f:qbec.io/application:
          f:qbec.io/environment:
      f:spec:
        .:
        f:jobName:
        f:module:
        f:prober:
          .:
          f:path:
          f:scheme:
          f:url:
        f:targets:
          .:
          f:staticConfig:
            .:
            f:static:
    Manager:         qbec
    Operation:       Update
    Time:            2020-08-13T06:56:42Z
  Resource Version:  17104482
  Self Link:         /apis/monitoring.coreos.com/v1/namespaces/monitoring/probes/blackbox-exporter
  UID:               5871f5a2-367a-413a-9235-71c10f71b562
Spec:
  Job Name:  blackbox
  Module:    http_2xx
  Prober:
    Path:    /probe
    Scheme:  http
    URL:     kubesolo-prometheus-blackbox-exporter
  Targets:
    Static Config:
      Static:
        https://ya.ru
        https://google.com
Events:  <none>
```

**Comment by enkov** [comment]
I found a solution!
We need to set
```
prometheus+:: {
    prometheus+: {
        spec+: {
            probeSelector: {},
        }
    }
}
```

**Comment by xuanyuanaosheng** [comment]
@enkov   The probe yml is:

```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-exporter
  namespace: monitoring-system
spec:
  jobName: http-get
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring-system.svc:19115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
      - https://baidu.com
      - http://qq.com
```
The serviceMonitor yml is 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.18.0
  name: blackbox-exporter
  namespace: monitoring-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: blackbox-exporter
      app.kubernetes.io/part-of: kube-prometheus
```

The service yml is 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.18.0
  name: blackbox-exporter
  namespace: monitoring-system 
spec:
  ports:
  - name: https
    port: 9115
    targetPort: https
  - name: probe
    port: 19115
    targetPort: http
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/part-of: kube-prometheus
```

----------------------

The service has two ports:

```
  ports:
  - name: https
    port: 9115
    targetPort: https
  - name: probe
    port: 19115
    targetPort: http
```

But  the service monitor has only one (9115) to scrape:

```
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
```

But the name: probe (port: 19115) has no scrape, How to repaire this?  whether to add a service monitor called probe?
