### ISSUE TITLE
Probe: cannot list resource "ingresses" in API group "extensions"

### ISSUE THREAD

**Issue by jperville** [prometheus-operator/kube-prometheus#650]
**What happened?**

I am trying to implement the bleeding edge Probe CRD in my prometheus stack.
Despite all my efforts, I cannot see my Probe in the prometheus /targets page.

**Did you expect to see some different?**

I expected to see my Probe listed in the prometheus /targets page (ideally with "Up" status)

**How to reproduce it (as minimally and precisely as possible)**:

I am trying to implement the bleeding edge Probe CRD in my prometheus stack.

I used kube-prometheus master as of 2020-08-18 and created a `Probe` object with the following contents :

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    name: myapp
  name: myapp
  namespace: platform # <--- change with whatever namespace prometheus-operator is deployed in
spec:
  jobName: probe/myapp
  interval: 15s
  module: http_2xx_external
  prober:
    url: blackbox-exporter:9115
  targets:
    ingress:
      selector:
        matchLabels:
          name: myapp
      namespaceSelector:
        matchNames:
        - apps
```

First, my Probe was not detected at all by prometheus-operator, issue which I worked around by following this comment : https://github.com/prometheus-operator/kube-prometheus/issues/644#issuecomment-673941152

Then, my Probe was found and prometheus-operator updated the prometheus configuration ; yet my Probe target still does not show up in Prometheus "targets" page.

In the logs of the prometheus-k8s-0 pod (prometheus container) I see the following messages:

> level=error ts=2020-08-18T16:28:25.526Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:429: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User \"system:serviceaccount:platform:prometheus-k8s\" cannot list resource \"ingresses\" in API group \"extensions\" in the namespace \"apps\""

Finally, I hacked the `manifests/prometheus-roleSpecificNamespaces.yaml` file to add the following snippet to each namespace-specific role definition:

```
      - apiGroups:
        - "extensions"
        resources:
        - ingresses
        verbs:
        - get
        - list
        - watch
```

Finally I can see my `Probe` listed in the prometheus `/targets` page.

**Environment**

* Prometheus Operator version:

    `v0.41.1`

* Kubernetes version information:

    `kubectl version`
    Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

    I booted my cluster using kubespray (version 2.13.1)

* Manifests:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    name: myapp
  name: myapp
  namespace: platform # <--- change with whatever namespace prometheus-operator is deployed in
spec:
  jobName: probe/myapp
  interval: 15s
  module: http_2xx_external
  prober:
    url: blackbox-exporter:9115
  targets:
    ingress:
      selector:
        matchLabels:
          name: myapp
      namespaceSelector:
        matchNames:
        - apps
```

* Prometheus Operator Logs:

```
# first log, before I applied the workaround from https://github.com/prometheus-operator/kube-prometheus/issues/644#issuecomment-673941152
level=debug ts=2020-08-18T16:23:14.41993527Z caller=operator.go:2010 component=prometheusoperator msg="selected PodMonitors" podmonitors=applications/minio-pod namespace=platform prometheus=k8s
level=debug ts=2020-08-18T16:23:14.419963756Z caller=operator.go:2040 component=prometheusoperator msg="filtering namespaces to select Probes from" namespaces=platform namespace=platform prometheus=k8s
```

* Prometheus Logs:

```
# second log, once prometheus-operator has detected my Probe object
level=error ts=2020-08-18T16:28:25.526Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:429: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User \"system:serviceaccount:platform:prometheus-k8s\" cannot list resource \"ingresses\" in API group \"extensions\" in the namespace \"backends\""
```

**Anything else we need to know?**:

I believe that several PRs are required (I will try to do them tomorrow).

First, `probeSelector: {}` must be present everywhere `podMonitorSelector: {}` is present.

```sh
julien:kube-prometheus(7603m|master!) $ fgrep -ry 'probeSelector:' *   
manifests/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml:              probeSelector:
julien:kube-prometheus(7603m|master!) $ fgrep -ry 'podMonitorSelector:' *
jsonnet/kube-prometheus/prometheus/prometheus.libsonnet:          podMonitorSelector: {},
manifests/prometheus-prometheus.yaml:  podMonitorSelector: {}
manifests/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml:              podMonitorSelector:
```

Second, the generated `manifests/prometheus-roleSpecificNamespaces.yaml` file must allow the prometheus service account to get/list/watch ingresses

And third, I still need to figure out why my Probe is detected when it exists in the same namespace as the prometheus-operator pod but not when I define it in another namespace.
