### ISSUE TITLE
DaemonSet Node-Exporter Security Error

### ISSUE THREAD

**Issue by okhuz** [prometheus-operator/kube-prometheus#678]
Kubernetes Version: 1.17
kube-prometheus: release 0.4

I have succesfuly deployed stack at my local machine but while deploying to our cluster faced an error which I get from running
`kubectl describe daemonset node-exporter`

and the error goes like that: 
`
Error creating: pods "node-exporter-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[1].hostPort: Invalid value: 9100: Host port 9100 is not allowed to be used. Allowed ports: [] spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[1].hostPort: Invalid value: 9100: Host port 9100 is not allowed to be used. Allowed ports: []]
`

Then a little bit rummaging around, I found this issue  #572 and tried to implement the PodSecurityPolicy. But I am not sure if I am in the right direction at finding the problem. Anybody else faced this issue?

It seems DaemonSet by-passes the PodSecurityPolicy. But I can't seem to figure out why.

**Comment by okhuz** [comment]
Problem for me was daemon-set-controller could not create the necessary pods. After a lot of testing following configuration worked.

`
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-permissive
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
- kind: ServiceAccount
  name: daemon-set-controller
  namespace: kube-system
- kind: ServiceAccount
  name: replicaset-controller
  namespace: kube-system
- kind: ServiceAccount
  name: job-controller
  namespace: kube-system
`

Giving those service accounts privilaged role in the monitoring namespace. DaemonSet worked as expected.

**Comment by lilic** [comment]
@okhuz are you saying these differ from what we have in our examples, if yes feel free to contribute those! :)

**Comment by okhuz** [comment]
I assume so. I am handed a already deployed on-premise kubernetes cluster with 7 nodes. So binding daemon set controller elevated role allowed the pod creation across the nodes. I can give more configuration details if you need. Giving PodSecurityPolicy did not work. I don't know why buy DaemonSet was by-passing the policy like it does not exist.

For example I have tried: 

**podsecuritypolicy.yaml**
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kube-prometheus
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
  - 'emptyDir'
  - 'secret'
  - 'downwardAPI'
  - 'configMap'
  - 'projected'
  hostPID: true
  hostIPC: false
  hostNetwork: true
#  allowedHostPaths: []
  allowedHostPaths:
  - pathPrefix: /proc
  - pathPrefix: /sys
  - pathPrefix: /
  hostPorts:
  - min: 9000
    max: 9200
```

**node-exporter-clusterRole.yaml**
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-exporter
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - kube-prometheus
```

ClusterRoleBinding is binding role with service account which is the service account of node-exporter-daemonset. Even directly binding policy to cluster role wasn't able to allow the pod creation and it was not even effecting the error message about Allowed Port etc. I don't know where I made an error, I am quite a newbie here.
