### ISSUE TITLE
Failed Discovery Check when registering the prometheus adapter to v1beta1.custom.metrics.k8s.io

### ISSUE THREAD

**Issue by tanujd11** [prometheus-operator/kube-prometheus#679]
I installed the kube-prometheus manifests as given in the readme. Changed the prometheus-adapter-apiSevice.yaml to 

```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: prometheus-adapter
    namespace: monitoring
  version: v1beta1
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: prometheus-adapter
    namespace: monitoring
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---

```

But the following error is coming
```

kubectl get apiservices | grep metrics
v1beta1.custom.metrics.k8s.io          monitoring/prometheus-adapter   False (FailedDiscoveryCheck)   5h54m
v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   True                           5h53m
``` 

```
kubectl describe apiservice v1beta1.custom.metrics.k8s.io
Name:         v1beta1.custom.metrics.k8s.io
Namespace:
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apiregistration.k8s.io/v1beta1","kind":"APIService","metadata":{"annotations":{},"name":"v1beta1.custom.metrics.k8s.io"},"s...
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2020-09-16T06:30:42Z
  Resource Version:    4348330
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.custom.metrics.k8s.io
  UID:                 f3510793-90ce-4347-ad0e-838f80723493
Spec:
  Group:                     custom.metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            prometheus-adapter
    Namespace:       monitoring
    Port:            443
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2020-09-16T06:30:42Z
    Message:               failing or missing response from https://10.136.70.51:6443/apis/custom.metrics.k8s.io/v1beta1: bad status from https://10.136.70.51:6443/apis/custom.metrics.k8s.io/v1beta1: 404
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```

Do I need to follow any other procedure for registering the service into custom.metrics.k8s.io apiGroup?
