### ISSUE TITLE
Need to deploy Operator with restricted rights in a K8S cluster

### ISSUE THREAD

**Issue by younid** [prometheus-operator/kube-prometheus#702]
**What did you do?**
Hello,

I Deployed Prometheus with Operator following the "getting started" guide from the project site (https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html)
And it worked correctly but after this I needed to deploy it on another cluster which is using RBAC and is more restrictive. The administrator asked me to change RBAC files to reduce rights granted to Operator.

Is it possible to have Prometheus Operator running with a minimum of granted rights (cluster wide one) and is it safe enouth if I reduce rights by myself in RBAC declaration (with DENY logs in apiserver logs) ?
Thank's for your help.

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-operator
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "get"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - "*"
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list"]
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: monitoring
  name: prometheus-operator
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["list", "get", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "create", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: monitoring
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.15.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      serviceAccountName: prometheus-operator

```

**What did you expect to see?**
I expected Operator to be used  with less rights granted on cluster wide.

**What did you see instead? Under which circumstances?**
I see some errors in apiserver logs according to Operator trying to use verbs with cluster wide rights.

```
RBAC DENY: user "system:serviceaccount:monitoring:prometheus-operator" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "configmaps" cluster-wide
RBAC DENY: user "system:serviceaccount:monitoring:prometheus-operator" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "secrets" cluster-wide
RBAC DENY: user "system:serviceaccount:monitoring:prometheus-operator" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "watch" resource "secrets" cluster-wide
RBAC DENY: user "system:serviceaccount:monitoring:prometheus-operator" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "watch" resource "configmaps" cluster-wide

```

**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
No error visible in Prometheus Operator logs
```
