### ISSUE TITLE
kube-prometheus:  CoreDNSDown

### ISSUE THREAD

**Issue by bitva77** [prometheus-operator/kube-prometheus#711]
**What did you do?**

Compiled/Installed kube-prometheus

**What did you expect to see?**

No alerts

**What did you see instead? Under which circumstances?**

`alert: CoreDNSDown
expr: absent(up{job="kube-dns"}
  == 1)`

**Environment**

Kubernetes 1.13.0 - installed via kubeadm.

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kubeadm

* Manifests:

```
cat prometheus-serviceMonitorCoreDNS.json.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: coredns
  name: coredns
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
```
``` 
   - alert: CoreDNSDown
      annotations:
        message: CoreDNS has disappeared from Prometheus target discovery.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-corednsdown
      expr: |
        absent(up{job="kube-dns"} == 1)
      for: 15m
      labels:
        severity: critical
 ```

The labels are correct:

```
kubectl get pods -l k8s-app=kube-dns -n kube-system
NAME                       READY   STATUS    RESTARTS   AGE
coredns-86c58d9df4-bhdln   1/1     Running   0          19d
coredns-86c58d9df4-pwrts   1/1     Running   0          19d
```

Not sure what the deal is.  Any thoughts?
