### ISSUE TITLE
Missing alert on 5xx of Prometheus Server

### ISSUE THREAD

**Issue by Purushotham233** [prometheus-operator/kube-prometheus#722]
**What is missing?**
In the default set of alerts added along with kube-prometheus, there is no alert on 5xx thrown by Prometheus server.
New Alert:
```
    - alert: Prometheus5xx
      annotations:
        description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has is throwing 5xx
        summary: Prometheus requests are failing with 5xx error responses
      expr: |
        sum(rate(prometheus_http_requests_total{code=~"5.."}[5m])) > 0
      for: 5m
      labels:
        severity: critical
```

Existing Alerts:
```
    - alert: PrometheusBadConfig
    - alert: PrometheusNotificationQueueRunningFull
    - alert: PrometheusErrorSendingAlertsToSomeAlertmanagers
    - alert: PrometheusErrorSendingAlertsToAnyAlertmanager
    - alert: PrometheusNotConnectedToAlertmanagers
    - alert: PrometheusTSDBReloadsFailing
    - alert: PrometheusTSDBCompactionsFailing
    - alert: PrometheusNotIngestingSamples
    - alert: PrometheusDuplicateTimestamps
    - alert: PrometheusOutOfOrderTimestamps
    - alert: PrometheusRemoteStorageFailures
    - alert: PrometheusRemoteWriteBehind
    - alert: PrometheusRemoteWriteDesiredShards
    - alert: PrometheusRuleFailures
    - alert: PrometheusMissingRuleEvaluations
```

**Why do we need it?**
It can alert on issues which are not covered by the above alerts.

**Environment**

* kube-prometheus version: v0.5.0
