### ISSUE TITLE
PodMonitor is not working as expected

### ISSUE THREAD

**Issue by a8j8i8t8** [prometheus-operator/kube-prometheus#726]
**What happened?**
- Installed kube-prometheus from master branch on kubernetes 1.18.9
- Created podmonitor resource as below
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:   
  name: fluent-bit
  namespace: monitoring
  labels:
     k8s-app: fluent-bit
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: fluent-bit
  namespaceSelector:
    matchNames:
      - monitoring
  podMetricsEndpoints:
  - interval: 30s
    path: /api/v1/metrics/prometheus
    port: "2020" 
```
- new target is shown in prometheus but without any active entry

**Environment**

* Prometheus Operator version:

    `v0.42.1`
    

* Kubernetes version information:

    `1.18.9`
    

* Kubernetes cluster kind:

    Cluster is created using Kops.

**Anything else we need to know?**:
When I create podmonitor, following is being added to prometheus configuration.
```
- job_name: monitoring/fluent-bit/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /api/v1/metrics/prometheus
  scheme: http
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - monitoring
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_k8s_app]
    separator: ;
    regex: fluent-bit
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    separator: ;
    regex: "2020"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: job
    replacement: monitoring/fluent-bit
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_k8s_app]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: "2020"
    action: replace
```

**Comment by dgrisonnet** [comment]
From the manifest you shared, the error seems to be coming from the port you specified. The port field is meant for the container port name and not its value.

For example, with the following container configuration, you should set the port to `http` instead of `2020`.
```yaml
ports:
  - containerPort: 2020
    name: http
```
