### ISSUE TITLE
How change the statefulset prometheus-k8s?

### ISSUE THREAD

**Issue by liaoqiArno** [prometheus-operator/kube-prometheus#840]
I want add " --web.external-url" to prometheus,
```
 kubectl  -n monitoring  edit statefulsets.apps  prometheus-k8s

- args:
        - --web.console.templates=/etc/prometheus/consoles
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention.time=24h
        - --web.enable-lifecycle
        - --storage.tsdb.no-lockfile
        - --web.route-prefix=/
        -  --web.external-url=xxxx
  
```
But I found Nothing change.
How can I do ?
Thanks，Thank you very much.   

```

**Comment by lilic** [comment]
Hey! You need to edit the custom resource Prometheus that you created and edit t he `externalUrl` field.

https://github.com/prometheus-operator/prometheus-operator/blob/22aaf848a27f6e45702131e22a596778686068d5/Documentation/api.md#prometheusspec

Short example:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  externalUrl: http://{EXTERNAL_IP}/prometheus
```
