### ISSUE TITLE
Service monitor for Grafana does not use correct selector

### ISSUE THREAD

**Issue by lanmarti** [prometheus-operator/kube-prometheus#884]
**What happened?**
Grafana service monitor selector does not match new grafana labels.

Grafana service monitor definition:
```
spec:
  endpoints:
  - interval: 15s
    port: http
  selector:
    matchLabels:
      app: grafana
```
Grafana service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 6.4.3
  name: grafana
 ```
**Did you expect to see some different?**
I'd expect to see a label in the service monitor's spec.selector matching the service's metadata.labels

**How to reproduce it (as minimally and precisely as possible)**:
Do a fresh install, apply generated manifests.

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.35.1`

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    kubeadm

**Anything else we need to know?**:
I'll make a PR with a hardcoded matching label (`app.kubernetes.io/name: grafana`). 
I have little experience with jsonnet. Perhaps there's a way to add the correct labels dynamically, to prevent this sort of problem on label change?
