### ISSUE TITLE
Unable to obtain kube-controller-manager and kube-scheduler monitoring information

### ISSUE THREAD

**Issue by XiaoMuYi** [prometheus-operator/kube-prometheus#913]
**What did you do?**
I use helm to deploy prometheus-operator to monitor binary kubernetes clusters. However, it is not possible to obtain kube-controller-manager and kube-scheduler component data at present.
![image](https://user-images.githubusercontent.com/34268642/50535404-8f57df00-0b84-11e9-85b9-abc3206df5db.png)

**What did you expect to see?**
I want to know how prometheus-operator monitors kubernetes Masters.

**What did you see instead? Under which circumstances?**
Look at the EP created by prometheus-operator and find that the ENDPOINTS field is <none>.
```
$ kubectl get ep -n kube-system |grep "prometheus-operator*"
prometheus-operator-coredns                   172.20.4.2:9153,172.20.5.4:9153                                         36m
prometheus-operator-kube-controller-manager   <none>                                                                  36m
prometheus-operator-kube-etcd                 172.17.80.26:2379,172.17.80.27:2379,172.17.80.28:2379                   36m
prometheus-operator-kube-scheduler            <none>                                                                  36m
prometheus-operator-kubelet                   172.17.80.26:10255,172.17.80.27:10255,172.17.80.28:10255 + 15 more...   28d
```
Service port listening 0.0.0.0.
```
$ ss -lnpt |egrep "kube-controller|kube-scheduler"
LISTEN     0      2048        :::10251                   :::*                   users:(("kube-scheduler",pid=41235,fd=3))
LISTEN     0      2048        :::10252                   :::*                   users:(("kube-controller",pid=41326,fd=3))
LISTEN     0      2048        :::10257                   :::*                   users:(("kube-controller",pid=41326,fd=5))
```
**Environment**

* Prometheus Operator version:
```
$ grep -A 3 "image:" /data/prometheus-operator-01/values.yaml
    image:
      repository: quay.io/prometheus/alertmanager
      tag: v0.15.3

--
  image:
    repository: quay.io/coreos/prometheus-operator
    tag: v0.26.0
    pullPolicy: IfNotPresent
--
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.5.0
```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
  Binary manual installation

* Manifests:

* Prometheus Operator Logs:

**Comment by weibeld** [comment]
@syednadeembe you're using the `--address` extra flag for kube-controller-manager and kube-scheduler, which is deprecated. The new flag is `--bind-address`. So, the kubeadm config file should look like this:

```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
...
controllerManager:
  extraArgs:
    bind-address: 0.0.0.0
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
```

**Comment by syednadeembe** [comment]
the pod has the required flag and i can verify that while doing the pod describe:

spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=0.0.0.0
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=192.168.0.0/16
However the problem still remains. 

#######################################################################
Also will like to know, does editing kubeadm-config configmap update the kubeadm config ?
Example: kubectl edit cm kubeadm-config -n kube-system
will this update my cluster at the runtime ?

**Comment by syednadeembe** [comment]
what is the recommended way to update kubeadm config file for a running cluster ?

**Comment by syednadeembe** [comment]
Resolved
########################################
After couple of endless nights, alladin's gini finally came to help me :) @retr0h  comment
########################################
Etcd, kube-controller-manager and kube-scheduler are servers that by default server request on https when one uses kubeadm to install the cluster.

The default values.yml file which comes with prometheus helm release only scraps at http unless specified elsewise.
Follow was the course of action for me:

helm fetch prometheus-community/prometheus-operator ### to get the default values that had been used
// updated the values.yml file 

## Component scraping the kube controller manager
##
kubeControllerManager:
  enabled: true

  ## If your kube controller manager is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints: []
  # - 10.60.27.248
  # - 10.141.4.23
  # - 10.141.4.24

  ## If using kubeControllerManager.endpoints only the port and targetPort are used
  ##
  service:
    port: 10257
    targetPort: 10257
    ## Enable scraping kube-controller-manager over https.
    ## Requires proper certs (not self-signed) and delegated authentication/authorization checks
    ##
    https: true
    # Skip TLS certificate validation when scraping
    insecureSkipVerify: true

// Ran the helm upgrade
helm upgrade prometheus-operator prometheus-operator/ -n <name_space>

**Comment by weibeld** [comment]
Since setting `--bind-address` to `0.0.0.0` might expose the port to the Internet (as reported in <https://github.com/kubernetes/kubeadm/issues/2244#issuecomment-763294722>), an alternative solution is using a local proxy on each master node that exposes the metrics in a secure way.

This could be implemented with an HAProxy container run on each master node with a DaemonSet with the following configuration:

```haproxy
defaults
  mode http
  timeout connect 5000ms
  timeout client 5000ms
  timeout server 5000ms
  default-server maxconn 10

frontend kube-controller-manager
  bind ${NODE_IP}:10257
  http-request deny if !{ path /metrics }
  default_backend kube-controller-manager
backend kube-controller-manager
  server kube-controller-manager 127.0.0.1:10257 ssl verify none

frontend kube-scheduler
  bind ${NODE_IP}:10259
  http-request deny if !{ path /metrics }
  default_backend kube-scheduler
backend kube-scheduler
  server kube-scheduler 127.0.0.1:10259 ssl verify none
```

This would listen on port 10257 on the node's IP address for requests to the `/metrics` path and forward these requests to the only locally available port 10257 of kube-controller-manager on the loopack interface.

The `$NODE_IP` environment variable can be injected into the Pod with a `fieldRef` in the Pod spec:

```yaml
env:
- name: NODE_IP
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
```

The proxy Pod must also run in the `hostNetwork` like the kube-controller-manager Pod, so that the former can access the latter's loopback interface.

**Comment by sachinmsft** [comment]
@weibeld should not you need to pass bearer token with cluster role binding on scrapping metrics endpoint. ?

**Comment by KlavsKlavsen** [comment]
> This could be implemented with an HAProxy container run on each master node with a DaemonSet with the following configuration:

@weibeld Sounds like a fantastic solution - albeit a big more complex ofcourse :)
Have you implemented it with the kube-prometheus build jsonnet system - or using the Helm chart?
I would be VERY happy if you would share some more details about this?

As I understand it - we need a daemonset running haproxy - with the config you mentioned above - and a modified service definition from Prometheus - to make it try to reach the nodes kubecontrolermanager and kube-scheduler pods - via node-ip instead

**Comment by weibeld** [comment]
@KlavsKlavsen I used Kustomize, since all the other services in the cluster were deployed with Kustomize. But it really doesn't matter how you deploy the DaemonSet, best if you just deploy it like any other application in your cluster, e.g. Helm if you usually use Helm.

Once you have the DaemonSet, you can scrape the exposed ports as a normal Prometheus target, i.e. either with a Service and a ServiceMonitor, or only a PodMonitor.

**Comment by weibeld** [comment]
@sachinmsft
> @weibeld should not you need to pass bearer token with cluster role binding on scrapping metrics endpoint. ?

Yes, this seems to be required for kube-controller-manager and kube-scheduler. You can create a Secret with a ServiceAccount token with the appropriate permissions like this:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-endpoint-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-endpoint-reader
rules:
  - nonResourceURLs: [/metrics]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-endpoint-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-endpoint-reader
subjects:
  - kind: ServiceAccount
    name: metrics-endpoint-reader
    namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-endpoint-reader
  annotations:
    kubernetes.io/service-account.name: metrics-endpoint-reader
type: kubernetes.io/service-account-token
```

Then you can reference the created Secret by its name (e.g. `metrics-endpoint-reader`) in the `bearerTokenSecret` field of either a [ServiceMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/ac2f3b74ea32f021f36b3a8c47f39f7901e83cd0/Documentation/api.md#endpoint) or a [PodMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/ac2f3b74ea32f021f36b3a8c47f39f7901e83cd0/Documentation/api.md#podmetricsendpoint) (see [comment](https://github.com/prometheus-operator/kube-prometheus/issues/913#issuecomment-1065494045) above).
