### ISSUE TITLE
Load Grafana dashboard from labelled ConfigMaps

### ISSUE THREAD

**Issue by hamid-elaosta** [prometheus-operator/kube-prometheus#922]
**What is missing?**

The ability to load Grafana dashboards from ConfigMap.

[This](https://github.com/helm/charts/tree/master/stable/prometheus-operator) chart has a value `grafana.sidecar.dashboards.enabled`, which enables, by their definition: "... the Grafana sidecar to automatically load dashboards with a label {{ grafana.sidecar.dashboards.label }}=1".

Example from [SO](https://stackoverflow.com/questions/57322022/stable-prometheus-operator-adding-persistent-grafana-dashboards):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-grafana-dashboard
  namespace: monitoring
  labels:
     grafana_dashboard: "1"
data:
  etcd-dashboard.json: |-
{JSON}
```

**Why do we need it?**
Provide an easy way to load additional Grafana dashboards from ConfigMap as part of a workload's deployment, without additional knowledge of the cluster monitoring configuration outside of the label required to do so.

**Environment**

* kube-prometheus version: release-0.7

**Anything else we need to know?**:

Q: Could the choice of label/value be improved over the example/existing operator?
Q: Is there any benefit to providing a name for the workload in the label value as opposed to a "1"? If not, a boolean may be preferred.

**Comment by vallard** [comment]
I had this in mine: 
```
grafana:
  sidecar:
    enabled: true
    dashboards:
      label: grafana_dashboard
      labelValue: 1
```

It didn't work for me unless I specified the `labelValue`.

**Comment by PetzJohannes** [comment]
This is probably a Grafana related problem.
See: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L631

I had to enable this for all namespaces:
```
grafana:
  sidecar:
    dashboards:
      labelValue: 1
      searchNamespace: "ALL"
```
