### ISSUE TITLE
cannot list resource "ingresses"

### ISSUE THREAD

**Issue by huangweikuna** [prometheus-operator/kube-prometheus#993]
version: v1.18.9-eks
I need ingress information, but because I don’t have permission to access, the following error occurred
```yaml
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
stringData:
  prometheus-additional.yaml: |-
    - job_name: 'kubernetes-ingresses'
      metrics_path: /probe
      params:
        module: [http_2xx]
      kubernetes_sd_configs:
      - role: ingress
      relabel_configs:
      - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_http_probe]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]
        regex: (.+);(.+);(.+)
        replacement: ${1}://${2}${3}
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter.monitoring:19115
      - source_labels: [__param_target]
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_ingress_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_ingress_name]
        target_label: kubernetes_name
type: Opaque
```
```k logs -n monitoring prometheus-k8s-0 -f -c prometheus --tail=100```

> level=error ts=2021-03-02T06:02:33.939Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:429: Failed to list *v1beta1.Ingress: ingresses.networking.k8s.io is forbidden: User \"system:serviceaccount:monitoring:prometheus-k8s\" cannot list resource \"ingresses\" in API group \"networking.k8s.io\" at the cluster scope"  

So I added the access permissions to the ClusterRole of prometheus, but it still reported an error. Did I miss the configuration?

this:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
    - ""
  resources:
    - nodes
    - services
    - endpoints
    - pods
    - nodes/proxy
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - configmaps
    - nodes/metrics
  verbs:
    - get
- nonResourceURLs:
    - /metrics
  verbs:
    - get
- apiGroups:
    - extensions
  resources:
    - ingresses
  verbs:
    - list
    - watch
```

**Comment by huangweikuna** [comment]
i'm so stupid


solution:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
    - ""
  resources:
    - nodes
    - services
    - endpoints
    - pods
    - nodes/proxy
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - configmaps
    - nodes/metrics
  verbs:
    - get
- nonResourceURLs:
    - /metrics
  verbs:
    - get
- apiGroups:
    - extensions
    - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - list
    - watch
    - get
```
